// Contributors — ṛṣis, ācāryas, scientists, poets, saints, reformers.
// All copy is original synthesis intended for an educational platform.

// Full contribution detail shown in the click-through modal.
// Added in batches of five; cards without a `detail` fall back to the blurb.
export type ContributorDetail = {
  intro: string;            // expanded opening paragraph
  contributions: string[];  // the principal contributions, one per line
  legacy: string;           // closing paragraph on influence / legacy
};

export type Contributor = {
  id: string;
  name: string;        // Roman / IAST transliteration
  deva: string;        // Devanāgarī
  seal: string;        // 1–2 Devanāgarī characters shown in the seal medallion
  epithet?: string;    // honourific or descriptor (Roman)
  epithetDeva?: string;
  dates: string;       // Roman dates / range
  datesDeva: string;
  era: 'vedic' | 'classical' | 'medieval' | 'modern';
  tradition: string;   // discipline / school (Roman)
  traditionDeva: string;
  blurb: string;
  works: string[];     // 2–4 short tags
  href?: string;       // optional link to a related section page
  detail?: ContributorDetail; // full contribution write-up for the modal
};

export const CONTRIBUTORS: Contributor[] = [
  // ─────────────────────────────── Vedic Era ──────────────────────────────────
  {
    id: 'vyasa',
    name: 'Vyāsa',
    deva: 'व्यासः',
    seal: 'व्या',
    epithet: 'Veda-Vyāsa',
    epithetDeva: 'वेदव्यासः',
    dates: 'Vedic period',
    datesDeva: 'वैदिक काल',
    era: 'vedic',
    tradition: 'Śruti redaction · Itihāsa',
    traditionDeva: 'श्रुति-संपादन · इतिहास',
    blurb: 'Divided the one Veda into four and arranged the Brāhmaṇas; composed the Mahābhārata, the Brahma-Sūtra and the eighteen Purāṇas — the architect of the canon.',
    works: ['Veda redaction', 'Mahābhārata', 'Brahma-Sūtra', '18 Purāṇas'],
    href: '/vedas/',
    detail: {
      intro:
        'Vyāsa — literally “the compiler” — stands at the threshold of the recorded tradition. Born Kṛṣṇa Dvaipāyana, he is remembered less as a single author than as the organising intelligence who gave the inherited revelation its lasting architecture.',
      contributions: [
        'Divided the single primordial Veda into the four Saṃhitās — Ṛk, Yajus, Sāman and Atharvan — and assigned each to a disciple, founding the four lines of Vedic transmission.',
        'Arranged the Brāhmaṇa prose and the ritual apparatus that frames the hymns, fixing the relationship between mantra and rite.',
        'Composed the Mahābhārata, the hundred-thousand-verse “fifth Veda” in which the Bhagavad-Gītā is set.',
        'Condensed the teaching of the Upaniṣads into the 555 aphorisms of the Brahma-Sūtra — the text every later Vedāntin is obliged to interpret.',
        'Traditionally credited with the eighteen Mahāpurāṇas, the encyclopaedic narrative vehicle of popular dharma.',
      ],
      legacy:
        'Because the very act of editing the canon is called vyāsa, every later redactor works in his shadow. The four Vedic schools, the epic tradition and the entire enterprise of Vedānta all trace their starting point to him.',
    },
  },
  {
    id: 'valmiki',
    name: 'Vālmīki',
    deva: 'वाल्मीकिः',
    seal: 'वा',
    epithet: 'Ādi-kavi',
    epithetDeva: 'आदिकविः',
    dates: 'Late Vedic period',
    datesDeva: 'उत्तर वैदिक काल',
    era: 'vedic',
    tradition: 'Itihāsa · Sanskrit kāvya',
    traditionDeva: 'इतिहास · संस्कृत काव्य',
    blurb: 'The “first poet,” to whom grief gave the first śloka. His Rāmāyaṇa fixes the shape of every later Indic narrative.',
    works: ['Rāmāyaṇa', 'Anuṣṭubh metre'],
    href: '/itihasa/',
    detail: {
      intro:
        'Vālmīki is honoured as the ādi-kavi, the first poet — the figure in whom deliberate, metrical literature is said to begin. Tradition tells that the sight of a hunter killing one of a pair of mating cranes wrung from him the first śloka, grief crystallising into measured speech.',
      contributions: [
        'Composed the Rāmāyaṇa, the twenty-four-thousand-verse epic that became the template for narrative poetry across the subcontinent and beyond.',
        'Gave the anuṣṭubh śloka its classical shape — the thirty-two-syllable couplet that remains the default metre of Sanskrit storytelling.',
        'Established the conventions of mahākāvya: the heroic protagonist, the structured cantos, and the set descriptions of cities, seasons and battles.',
      ],
      legacy:
        'Every later retelling — Tamil, Awadhi, Bengali, Telugu, Southeast Asian — measures itself against his text. In the Indic imagination the shape of the ideal man, the ideal kingdom and the ideal poem all descend from Vālmīki.',
    },
  },
  {
    id: 'vasishtha',
    name: 'Vasiṣṭha',
    deva: 'वसिष्ठः',
    seal: 'व',
    epithet: 'Saptarṣi',
    epithetDeva: 'सप्तर्षिः',
    dates: 'Ṛgvedic period',
    datesDeva: 'ऋग्वेदकाल',
    era: 'vedic',
    tradition: 'Ṛgveda · Maṇḍala VII',
    traditionDeva: 'ऋग्वेद · सप्तम मण्डल',
    blurb: 'Seer of the seventh maṇḍala and preceptor of the Ikṣvāku line. The Yoga-Vāsiṣṭha carries his name into later Advaita.',
    works: ['Ṛgveda Maṇḍala VII', 'Yoga-Vāsiṣṭha (attrib.)'],
    detail: {
      intro:
        'Vasiṣṭha is counted among the saptarṣis, the seven seers, and is the ṛṣi of the seventh maṇḍala of the Ṛgveda. He appears as the family priest (purohita) of the Ikṣvāku kings — the dynasty into which Rāma is later born.',
      contributions: [
        'Seer of the entire seventh maṇḍala of the Ṛgveda, including the hymns to Varuṇa that are among the tradition’s most searching meditations on guilt and grace.',
        'Embodies the office of the brahman purohita — the priest who binds the kingdom’s prosperity to right ritual conduct.',
        'Lends his name to the Vasiṣṭha Dharmasūtra and, in later tradition, to the Yoga-Vāsiṣṭha, a vast Advaitic dialogue addressed to Rāma.',
      ],
      legacy:
        'As the archetypal preceptor of kings, Vasiṣṭha stands for the ideal of priestly counsel to royal power — the steady brahminical pole set against the restless kṣatriya energy of his rival Viśvāmitra.',
    },
  },
  {
    id: 'vishvamitra',
    name: 'Viśvāmitra',
    deva: 'विश्वामित्रः',
    seal: 'वि',
    epithet: 'Saptarṣi',
    epithetDeva: 'सप्तर्षिः',
    dates: 'Ṛgvedic period',
    datesDeva: 'ऋग्वेदकाल',
    era: 'vedic',
    tradition: 'Ṛgveda · Maṇḍala III',
    traditionDeva: 'ऋग्वेद · तृतीय मण्डल',
    blurb: 'The kṣatriya who became a brahmarṣi. Seer of the third maṇḍala and of the Gāyatrī — the mantra recited every dawn for three thousand years.',
    works: ['Ṛgveda Maṇḍala III', 'Gāyatrī Mantra'],
    detail: {
      intro:
        'Viśvāmitra is the great exception among the seers — a king by birth who, by sheer ascetic resolve, won the rank of brahmarṣi that no warrior was thought able to reach. His rivalry with Vasiṣṭha is one of the oldest narrative threads in the tradition.',
      contributions: [
        'Seer of the third maṇḍala of the Ṛgveda.',
        'Revealed the Gāyatrī mantra (Ṛgveda 3.62.10) — the verse to Savitṛ recited at dawn for three millennia and the heart of Vedic initiation.',
        'In the Rāmāyaṇa, the sage who takes the young Rāma and Lakṣmaṇa as his charges and arms them for their task.',
      ],
      legacy:
        'Viśvāmitra is the standing proof, inside the tradition’s own myth, that spiritual attainment is open to effort rather than fixed by birth — a theme later reformers return to again and again.',
    },
  },
  {
    id: 'bharadvaja',
    name: 'Bharadvāja',
    deva: 'भरद्वाजः',
    seal: 'भ',
    epithet: 'Saptarṣi',
    epithetDeva: 'सप्तर्षिः',
    dates: 'Ṛgvedic period',
    datesDeva: 'ऋग्वेदकाल',
    era: 'vedic',
    tradition: 'Ṛgveda · Maṇḍala VI',
    traditionDeva: 'ऋग्वेद · षष्ठ मण्डल',
    blurb: 'Seer of the sixth maṇḍala. His gotra continues into both Āyurveda and Dhanurveda — a single line carries medicine and arms.',
    works: ['Ṛgveda Maṇḍala VI', 'Bharadvāja Saṃhitā (Āyurveda)'],
    detail: {
      intro:
        'Bharadvāja is the seer of the sixth maṇḍala of the Ṛgveda and the founder of one of the most populous of brahmin gotras. His name marks a lineage that carries, unusually, both the healing arts and the science of arms.',
      contributions: [
        'Seer of the sixth maṇḍala of the Ṛgveda.',
        'Founding figure of the Bharadvāja gotra, one of the principal pravara lineages.',
        'Named as an early authority in the Āyurvedic tradition — the Caraka-Saṃhitā opens by tracing medical knowledge through Bharadvāja.',
        'Associated in later texts with the Dhanurveda, the science of archery and warfare.',
      ],
      legacy:
        'Through the gotra system and the twin inheritances of medicine and arms, Bharadvāja’s name threads through both the Āyurvedic and the martial traditions — a single ṛṣi at the root of two very different sciences.',
    },
  },
  {
    id: 'yajnavalkya',
    name: 'Yājñavalkya',
    deva: 'याज्ञवल्क्यः',
    seal: 'या',
    dates: 'c. 8th–7th c. BCE',
    datesDeva: 'इ.स.पूर्व ८–७ शतक',
    era: 'vedic',
    tradition: 'Upaniṣad · Dharma · Yajurveda',
    traditionDeva: 'उपनिषद् · धर्म · यजुर्वेद',
    blurb: 'Central voice of the Bṛhadāraṇyaka. Compiled the Śukla Yajurveda; the Yājñavalkya-Smṛti carries his name as a rule-book of dharma.',
    works: ['Bṛhadāraṇyaka dialogues', 'Śukla Yajurveda', 'Yājñavalkya-Smṛti'],
    href: '/upanishads/',
  },
  {
    id: 'gargi',
    name: 'Gārgī Vāchaknavī',
    deva: 'गार्गी वाचक्नवी',
    seal: 'गा',
    epithet: 'Brahmavādinī',
    epithetDeva: 'ब्रह्मवादिनी',
    dates: 'c. 8th c. BCE',
    datesDeva: 'इ.स.पूर्व ८ शतक',
    era: 'vedic',
    tradition: 'Upaniṣad · philosophy',
    traditionDeva: 'उपनिषद् · तत्त्वज्ञान',
    blurb: 'At Janaka’s court she pressed Yājñavalkya with the question on which all metaphysics turns — and was the only interlocutor told to stop.',
    works: ['Bṛhadāraṇyaka 3.6, 3.8'],
    href: '/upanishads/',
  },
  {
    id: 'maitreyi',
    name: 'Maitreyī',
    deva: 'मैत्रेयी',
    seal: 'मै',
    epithet: 'Brahmavādinī',
    epithetDeva: 'ब्रह्मवादिनी',
    dates: 'c. 8th c. BCE',
    datesDeva: 'इ.स.पूर्व ८ शतक',
    era: 'vedic',
    tradition: 'Upaniṣad · philosophy',
    traditionDeva: 'उपनिषद् · तत्त्वज्ञान',
    blurb: 'Refused her husband’s wealth and asked for what makes a thing dear instead. The Maitreyī dialogue opens the Upaniṣadic teaching on the Self.',
    works: ['Bṛhadāraṇyaka 2.4, 4.5'],
    href: '/upanishads/',
  },
  {
    id: 'agastya',
    name: 'Agastya',
    deva: 'अगस्त्यः',
    seal: 'अ',
    dates: 'Vedic period',
    datesDeva: 'वैदिक काल',
    era: 'vedic',
    tradition: 'Ṛgveda · southern transmission',
    traditionDeva: 'ऋग्वेद · दक्षिण प्रसार',
    blurb: 'Seer credited with carrying Vedic dharma south of the Vindhyas. Lopāmudrā shares his hymns; the southern grammars and siddha lineages claim him as ādi-guru.',
    works: ['Ṛgveda hymns (with Lopāmudrā)', 'Agastya-Saṃhitā'],
  },

  // ───────────────────────────── Classical Era ────────────────────────────────
  {
    id: 'mahavira',
    name: 'Mahāvīra',
    deva: 'महावीरः',
    seal: 'म',
    epithet: '24th Tīrthaṅkara',
    epithetDeva: '२४वे तीर्थंकर',
    dates: '599–527 BCE',
    datesDeva: 'इ.स.पूर्व ५९९–५२७',
    era: 'classical',
    tradition: 'Jaina darśana',
    traditionDeva: 'जैन दर्शन',
    blurb: 'Recensed and systematised the Jaina path of ahiṃsā, anekāntavāda and aparigraha — the ethics of multi-sided truth and radical non-harm.',
    works: ['Five mahāvratas', 'Syādvāda', 'Āgama tradition'],
    href: '/nastika-darshanas/',
  },
  {
    id: 'buddha',
    name: 'Gautama Buddha',
    deva: 'गौतम बुद्धः',
    seal: 'बु',
    epithet: 'Śākyamuni',
    epithetDeva: 'शाक्यमुनिः',
    dates: 'c. 563–483 BCE',
    datesDeva: 'इ.स.पूर्व ५६३–४८३',
    era: 'classical',
    tradition: 'Bauddha darśana',
    traditionDeva: 'बौद्ध दर्शन',
    blurb: 'Set the Four Noble Truths and the Eightfold Path. The middle way reframed dharma without God, soul, or sacrifice — and travelled further than any Indian school.',
    works: ['Dhammacakkappavattana', 'Vinaya', 'Sutta Piṭaka'],
    href: '/nastika-darshanas/',
  },
  {
    id: 'panini',
    name: 'Pāṇini',
    deva: 'पाणिनिः',
    seal: 'पा',
    dates: 'c. 5th–4th c. BCE',
    datesDeva: 'इ.स.पूर्व ५–४ शतक',
    era: 'classical',
    tradition: 'Vyākaraṇa · Vedāṅga',
    traditionDeva: 'व्याकरण · वेदाङ्ग',
    blurb: 'The Aṣṭādhyāyī: nearly four thousand generative rules that derive every well-formed Sanskrit utterance. The most precise grammar written in any ancient language.',
    works: ['Aṣṭādhyāyī', 'Dhātupāṭha', 'Gaṇapāṭha'],
    href: '/vedangas/',
  },
  {
    id: 'kautilya',
    name: 'Cāṇakya / Kauṭilya',
    deva: 'कौटिल्यः',
    seal: 'कौ',
    epithet: 'Viṣṇugupta',
    epithetDeva: 'विष्णुगुप्तः',
    dates: 'c. 4th c. BCE',
    datesDeva: 'इ.स.पूर्व ४ शतक',
    era: 'classical',
    tradition: 'Arthaśāstra · statecraft',
    traditionDeva: 'अर्थशास्त्र · राजनीति',
    blurb: 'Architect of the Mauryan order. The Arthaśāstra reads economics, intelligence, foreign policy and law as a single integrated science of rule.',
    works: ['Arthaśāstra', 'Cāṇakya-nīti'],
  },
  {
    id: 'patanjali',
    name: 'Patañjali',
    deva: 'पतञ्जलिः',
    seal: 'प',
    dates: 'c. 2nd c. BCE',
    datesDeva: 'इ.स.पूर्व २ शतक',
    era: 'classical',
    tradition: 'Yoga · Vyākaraṇa',
    traditionDeva: 'योग · व्याकरण',
    blurb: 'The Yoga-Sūtra distils meditative practice into 196 aphorisms. The same tradition assigns him the Mahābhāṣya — the great commentary on Pāṇini.',
    works: ['Yoga-Sūtra', 'Mahābhāṣya'],
    href: '/darshanas/',
  },
  {
    id: 'kapila',
    name: 'Kapila',
    deva: 'कपिलः',
    seal: 'क',
    dates: 'pre-classical',
    datesDeva: 'पूर्व-अभिजात काल',
    era: 'classical',
    tradition: 'Sāṅkhya darśana',
    traditionDeva: 'सांख्य दर्शन',
    blurb: 'Founding ācārya of Sāṅkhya. The dualism of puruṣa and prakṛti enters the Gītā, Yoga, Āyurveda and every later school as a default working vocabulary.',
    works: ['Sāṅkhya-Sūtra (attrib.)', 'Sāṅkhya-Kārikā (line)'],
    href: '/darshanas/',
  },
  {
    id: 'gautama-nyaya',
    name: 'Gautama (Akṣapāda)',
    deva: 'अक्षपाद गौतमः',
    seal: 'गौ',
    dates: 'c. 2nd c. BCE',
    datesDeva: 'इ.स.पूर्व २ शतक',
    era: 'classical',
    tradition: 'Nyāya darśana',
    traditionDeva: 'न्याय दर्शन',
    blurb: 'The Nyāya-Sūtra: the formal theory of pramāṇa (means of knowledge) and the five-membered syllogism that powered Indic debate for two millennia.',
    works: ['Nyāya-Sūtra'],
    href: '/darshanas/',
  },
  {
    id: 'kanada',
    name: 'Kaṇāda',
    deva: 'कणादः',
    seal: 'क',
    epithet: 'Ulūka',
    epithetDeva: 'उलूकः',
    dates: 'c. 2nd c. BCE',
    datesDeva: 'इ.स.पूर्व २ शतक',
    era: 'classical',
    tradition: 'Vaiśeṣika darśana',
    traditionDeva: 'वैशेषिक दर्शन',
    blurb: 'The Vaiśeṣika-Sūtra: an atomistic ontology of substance, quality and motion two thousand years before Dalton — and paired with Nyāya into a single school.',
    works: ['Vaiśeṣika-Sūtra'],
    href: '/darshanas/',
  },
  {
    id: 'jaimini',
    name: 'Jaimini',
    deva: 'जैमिनिः',
    seal: 'जै',
    dates: 'c. 3rd c. BCE',
    datesDeva: 'इ.स.पूर्व ३ शतक',
    era: 'classical',
    tradition: 'Pūrva Mīmāṃsā',
    traditionDeva: 'पूर्व मीमांसा',
    blurb: 'The Pūrva-Mīmāṃsā-Sūtra: the hermeneutics of Vedic ritual and the theory of injunction (vidhi) that later jurisprudence inherits whole.',
    works: ['Pūrva-Mīmāṃsā-Sūtra'],
    href: '/darshanas/',
  },
  {
    id: 'badarayana',
    name: 'Bādarāyaṇa',
    deva: 'बादरायणः',
    seal: 'बा',
    dates: 'c. 2nd c. BCE',
    datesDeva: 'इ.स.पूर्व २ शतक',
    era: 'classical',
    tradition: 'Vedānta · Uttara Mīmāṃsā',
    traditionDeva: 'वेदान्त · उत्तर मीमांसा',
    blurb: 'The Brahma-Sūtra summarises the Upaniṣads in 555 aphorisms. Every later Vedāntin — Śaṅkara, Rāmānuja, Madhva — writes a bhāṣya on it.',
    works: ['Brahma-Sūtra'],
    href: '/darshanas/',
  },
  {
    id: 'bharata-muni',
    name: 'Bharata Muni',
    deva: 'भरतमुनिः',
    seal: 'भ',
    dates: 'c. 200 BCE – 200 CE',
    datesDeva: 'इ.स.पूर्व २०० – इ.स. २००',
    era: 'classical',
    tradition: 'Nāṭyaśāstra · aesthetics',
    traditionDeva: 'नाट्यशास्त्र · रससिद्धान्त',
    blurb: 'The Nāṭyaśāstra codified drama, music, dance and the eight rasas. Every classical Indian art still references it as a first source.',
    works: ['Nāṭyaśāstra', 'Rasa-sūtra'],
    href: '/upavedas/',
  },
  {
    id: 'charaka',
    name: 'Caraka',
    deva: 'चरकः',
    seal: 'च',
    dates: 'c. 1st–2nd c. CE',
    datesDeva: 'इ.स. १–२ शतक',
    era: 'classical',
    tradition: 'Āyurveda · internal medicine',
    traditionDeva: 'आयुर्वेद · कायचिकित्सा',
    blurb: 'The Caraka-Saṃhitā is the foundational text of internal medicine — pathology, pharmacology and the ethics of the physician — still cited in BAMS curricula today.',
    works: ['Caraka-Saṃhitā'],
    href: '/upavedas/',
  },
  {
    id: 'sushruta',
    name: 'Suśruta',
    deva: 'सुश्रुतः',
    seal: 'सु',
    epithet: 'Father of surgery',
    epithetDeva: 'शल्यतंत्रजनकः',
    dates: 'c. 600 BCE – 2nd c. CE',
    datesDeva: 'इ.स.पूर्व ६०० – इ.स. २००',
    era: 'classical',
    tradition: 'Āyurveda · śalya-tantra',
    traditionDeva: 'आयुर्वेद · शल्यतंत्र',
    blurb: 'The Suśruta-Saṃhitā describes 300+ surgical procedures, including rhinoplasty and cataract extraction — the earliest systematic surgical manual in any tradition.',
    works: ['Suśruta-Saṃhitā', '120 surgical instruments'],
    href: '/upavedas/',
  },
  {
    id: 'nagarjuna',
    name: 'Nāgārjuna',
    deva: 'नागार्जुनः',
    seal: 'ना',
    dates: 'c. 150–250 CE',
    datesDeva: 'इ.स. १५०–२५०',
    era: 'classical',
    tradition: 'Madhyamaka Buddhism',
    traditionDeva: 'माध्यमिक बौद्ध दर्शन',
    blurb: 'The Mūlamadhyamaka-Kārikā: the dialectic of śūnyatā (emptiness) that empties every position — including its own — and reorganised Mahāyāna philosophy.',
    works: ['Mūlamadhyamaka-Kārikā', 'Vigrahavyāvartanī'],
    href: '/nastika-darshanas/',
  },
  {
    id: 'kalidasa',
    name: 'Kālidāsa',
    deva: 'कालिदासः',
    seal: 'का',
    dates: 'c. 4th–5th c. CE',
    datesDeva: 'इ.स. ४–५ शतक',
    era: 'classical',
    tradition: 'Sanskrit kāvya · nāṭya',
    traditionDeva: 'संस्कृत काव्य · नाट्य',
    blurb: 'Abhijñāna-Śākuntalam, Raghuvaṃśa, Meghadūta, Kumārasambhava — the height of classical Sanskrit poetry, and the standard by which all later kāvya is judged.',
    works: ['Śākuntalam', 'Meghadūta', 'Raghuvaṃśa'],
  },
  {
    id: 'aryabhata',
    name: 'Āryabhaṭa',
    deva: 'आर्यभटः',
    seal: 'आ',
    dates: '476–550 CE',
    datesDeva: 'इ.स. ४७६–५५०',
    era: 'classical',
    tradition: 'Gaṇita · Jyotiṣa',
    traditionDeva: 'गणित · ज्योतिष',
    blurb: 'The Āryabhaṭīya: place-value notation, the sine table, π to four decimals, the day-length of the sidereal rotation, and the rotation of the Earth on its axis.',
    works: ['Āryabhaṭīya', 'Sūrya-siddhānta line'],
    href: '/vedangas/',
  },
  {
    id: 'varahamihira',
    name: 'Varāhamihira',
    deva: 'वराहमिहिरः',
    seal: 'व',
    dates: '505–587 CE',
    datesDeva: 'इ.स. ५०५–५८७',
    era: 'classical',
    tradition: 'Jyotiṣa · samhitā',
    traditionDeva: 'ज्योतिष · संहिता',
    blurb: 'The Bṛhat-Saṃhitā — an encyclopaedia of jyotiṣa, omens, meteorology, gemmology and architecture — and the Pañca-siddhāntikā that compares five astronomical systems.',
    works: ['Bṛhat-Saṃhitā', 'Pañca-siddhāntikā', 'Bṛhat-Jātaka'],
    href: '/vedangas/',
  },
  {
    id: 'adi-shankara',
    name: 'Ādi Śaṅkarācārya',
    deva: 'आदि शङ्कराचार्यः',
    seal: 'श',
    dates: '788–820 CE',
    datesDeva: 'इ.स. ७८८–८२०',
    era: 'classical',
    tradition: 'Advaita Vedānta',
    traditionDeva: 'अद्वैत वेदान्त',
    blurb: 'Bhāṣyas on the Upaniṣads, Brahma-Sūtra and Gītā (the prasthāna-trayī), and the four maṭhas at the four corners of the subcontinent — Advaita made institutional.',
    works: ['Brahma-Sūtra Bhāṣya', 'Vivekacūḍāmaṇi', 'Four maṭhas'],
    href: '/darshanas/',
  },

  // ────────────────────────────── Medieval Era ────────────────────────────────
  {
    id: 'abhinavagupta',
    name: 'Abhinavagupta',
    deva: 'अभिनवगुप्तः',
    seal: 'अ',
    dates: '950–1016 CE',
    datesDeva: 'इ.स. ९५०–१०१६',
    era: 'medieval',
    tradition: 'Kashmir Śaivism · aesthetics',
    traditionDeva: 'काश्मीर शैव · रससिद्धान्त',
    blurb: 'The Tantrāloka synthesises Kashmir Śaivism; the Abhinava-Bhāratī (commentary on the Nāṭyaśāstra) gives rasa-theory its final philosophical form.',
    works: ['Tantrāloka', 'Abhinava-Bhāratī', 'Locana'],
  },
  {
    id: 'ramanuja',
    name: 'Rāmānujācārya',
    deva: 'रामानुजाचार्यः',
    seal: 'रा',
    dates: '1017–1137 CE',
    datesDeva: 'इ.स. १०१७–११३७',
    era: 'medieval',
    tradition: 'Viśiṣṭādvaita Vedānta',
    traditionDeva: 'विशिष्टाद्वैत वेदान्त',
    blurb: 'The Śrī-Bhāṣya argues that the soul is real and distinct yet inseparable from God. Reformed Śrīraṅgam temple worship and opened it across caste.',
    works: ['Śrī-Bhāṣya', 'Vedārtha-Saṅgraha', 'Gītā-Bhāṣya'],
    href: '/darshanas/',
  },
  {
    id: 'madhva',
    name: 'Madhvācārya',
    deva: 'मध्वाचार्यः',
    seal: 'म',
    epithet: 'Ānandatīrtha',
    epithetDeva: 'आनन्दतीर्थः',
    dates: '1238–1317 CE',
    datesDeva: 'इ.स. १२३८–१३१७',
    era: 'medieval',
    tradition: 'Dvaita Vedānta',
    traditionDeva: 'द्वैत वेदान्त',
    blurb: 'Pure dualism: God, soul and world are each fully real and irreducibly distinct. Thirty-seven works including bhāṣyas on every text of the prasthāna-trayī.',
    works: ['Brahma-Sūtra Bhāṣya', 'Anuvyākhyāna'],
    href: '/darshanas/',
  },
  {
    id: 'bhaskara-ii',
    name: 'Bhāskara II',
    deva: 'भास्कराचार्यः',
    seal: 'भा',
    dates: '1114–1185 CE',
    datesDeva: 'इ.स. १११४–११८५',
    era: 'medieval',
    tradition: 'Gaṇita · Jyotiṣa',
    traditionDeva: 'गणित · ज्योतिष',
    blurb: 'The Siddhānta-Śiromaṇi treats algebra, calculus precursors and planetary theory; the Līlāvatī teaches arithmetic in verse to a daughter.',
    works: ['Līlāvatī', 'Bījagaṇita', 'Siddhānta-Śiromaṇi'],
  },
  {
    id: 'jnaneshwar',
    name: 'Jñāneśvar',
    deva: 'ज्ञानेश्वरः',
    seal: 'ज्ञा',
    epithet: 'Māuli',
    epithetDeva: 'माउली',
    dates: '1275–1296 CE',
    datesDeva: 'इ.स. १२७५–१२९६',
    era: 'medieval',
    tradition: 'Marathi bhakti · Nāth · Vārkarī',
    traditionDeva: 'मराठी भक्ती · नाथ · वारकरी',
    blurb: 'At nineteen he wrote the Bhāvārtha-Dīpikā — the Gītā translated and unfolded in Marathi ovis — and gave the Vārkarī tradition its first scripture.',
    works: ['Jñāneśvarī', 'Amṛtānubhava', 'Haripāṭh'],
  },
  {
    id: 'namdev',
    name: 'Nāmdev',
    deva: 'नामदेवः',
    seal: 'ना',
    dates: '1270–1350 CE',
    datesDeva: 'इ.स. १२७०–१३५०',
    era: 'medieval',
    tradition: 'Marathi bhakti · Vārkarī',
    traditionDeva: 'मराठी भक्ती · वारकरी',
    blurb: 'A tailor of Pandharpur whose abhangas became canon in two languages — Marathi and Gurmukhi. Sixty-one of his hymns sit in the Guru Granth Sāhib.',
    works: ['Marathi abhangas', 'Hindi pads in Granth Sāhib'],
  },
  {
    id: 'vidyaranya',
    name: 'Vidyāraṇya',
    deva: 'विद्यारण्यः',
    seal: 'वि',
    dates: '1268–1386 CE',
    datesDeva: 'इ.स. १२६८–१३८६',
    era: 'medieval',
    tradition: 'Advaita · institution-building',
    traditionDeva: 'अद्वैत · संस्था-स्थापना',
    blurb: 'Pañcadaśī and Jīvanmukti-Viveka systematise Advaita for the householder. The intellectual force behind the founding of the Vijayanagara empire.',
    works: ['Pañcadaśī', 'Jīvanmukti-Viveka', 'Sarva-darśana-Saṅgraha'],
  },
  {
    id: 'madhava-sangamagrama',
    name: 'Mādhava of Saṅgamagrāma',
    deva: 'माधवः',
    seal: 'मा',
    dates: '1340–1425 CE',
    datesDeva: 'इ.स. १३४०–१४२५',
    era: 'medieval',
    tradition: 'Kerala school · gaṇita',
    traditionDeva: 'केरळ गणित संप्रदाय',
    blurb: 'Founder of the Kerala school. Infinite-series expansions for π, sine and cosine — three centuries before Leibniz, Newton and Gregory.',
    works: ['Mādhava–Leibniz series', 'Sine & cosine series'],
  },
  {
    id: 'kabir',
    name: 'Kabīr',
    deva: 'कबीरः',
    seal: 'क',
    dates: '1440–1518 CE',
    datesDeva: 'इ.स. १४४०–१५१८',
    era: 'medieval',
    tradition: 'Nirguṇa bhakti · sant',
    traditionDeva: 'निर्गुण भक्ती · संत',
    blurb: 'A weaver of Banāras whose dohās scold Hindus and Muslims with equal sharpness. Read across three canons — Bījak, Granth Sāhib and Pañc-vāṇī.',
    works: ['Bījak', 'Pads in Granth Sāhib'],
  },
  {
    id: 'guru-nanak',
    name: 'Guru Nānak',
    deva: 'गुरु नानकः',
    seal: 'ना',
    dates: '1469–1539 CE',
    datesDeva: 'इ.स. १४६९–१५३९',
    era: 'medieval',
    tradition: 'Sikh dharma',
    traditionDeva: 'सिख धर्म',
    blurb: 'First of the ten Sikh gurus. The Japjī Sāhib opens the Guru Granth Sāhib; the message of one nirguṇa Reality crossed every regional boundary.',
    works: ['Japjī Sāhib', 'Āsā dī Vār'],
  },
  {
    id: 'sūrdas',
    name: 'Sūrdās',
    deva: 'सूरदासः',
    seal: 'सू',
    dates: '1478–1583 CE',
    datesDeva: 'इ.स. १४७८–१५८३',
    era: 'medieval',
    tradition: 'Braj bhakti · Puṣṭimārga',
    traditionDeva: 'ब्रज भक्ती · पुष्टिमार्ग',
    blurb: 'The blind poet whose Sūrsāgar fills four thousand pads with the childhood of Kṛṣṇa — the lyric voice of Braj-bhāṣā devotion.',
    works: ['Sūrsāgar', 'Sāhitya-Laharī'],
  },
  {
    id: 'vallabha',
    name: 'Vallabhācārya',
    deva: 'वल्लभाचार्यः',
    seal: 'व',
    dates: '1479–1531 CE',
    datesDeva: 'इ.स. १४७९–१५३१',
    era: 'medieval',
    tradition: 'Śuddhādvaita · Puṣṭimārga',
    traditionDeva: 'शुद्धाद्वैत · पुष्टिमार्ग',
    blurb: 'Founded the Puṣṭimārga path of divine grace. The Aṇu-Bhāṣya on the Brahma-Sūtra and the Subodhinī on the Bhāgavata anchor Śuddhādvaita.',
    works: ['Aṇu-Bhāṣya', 'Subodhinī', 'Ṣoḍaśa-Granthāḥ'],
  },
  {
    id: 'caitanya',
    name: 'Caitanya Mahāprabhu',
    deva: 'चैतन्य महाप्रभुः',
    seal: 'चै',
    dates: '1486–1534 CE',
    datesDeva: 'इ.स. १४८६–१५३४',
    era: 'medieval',
    tradition: 'Gauḍīya Vaiṣṇavism · bhakti',
    traditionDeva: 'गौडीय वैष्णव · भक्ती',
    blurb: 'Founder of Gauḍīya Vaiṣṇavism. Saṅkīrtana — public chanting of the Name — turned bhakti into a mass devotional practice across Bengal and Odisha.',
    works: ['Śikṣāṣṭakam', 'Saṅkīrtana practice'],
  },
  {
    id: 'mira',
    name: 'Mīrā Bāī',
    deva: 'मीराबाई',
    seal: 'मी',
    dates: '1498–1547 CE',
    datesDeva: 'इ.स. १४९८–१५४७',
    era: 'medieval',
    tradition: 'Rajasthani bhakti · Kṛṣṇa',
    traditionDeva: 'राजस्थानी भक्ती · कृष्ण',
    blurb: 'A Rajput princess who took Kṛṣṇa as her only husband. Her padas — in Rajasthani, Braj and Gujarati — refuse every other allegiance.',
    works: ['Padāvalī', 'Bhajans'],
  },
  {
    id: 'eknath',
    name: 'Eknāth',
    deva: 'एकनाथः',
    seal: 'ए',
    dates: '1533–1599 CE',
    datesDeva: 'इ.स. १५३३–१५९९',
    era: 'medieval',
    tradition: 'Marathi bhakti · Vārkarī',
    traditionDeva: 'मराठी भक्ती · वारकरी',
    blurb: 'The Eknāthī Bhāgavata, the Bhāvārtha-Rāmāyaṇa and bhārūds in vernacular Marathi. The editor who restored Jñāneśvar’s text from corrupted copies.',
    works: ['Eknāthī Bhāgavata', 'Bhāvārtha-Rāmāyaṇa', 'Bhārūds'],
  },
  {
    id: 'tulsidas',
    name: 'Tulsīdās',
    deva: 'तुलसीदासः',
    seal: 'तु',
    dates: '1532–1623 CE',
    datesDeva: 'इ.स. १५३२–१६२३',
    era: 'medieval',
    tradition: 'Awadhi bhakti · Rāma',
    traditionDeva: 'अवधी भक्ती · राम',
    blurb: 'The Rāmcaritmānas told the Rāma story in Awadhi for everyone north India had ever read off a temple wall. The most recited text in Hindi-belt homes.',
    works: ['Rāmcaritmānas', 'Hanumān Cālīsā', 'Vinaya-Patrikā'],
  },
  {
    id: 'tukaram',
    name: 'Tukārām',
    deva: 'तुकारामः',
    seal: 'तु',
    dates: '1608–1650 CE',
    datesDeva: 'इ.स. १६०८–१६५०',
    era: 'medieval',
    tradition: 'Marathi bhakti · Vārkarī',
    traditionDeva: 'मराठी भक्ती · वारकरी',
    blurb: 'Five thousand abhangas — the unsparing inner voice of Marathi bhakti. Sang of doubt and the absent God as honestly as of presence.',
    works: ['Tukārām-gāthā', 'Abhanga corpus'],
  },
  {
    id: 'ramdas',
    name: 'Samartha Rāmdās',
    deva: 'समर्थ रामदासः',
    seal: 'रा',
    dates: '1608–1681 CE',
    datesDeva: 'इ.स. १६०८–१६८१',
    era: 'medieval',
    tradition: 'Activist Vedānta · Rāma bhakti',
    traditionDeva: 'सक्रिय वेदान्त · राम भक्ती',
    blurb: 'Dāsbodh and Manāche Ślok — the gurū of activist Vedānta in the age of Śivājī. Renunciation joined to public reconstruction.',
    works: ['Dāsbodh', 'Manāche Ślok', 'Karuṇāṣṭakas'],
  },

  // ─────────────────────────────── Modern Era ─────────────────────────────────
  {
    id: 'rammohan',
    name: 'Rām Mohan Roy',
    deva: 'राम मोहन रॉय',
    seal: 'रा',
    dates: '1772–1833 CE',
    datesDeva: 'इ.स. १७७२–१८३३',
    era: 'modern',
    tradition: 'Reform · Brāhmo Samāj',
    traditionDeva: 'सुधारक · ब्राह्मो समाज',
    blurb: 'Founder of the Brāhmo Samāj. Translated the Upaniṣads into Bengali and English, and lobbied the colonial state into banning satī.',
    works: ['Translations of Upaniṣads', 'Tuhfat-ul-Muwahhidin'],
  },
  {
    id: 'dayananda',
    name: 'Dayānanda Sarasvatī',
    deva: 'दयानन्द सरस्वती',
    seal: 'द',
    dates: '1824–1883 CE',
    datesDeva: 'इ.स. १८२४–१८८३',
    era: 'modern',
    tradition: 'Reform · Ārya Samāj',
    traditionDeva: 'सुधारक · आर्य समाज',
    blurb: 'Founder of the Ārya Samāj. Satyārtha Prakāś called for a return to the Vedas and against idol-worship, caste-by-birth and child marriage.',
    works: ['Satyārtha Prakāś', 'Ṛgveda Bhāṣya'],
  },
  {
    id: 'tilak',
    name: 'Bāḷ Gaṅgādhar Tilak',
    deva: 'बाळ गंगाधर टिळक',
    seal: 'ती',
    epithet: 'Lokmānya',
    epithetDeva: 'लोकमान्य',
    dates: '1856–1920 CE',
    datesDeva: 'इ.स. १८५६–१९२०',
    era: 'modern',
    tradition: 'Karma-yoga · nationalism',
    traditionDeva: 'कर्मयोग · राष्ट्रवाद',
    blurb: 'Wrote the Gītā-Rahasya in a Mandalay prison. Read the Gītā as a manual of karma-yoga — a charter for action, not withdrawal.',
    works: ['Gītā-Rahasya', 'Orion', 'Arctic Home in the Vedas'],
  },
  {
    id: 'ramakrishna',
    name: 'Rāmakṛṣṇa Paramahaṃsa',
    deva: 'रामकृष्ण परमहंसः',
    seal: 'रा',
    dates: '1836–1886 CE',
    datesDeva: 'इ.स. १८३६–१८८६',
    era: 'modern',
    tradition: 'Bhakti · jñāna · universal religion',
    traditionDeva: 'भक्ती · ज्ञान · सर्व-धर्म-समभाव',
    blurb: 'The Bengali mystic of Dakṣiṇeśvar who practiced — to verify — Vaiṣṇava, Śākta, Advaita, Christian and Islamic paths in turn, and reported the same goal.',
    works: ['Gospel of Śrī Rāmakṛṣṇa', 'Kathāmṛta'],
  },
  {
    id: 'vivekananda',
    name: 'Swāmī Vivekānanda',
    deva: 'स्वामी विवेकानन्द',
    seal: 'वि',
    dates: '1863–1902 CE',
    datesDeva: 'इ.स. १८६३–१९०२',
    era: 'modern',
    tradition: 'Practical Vedānta · seva',
    traditionDeva: 'प्रायोगिक वेदान्त · सेवा',
    blurb: 'The 1893 Chicago address. Founded the Rāmakṛṣṇa Mission. Recast Vedānta as a rational, this-worldly creed and made service of the human the worship of God.',
    works: ['Rāja-Yoga', 'Karma-Yoga', 'Chicago Addresses'],
  },
  {
    id: 'aurobindo',
    name: 'Aurobindo Ghose',
    deva: 'अरविन्द घोषः',
    seal: 'अ',
    epithet: 'Mahāyogī',
    epithetDeva: 'महायोगी',
    dates: '1872–1950 CE',
    datesDeva: 'इ.स. १८७२–१९५०',
    era: 'modern',
    tradition: 'Integral yoga · Pondicherry',
    traditionDeva: 'पूर्ण योग · पुदुच्चेरी',
    blurb: 'The Life Divine, the Essays on the Gītā and Savitrī — an integral yoga that reads the spiritual life as evolutionary and the body as the field of transformation.',
    works: ['The Life Divine', 'Essays on the Gītā', 'Savitrī'],
  },
  {
    id: 'ramana',
    name: 'Ramaṇa Maharṣi',
    deva: 'रमण महर्षिः',
    seal: 'र',
    dates: '1879–1950 CE',
    datesDeva: 'इ.स. १८७९–१९५०',
    era: 'modern',
    tradition: 'Advaita · ātma-vicāra',
    traditionDeva: 'अद्वैत · आत्म-विचार',
    blurb: 'On the hill of Aruṇācala, the silent revival of the one question — “Who am I?” The simplest possible method of self-inquiry, made universal.',
    works: ['Upadeśa Sāram', 'Forty Verses on Reality'],
  },
  {
    id: 'sivananda',
    name: 'Svāmī Śivānanda',
    deva: 'स्वामी शिवानन्दः',
    seal: 'शि',
    dates: '1887–1963 CE',
    datesDeva: 'इ.स. १८८७–१९६३',
    era: 'modern',
    tradition: 'Yoga · Vedānta · seva',
    traditionDeva: 'योग · वेदान्त · सेवा',
    blurb: 'Founded the Divine Life Society at Ṛṣikeśa. Three hundred books that taught yoga, Vedānta and a householder discipline accessible to the modern reader.',
    works: ['Divine Life Society', '300+ books'],
  },
  {
    id: 'radhakrishnan',
    name: 'Sarvepalli Rādhākrishnan',
    deva: 'सर्वपल्ली राधाकृष्णन्',
    seal: 'रा',
    dates: '1888–1975 CE',
    datesDeva: 'इ.स. १८८८–१९७५',
    era: 'modern',
    tradition: 'Philosophy · statecraft',
    traditionDeva: 'तत्त्वज्ञान · राजनीति',
    blurb: 'Philosopher-statesman. Indian Philosophy and translations of the Upaniṣads, Gītā and Brahma-Sūtra carried Vedānta into the academies of the world.',
    works: ['Indian Philosophy', 'Translations of prasthāna-trayī'],
  },
  {
    id: 'gandhi',
    name: 'Mahātmā Gāndhī',
    deva: 'महात्मा गांधी',
    seal: 'गा',
    dates: '1869–1948 CE',
    datesDeva: 'इ.स. १८६९–१९४८',
    era: 'modern',
    tradition: 'Satyāgraha · Gītā ethics',
    traditionDeva: 'सत्याग्रह · गीता नैतिकता',
    blurb: 'Hind Svarāj and the Anāsakti-Yoga commentary on the Gītā. Satyāgraha turned ahiṃsā into a political method that ended an empire.',
    works: ['Hind Svarāj', 'Anāsakti-Yoga', 'My Experiments with Truth'],
  },
  {
    id: 'ambedkar',
    name: 'B. R. Ambedkar',
    deva: 'बाबासाहेब आंबेडकर',
    seal: 'आं',
    epithet: 'Bābāsāheb',
    epithetDeva: 'बाबासाहेब',
    dates: '1891–1956 CE',
    datesDeva: 'इ.स. १८९१–१९५६',
    era: 'modern',
    tradition: 'Jurisprudence · Navayāna Buddhism',
    traditionDeva: 'विधिशास्त्र · नवयान बौद्ध',
    blurb: 'Chief architect of the Indian Constitution. The Buddha and His Dhamma reframes Buddhism as a modern social ethic for the republic.',
    works: ['Indian Constitution', 'The Buddha and His Dhamma', 'Annihilation of Caste'],
  },
  {
    id: 'yogananda',
    name: 'Paramahaṃsa Yogānanda',
    deva: 'परमहंस योगानन्दः',
    seal: 'यो',
    dates: '1893–1952 CE',
    datesDeva: 'इ.स. १८९३–१९५२',
    era: 'modern',
    tradition: 'Kriyā-yoga · global outreach',
    traditionDeva: 'क्रिया-योग · वैश्विक प्रसार',
    blurb: 'Autobiography of a Yogi opened kriyā-yoga to the West with a reach no earlier teacher matched. Founded the Self-Realization Fellowship.',
    works: ['Autobiography of a Yogi', 'God Talks with Arjuna'],
  },
];

export const CONTRIB_ERAS = ['vedic', 'classical', 'medieval', 'modern'] as const;
