'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'mr';

type LanguageContextType = {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.texts': 'Texts',
    'nav.tree': 'Timeline',
    'nav.library': 'Collection',
    'nav.contrib': 'Contributors',
    'nav.concepts': 'Concepts',
    'nav.lifestyle': 'Lifestyle',
    'nav.essays': 'Essays',
    'nav.sanskrit': 'Sanskrit',
    'nav.journeys': 'Journeys',
    'home.preface_q': 'Finished the introduction?',
    'home.preface_btn': 'Yes — take me to the reading paths',
    'home.preface_bar': 'You have read the introduction.',
    'home.preface_again': 'Read it again',
    'home.choose_path': 'Choose your path',
    'rg.title': 'Route at a glance',
    'rg.facts': '{n} steps · about {time} · {a}–{b} min each',
    'rg.eras': 'Steps by era',
    'rg.route': 'The route, step by step',
    'rg.starts': 'Starts with',
    'rg.ends': 'Ends with',
    'rg.begin': 'Begin the path',
    'rg.continue': 'Continue from step {n}',
    'rg.hint': 'Tap a dot to see the step.',
    'upd.msg': 'A new version is available.',
    'upd.refresh': 'Refresh',
    'upd.later': 'Later',
    'home.gate_eyebrow': 'On your own?',
    'home.gate_title': 'Prefer to browse freely?',
    'home.gate_text': 'The full library — all 28 sections, concepts, contributors and living knowledge — is one tap away. A reading path keeps you on course; the library lets you wander.',
    'home.gate_btn': 'Open the full library',
    'home.bar_text': 'You are browsing the full library.',
    'home.bar_btn': 'Back to guided paths',
    'gd.exit': 'Exit path',
    'gd.step_of': 'Step {n} of {total}',
    'gd.min': 'about {n} min',
    'gd.why': 'Why this step, why now',
    'gd.next': 'Next step',
    'gd.prev': 'Previous',
    'gd.done': 'Path complete',
    'gd.done_title': 'You have finished {title}',
    'gd.paths': 'Choose another path',
    'gd.library': 'Open the full library',
    'gd.deeper': 'Go deeper (optional)',
    'gd.hide_deeper': 'Hide the extra material',
    'gd.trip': 'Side trip — this page is not part of your path',
    'gd.return': 'Return to your path',
    'gd.locked': 'Locked until you reach it',
    'gd.locked_toast': 'That step is still ahead on your path. Finish this one first.',
    'gd.blocked': 'That page is not on your path. Finish this step, or exit the path to explore freely.',
    'nav.map': 'Map',
    'map.crumb': 'Jñāna Map',
    'map.eyebrow': 'Interactive timeline',
    'map.title': 'Jñāna Map',
    'map.teaser': 'All 28 sections at a glance, arranged by era — then open any one for its own timeline, people and knowledge cards.',
    'map.teaser_cta': 'Open the map →',
    'map.lede.schools': 'The six āstika darśanas arrive as three complementary pairs; the nāstika schools stand outside the Veda\'s authority. Tap a school to see who it debated and who it shaped.',
    'map.schools.astika': 'Āstika — accept the Veda\'s authority',
    'map.schools.nastika': 'Nāstika — outside it',
    'map.schools.root': 'Veda (Śruti)',
    'map.schools.k_pair': 'Paired',
    'map.schools.k_debate': 'Debate',
    'map.schools.k_influence': 'Influence',
    'map.schools.aria': 'Diagram of the nine philosophical schools and how they relate',
    'map.schools.legend': 'Line types',
    'map.schools.hint': 'Tap a school to highlight its relationships. Faint lines show every debate and influence; the selected school\'s lines turn solid.',
    'map.schools.relations': 'Relationships',
    'vx.intro': 'Four collections on one line of time. Each Veda grew in four layers — hymns, ritual commentary, forest texts and inquiry — and was carried by named teachers. Tap a bar, a seer or a card.',
    'vx.intro_eyebrow': 'Section explorer',
    'vx.layers': 'Layers of the text',
    'vx.seers': 'Seers and teachers',
    'vx.ideas': 'Ideas to explore',
    'vx.legend_layers': 'Text layers — darker is older',
    'vx.approx': 'Dates are approximate',
    'vx.seer': 'Seer',
    'vx.close': 'Close',
    'vx.open_related': 'Open related page',
    'vx.pending': 'Texts for this layer are being added.',
    'vx.timeline_aria': 'Timeline of the Vedic text layers and seers',
    'vx.choose': 'Choose a Veda',
    'vx.deep': 'Read this Veda in depth',
    'vx.deep_eyebrow': 'In depth',
    'vx.deep_title': 'Śākhās, sūktas and teachings',
    'up.intro': 'Ten principal Upaniṣads, grouped by the Veda each belongs to and placed on one line of time. The oldest are long dialogues; the later ones are short and concentrated. Tap a bar, a seer or a card.',
    'up.legend': 'Each bar is one Upaniṣad — darker is older',
    'up.count': '{n} Upaniṣads',
    'up.count_one': '1 Upaniṣad',
    'up.texts': 'The Upaniṣads',
    'up.open': 'Open full page',
    'up.timeline_aria': 'Timeline of the principal Upaniṣads by Veda',
    'ge.intro_timeline': 'Everything in this section on one line of approximate time. Tap a bar, a person or a tile to read about it.',
    'ge.intro_cards': 'A quick way into this section. Tap a tile for a short summary, then open its full page.',
    'ge.legend': 'Each bar is one text, school or person — darker is earlier',
    'ge.people': 'People',
    'ge.items': 'In this section',
    'ge.topics': 'Topics to explore',
    'ge.count': '{n} entries',
    'ge.timeline_aria': 'Timeline of this section',
    'ov.eyebrow': 'Overview',
    'ov.count': '{n} sections',
    'ov.lede': 'The whole collection at a glance, arranged by the era each section comes from. Open any section to see its own timeline, people and knowledge cards.',
    'ov.eras': 'Jump to an era',
    'ov.n_sections': '{n} sections',
    'sm.eyebrow': 'Relationships',
    'sm.title': 'How the schools relate',
    'map.open': 'Open full page',
    'map.close': 'Close',
    'search.placeholder': 'Search verses, sūktas, schools…',
    // Hero
    'hero.eyebrow': 'Daily wisdom · 24 Vaiśākha · Saumya saṃvatsara',
    'hero.title': 'A digital collection of the texts, sciences and ways of living rooted in the Indic knowledge systems.',
    'hero.show_trans': 'Show translation',
    'hero.hide_trans': 'Hide translation',
    'hero.read_essay': 'Read essay →',
    'hero.begin_here': 'Begin here',
    'hero.continue_reading': 'Continue reading',
    'hero.explore_paths': 'Explore more paths',
    'hero.choose_path': 'See all paths',
    // Verse (mahāvākya / subhāṣita)
    'verse.mahavakya_label': 'Mahāvākya · the great utterances',
    'verse.subhashit_label': 'Subhāṣita · Bhartṛhari',
    'verse.today_mahavakya': "Today's Mahāvākya",
    'verse.today_subhashit': "Today's Subhāṣita",
    'verse.show_explanation': 'Show explanation',
    'verse.next': 'Another verse',
    'verse.meaning': 'Meaning',
    'verse.explanation': 'Explanation',
    'verse.close': 'Close',
    'verse.share': 'Share',
    'verse.copy': 'Copy text',
    'verse.copied': 'Copied ✓',
    'verse.share_footer': 'To know more about Bhāratīya Jñāna Bhaṇḍāra — India\'s open digital archive of Indic knowledge systems —',
    // Daily notification (Android app)
    'notify.title': 'Daily verse notification',
    'notify.desc': "Get today's verse each morning — works fully offline.",
    'notify.time': 'Time',
    'notify.collection': 'Verse',
    'notify.subhashita': 'Subhāṣita',
    'notify.mahavakya': 'Mahāvākya',
    'notify.both': 'Both, alternating',
    'notify.denied': 'Notification permission was denied — enable it in system settings.',
    // Site share
    'site.share_btn': 'Share this website',
    // Tree
    'tree.eyebrow': 'Map of the corpus',
    'tree.title': 'The three streams',
    'tree.hover_prompt': 'Hover any leaf · click to open',
    'tree.branch': 'Branch',
    'tree.streams': 'streams',
    'tree.open_page': 'Open page →',
    // Timeline
    'timeline.eyebrow': 'Chronology of the corpus',
    'timeline.title': 'The historical timeline',
    'timeline.prompt': 'Click any stream to expand details',
    // Grid
    'grid.eyebrow': 'The full library',
    'grid.title': 'Browse the full library',
    'grid.lede': 'The complete reference catalogue — all 28 streams, grouped era by era. For a guided read, start with the paths above.',
    'grid.showing': 'Showing {count} of {total} streams',
    'grid.tag_era': 'Era',
    'grid.tag_canon': 'Canon',
    'grid.tag_topic': 'Topic',
    // Contributors
    'contrib.eyebrow': 'The makers',
    'contrib.title': 'Ṛṣis, ācāryas, scientists & saints — across the timeline',
    'contrib.meta': '{count} contributors · four eras',
    'contrib.prompt': 'Click any card for the full account of their contributions',
    'contrib.detail.tag': 'Detailed account',
    'contrib.detail.contributions': 'Principal contributions',
    'contrib.detail.legacy': 'Legacy & influence',
    'contrib.detail.works': 'Key works',
    'contrib.detail.explore': 'Explore in the collection',
    'contrib.detail.close': 'Close',
    // Core concepts
    'concepts.eyebrow': 'The framework',
    'concepts.title': 'Core concepts of the Indian knowledge systems',
    'concepts.meta': '{count} concepts · seven domains',
    'concepts.prompt': 'Click any card for the full meaning and significance',
    'concepts.detail.aspects': 'Key aspects',
    'concepts.detail.significance': 'Why it matters',
    'concepts.detail.related': 'Related terms',
    'concepts.detail.appears': 'Where it appears',
    'concepts.detail.first': 'First explained in',
    'concepts.detail.referred': 'Further developed in',
    'concepts.detail.explore': 'Explore in the collection',
    'concepts.detail.close': 'Close',
    // Dinacharya
    'dina.eyebrow': 'Lifestyle',
    'dina.title': 'Dinacaryā — the structure of the day',
    'dina.meta': 'Six segments · classical Āyurveda',
    // Essays
    'essays.eyebrow': 'Editorial',
    'essays.title': 'Essays from the editors',
    'essays.meta': 'Updated weekly',
    // Footer
    'footer.colophon': 'An open digital collection of the Indic knowledge systems. Texts in transliteration and original. Translations and commentary by working scholars. Free to read; built to last.',
    'footer.compiled_by': 'Compiled by Vivek Sovani',
    'footer.sec_texts': 'Texts',
    'footer.sec_tools': 'Tools',
    'footer.sec_about': 'About',
    'footer.samvat': '© Vikram Saṃvat 2083',
    'footer.setin': 'Set in Cormorant, Lora & Tiro Devanagari Sanskrit',
    'footer.license': 'An open archive · CC BY-SA 4.0',
    // Details
    'detail.back': '← Back to the collection',
    'detail.continue': 'Continue in the collection',
    'detail.the_opening': 'The opening',
    'detail.at_a_glance': 'At a glance',
    'detail.practice_focused': 'Practice-focused stream. See the full reading-list in the references panel.',
    'detail.recension': 'Recension',
    'detail.authors': 'Authors',
    'detail.range': 'Range',
    'detail.scope': 'Scope',
    'detail.officiant': 'Officiant',
    'detail.period': 'Period',
    'detail.strata': 'The four strata of every Veda',
    'detail.library': 'Collection',
    // Living Knowledge
    'nav.lk': 'Living Knowledge',
    'lk.eyebrow': 'Living knowledge',
    'lk.title': 'Gifts of Indian knowledge systems to the world',
    'lk.title_short': 'Living Knowledge',
    'lk.meta': '{count} contributions · nine domains',
    'lk.note_label': 'A note on honesty:',
    'lk.prompt': 'Click any domain tile to reveal its contributions, then click a contribution to read more.',
    'lk.count': '{n} contributions',
    'lk.debated': 'Debated claim',
    'lk.expand': 'See contributions',
    'lk.collapse': 'Collapse',
    'lk.read_more': 'Read more →',
    'lk.what': 'What it is',
    'lk.when': 'When it emerged',
    'lk.how': 'How it applies today',
    'lk.back_label': '← Back to Living Knowledge',
    'lk.back_to_domains': 'Back to all domains',
    'lk.phase2': 'Detailed account coming soon — check back in Phase II.',
    // Journeys
    'jrn.eyebrow': 'Guided reading',
    'jrn.title': 'Choose Your Reading Path',
    'jrn.lede': "You've just seen how the tree grows. Now pick how you want to walk through it.",
    'jrn.themed_heading': 'Or a themed path',
    'jrn.meta': '{count} themed journeys',
    'jrn.steps_min': '{steps} steps · ~{minutes} min',
    'jrn.begin': 'Begin →',
    'jrn.continue': 'Continue · step {n} →',
    'jrn.complete_badge': 'Walked ✓',
    'jrn.list.eyebrow': 'Guided reading',
    'jrn.list.title': 'All Journeys',
    'jrn.crumb': 'Journeys',
    'jrn.step_of': 'Step {n} of {total}',
    'jrn.min_short': '{n} min',
    'jrn.reset': 'Reset progress',
    'jrn.reset_confirm': 'Reset your progress on "{title}"? This can\'t be undone.',
    'tabnav.prev': 'Previous',
    'tabnav.next': 'Next',
    'jrn.visited': 'Visited',
    'jrn.begin_step': 'Begin this journey →',
    'jrn.ribbon.next': 'Next',
    'jrn.ribbon.trail': 'Trail map',
    'jrn.ribbon.dismiss': 'Dismiss',
    'jrn.ribbon.done_title': "You've walked {title}.",
    'jrn.ribbon.done_more': 'Continue with:',
    // Reading spine (the complete path)
    'spine.eyebrow': 'Read in order',
    'spine.title': 'The Complete Path',
    'spine.tagline': 'Every stream in the archive, in the order it grew — Vedic to modern. Start at the source and let each page lead to the next.',
    'spine.begin': 'Begin at the beginning',
    'spine.continue': 'Continue · № {n}',
    'spine.walked': '{n} of {total} read',
    'spine.see_all': 'See the full path →',
  },
  mr: {
    // Nav
    'nav.texts': 'ग्रंथ',
    'nav.tree': 'कालरेषा',
    'nav.library': 'संग्रहण',
    'nav.contrib': 'योगदाते',
    'nav.concepts': 'संकल्पना',
    'nav.lifestyle': 'दिनचर्या',
    'nav.essays': 'निबंध',
    'nav.sanskrit': 'संस्कृत',
    'nav.journeys': 'प्रवास',
    'home.preface_q': 'प्रस्तावना वाचून झाली?',
    'home.preface_btn': 'हो — मला वाचन-मार्गांकडे न्या',
    'home.preface_bar': 'तुम्ही प्रस्तावना वाचली आहे.',
    'home.preface_again': 'पुन्हा वाचा',
    'home.choose_path': 'तुमचा मार्ग निवडा',
    'rg.title': 'मार्गाचा आढावा',
    'rg.facts': '{n} पायऱ्या · सुमारे {time} · प्रत्येकी {a}–{b} मिनिटे',
    'rg.eras': 'कालखंडानुसार पायऱ्या',
    'rg.route': 'मार्ग, पायरीपायरीने',
    'rg.starts': 'सुरुवात',
    'rg.ends': 'शेवट',
    'rg.begin': 'मार्ग सुरू करा',
    'rg.continue': 'पायरी {n} पासून पुढे',
    'rg.hint': 'पायरी पाहण्यासाठी बिंदूवर टॅप करा.',
    'upd.msg': 'नवीन आवृत्ती उपलब्ध आहे.',
    'upd.refresh': 'रीफ्रेश करा',
    'upd.later': 'नंतर',
    'home.gate_eyebrow': 'स्वतंत्रपणे?',
    'home.gate_title': 'मुक्तपणे फिरायचे आहे?',
    'home.gate_text': 'संपूर्ण संग्रहण — सर्व २८ विभाग, संकल्पना, योगदाते आणि जिवंत ज्ञान — एका टॅपवर. वाचन-मार्ग तुम्हाला दिशा देतो; संग्रहण तुम्हाला मोकळेपणाने फिरू देते.',
    'home.gate_btn': 'संपूर्ण संग्रहण उघडा',
    'home.bar_text': 'तुम्ही संपूर्ण संग्रहण पाहत आहात.',
    'home.bar_btn': 'मार्गदर्शित मार्गांकडे परत',
    'gd.exit': 'मार्ग सोडा',
    'gd.step_of': 'पायरी {n} / {total}',
    'gd.min': 'सुमारे {n} मिनिटे',
    'gd.why': 'ही पायरी का, आत्ताच का',
    'gd.next': 'पुढील पायरी',
    'gd.prev': 'मागील',
    'gd.done': 'मार्ग पूर्ण',
    'gd.done_title': '{title} पूर्ण झाला',
    'gd.paths': 'दुसरा मार्ग निवडा',
    'gd.library': 'संपूर्ण संग्रहण उघडा',
    'gd.deeper': 'अधिक खोलात (ऐच्छिक)',
    'gd.hide_deeper': 'अतिरिक्त मजकूर लपवा',
    'gd.trip': 'बाजूचा फेरफटका — हे पान तुमच्या मार्गावर नाही',
    'gd.return': 'मार्गावर परत जा',
    'gd.locked': 'तिथे पोहोचेपर्यंत बंद',
    'gd.locked_toast': 'ती पायरी तुमच्या मार्गावर पुढे आहे. आधी ही पूर्ण करा.',
    'gd.blocked': 'ते पान तुमच्या मार्गावर नाही. ही पायरी पूर्ण करा, किंवा मुक्तपणे फिरण्यासाठी मार्ग सोडा.',
    'nav.map': 'नकाशा',
    'map.crumb': 'ज्ञान-नकाशा',
    'map.eyebrow': 'संवादी कालरेषा',
    'map.title': 'ज्ञान-नकाशा',
    'map.teaser': 'सर्व २८ विभाग एका दृष्टिक्षेपात, कालखंडानुसार — मग कोणताही उघडून त्याची कालरेषा, व्यक्ती आणि ज्ञान-कार्डे पहा.',
    'map.teaser_cta': 'नकाशा उघडा →',
    'map.lede.schools': 'सहा आस्तिक दर्शने तीन पूरक जोड्यांत येतात; नास्तिक दर्शने वेदप्रामाण्याबाहेर उभी आहेत. दर्शनावर टॅप करा — त्याने कोणाशी वाद केला व कोणाला घडवले ते पहा.',
    'map.schools.astika': 'आस्तिक — वेदप्रामाण्य मानणारी',
    'map.schools.nastika': 'नास्तिक — वेदप्रामाण्याबाहेरील',
    'map.schools.root': 'वेद (श्रुती)',
    'map.schools.k_pair': 'जोडी',
    'map.schools.k_debate': 'वाद',
    'map.schools.k_influence': 'प्रभाव',
    'map.schools.aria': 'नऊ तत्त्वज्ञान-दर्शने व त्यांचे परस्परसंबंध दर्शवणारे आकृतीबंध',
    'map.schools.legend': 'रेषांचे प्रकार',
    'map.schools.hint': 'संबंध पाहण्यासाठी दर्शनावर टॅप करा. फिकट रेषा सर्व वाद व प्रभाव दर्शवतात; निवडलेल्या दर्शनाच्या रेषा गडद होतात.',
    'map.schools.relations': 'परस्परसंबंध',
    'vx.intro': 'चार संग्रह, काळाच्या एका रेषेवर. प्रत्येक वेद चार स्तरांत वाढला — मंत्र, यज्ञविवरण, अरण्यग्रंथ आणि चिंतन — आणि नामवंत आचार्यांनी तो वाहून नेला. पट्टी, ऋषी किंवा कार्डावर टॅप करा.',
    'vx.intro_eyebrow': 'विभाग-अन्वेषक',
    'vx.layers': 'ग्रंथाचे स्तर',
    'vx.seers': 'ऋषी आणि आचार्य',
    'vx.ideas': 'शोधण्यासारख्या संकल्पना',
    'vx.legend_layers': 'ग्रंथ-स्तर — गडद म्हणजे अधिक प्राचीन',
    'vx.approx': 'कालनिर्णय अंदाजे आहेत',
    'vx.seer': 'ऋषी',
    'vx.close': 'बंद करा',
    'vx.open_related': 'संबंधित पान उघडा',
    'vx.pending': 'या स्तराचे ग्रंथ लवकरच जोडले जातील.',
    'vx.timeline_aria': 'वैदिक ग्रंथ-स्तर आणि ऋषींची कालरेषा',
    'vx.choose': 'वेद निवडा',
    'vx.deep': 'हा वेद सविस्तर वाचा',
    'vx.deep_eyebrow': 'सविस्तर',
    'vx.deep_title': 'शाखा, सूक्ते आणि शिकवण',
    'up.intro': 'दहा प्रमुख उपनिषदे, ज्या वेदाशी जोडलेली त्यानुसार गटबद्ध, काळाच्या एका रेषेवर. सर्वात प्राचीन उपनिषदे दीर्घ संवादरूप आहेत; नंतरची लहान व एकाग्र. पट्टी, ऋषी किंवा कार्डावर टॅप करा.',
    'up.legend': 'प्रत्येक पट्टी एक उपनिषद — गडद म्हणजे अधिक प्राचीन',
    'up.count': '{n} उपनिषदे',
    'up.count_one': '१ उपनिषद',
    'up.texts': 'उपनिषदे',
    'up.open': 'संपूर्ण पान उघडा',
    'up.timeline_aria': 'वेदांनुसार प्रमुख उपनिषदांची कालरेषा',
    'ge.intro_timeline': 'या विभागातील सर्व काही अंदाजे काळाच्या एका रेषेवर. पट्टी, व्यक्ती किंवा चौकटीवर टॅप करून वाचा.',
    'ge.intro_cards': 'या विभागात शिरण्याचा जलद मार्ग. थोडक्यात माहितीसाठी चौकटीवर टॅप करा, मग संपूर्ण पान उघडा.',
    'ge.legend': 'प्रत्येक पट्टी एक ग्रंथ, दर्शन किंवा व्यक्ती — गडद म्हणजे आधीचे',
    'ge.people': 'व्यक्ती',
    'ge.items': 'या विभागात',
    'ge.topics': 'शोधण्यासारखे विषय',
    'ge.count': '{n} नोंदी',
    'ge.timeline_aria': 'या विभागाची कालरेषा',
    'ov.eyebrow': 'आढावा',
    'ov.count': '{n} विभाग',
    'ov.lede': 'संपूर्ण संग्रहाचा एका दृष्टिक्षेपात आढावा, प्रत्येक विभाग ज्या कालखंडाचा त्यानुसार मांडलेला. कोणताही विभाग उघडून त्याची स्वतःची कालरेषा, व्यक्ती आणि ज्ञान-कार्डे पहा.',
    'ov.eras': 'कालखंडाकडे जा',
    'ov.n_sections': '{n} विभाग',
    'sm.eyebrow': 'परस्परसंबंध',
    'sm.title': 'दर्शने एकमेकांशी कशी जोडलेली आहेत',
    'map.open': 'संपूर्ण पान उघडा',
    'map.close': 'बंद करा',
    'search.placeholder': 'श्लोक, सूक्त, संप्रदाय शोधा...',
    // Hero
    'hero.eyebrow': 'दैनिक सुभाषित · २४ वैशाख · सौम्य संवत्सर',
    'hero.title': 'भारतीय ज्ञानप्रणालींमध्ये रुजलेले ग्रंथ, विज्ञान आणि जीवनपद्धतींचे एक खुले डिजिटल संग्रहण.',
    'hero.show_trans': 'भाषांतर दाखवा',
    'hero.hide_trans': 'भाषांतर लपवा',
    'hero.read_essay': 'निबंध वाचा →',
    'hero.begin_here': 'इथून सुरुवात करा',
    'hero.continue_reading': 'वाचन सुरू ठेवा',
    'hero.explore_paths': 'आणखी प्रवास पाहा',
    'hero.choose_path': 'सर्व प्रवास पाहा',
    // Verse (mahāvākya / subhāṣita)
    'verse.mahavakya_label': 'महावाक्य · महान वचने',
    'verse.subhashit_label': 'सुभाषित · भर्तृहरि',
    'verse.today_mahavakya': 'आजचे महावाक्य',
    'verse.today_subhashit': 'आजचे सुभाषित',
    'verse.show_explanation': 'विवेचन पहा',
    'verse.next': 'दुसरे वचन',
    'verse.meaning': 'अर्थ',
    'verse.explanation': 'विवेचन',
    'verse.close': 'बंद करा',
    'verse.share': 'शेअर करा',
    'verse.copy': 'मजकूर कॉपी करा',
    'verse.copied': 'कॉपी झाले ✓',
    'verse.share_footer': 'भारतीय ज्ञान भंडाराबद्दल अधिक जाणून घेण्यासाठी — भारतीय ज्ञानप्रणालींचे एक खुले डिजिटल संग्रहण —',
    // Daily notification (Android app)
    'notify.title': 'दैनिक वचन सूचना',
    'notify.desc': 'रोज सकाळी आजचे वचन मिळवा — इंटरनेटशिवायही चालते.',
    'notify.time': 'वेळ',
    'notify.collection': 'वचन',
    'notify.subhashita': 'सुभाषित',
    'notify.mahavakya': 'महावाक्य',
    'notify.both': 'दोन्ही, आलटून पालटून',
    'notify.denied': 'सूचनांची परवानगी नाकारली गेली — सिस्टम सेटिंग्जमध्ये ती सुरू करा.',
    // Site share
    'site.share_btn': 'हे संकेतस्थळ शेअर करा',
    // Tree
    'tree.eyebrow': 'ज्ञानकोश नकाशा',
    'tree.title': 'तीन ज्ञानप्रवाह',
    'tree.hover_prompt': 'पानावर माउस फिरवा · उघडण्यासाठी क्लिक करा',
    'tree.branch': 'शाखा',
    'tree.streams': 'प्रवाह',
    'tree.open_page': 'पृष्ठ उघडा →',
    // Timeline
    'timeline.eyebrow': 'ज्ञानकोश कालक्रम',
    'timeline.title': 'ऐतिहासिक कालरेषा',
    'timeline.prompt': 'तपशील पाहण्यासाठी कोणत्याही प्रवाहावर क्लिक करा',
    // Grid
    'grid.eyebrow': 'संपूर्ण संग्रह',
    'grid.title': 'संपूर्ण संग्रह चाळा',
    'grid.lede': 'संपूर्ण संदर्भ-सूची — सर्व २८ प्रवाह, कालखंडानुसार मांडलेले. मार्गदर्शित वाचनासाठी वरील मार्गांपासून सुरुवात करा.',
    'grid.showing': '{total} पैकी {count} प्रवाह दर्शवत आहे',
    'grid.tag_era': 'कालखंड',
    'grid.tag_canon': 'प्रमाण ग्रंथ',
    'grid.tag_topic': 'विषय',
    // Contributors
    'contrib.eyebrow': 'योगदाते',
    'contrib.title': 'ऋषी, आचार्य, संत आणि शास्त्रज्ञ — कालक्रमेण',
    'contrib.meta': '{count} योगदाते · चार कालखंड',
    'contrib.prompt': 'त्यांच्या योगदानाचा संपूर्ण तपशील पाहण्यासाठी कोणत्याही कार्डावर क्लिक करा',
    'contrib.detail.tag': 'सविस्तर माहिती',
    'contrib.detail.contributions': 'प्रमुख योगदान',
    'contrib.detail.legacy': 'वारसा व प्रभाव',
    'contrib.detail.works': 'प्रमुख ग्रंथ',
    'contrib.detail.explore': 'संग्रहणात अधिक पहा',
    'contrib.detail.close': 'बंद करा',
    // Core concepts
    'concepts.eyebrow': 'मूलचौकट',
    'concepts.title': 'भारतीय ज्ञानप्रणालींच्या मूलसंकल्पना',
    'concepts.meta': '{count} संकल्पना · सात क्षेत्रे',
    'concepts.prompt': 'पूर्ण अर्थ व महत्त्व पाहण्यासाठी कोणत्याही कार्डावर क्लिक करा',
    'concepts.detail.aspects': 'मुख्य पैलू',
    'concepts.detail.significance': 'महत्त्व',
    'concepts.detail.related': 'संबंधित संज्ञा',
    'concepts.detail.appears': 'ग्रंथसंपदेत कुठे',
    'concepts.detail.first': 'प्रथम विवेचन',
    'concepts.detail.referred': 'पुढील विकास',
    'concepts.detail.explore': 'संग्रहणात अधिक पहा',
    'concepts.detail.close': 'बंद करा',
    // Dinacharya
    'dina.eyebrow': 'जीवनशैली',
    'dina.title': 'दिनचर्या — दिवसाचे नियोजन',
    'dina.meta': 'सहा विभाग · पारंपरिक आयुर्वेद',
    // Essays
    'essays.eyebrow': 'संपादकीय',
    'essays.title': 'संपादकांचे निबंध',
    'essays.meta': 'साप्ताहिक अद्यतने',
    // Footer
    'footer.colophon': 'भारतीय ज्ञानप्रणालींचे खुले डिजिटल संग्रहण. मूळ मजकूर आणि लिप्यंतरण स्वरूपात उपलब्ध. संशोधक आणि विद्वानांद्वारे भाषांतर व स्पष्टीकरण. वाचनासाठी विनामूल्य; चिरंतन रचलेले.',
    'footer.compiled_by': 'संकलन — विवेक सोवनी',
    'footer.sec_texts': 'ग्रंथ संपदा',
    'footer.sec_tools': 'साधने',
    'footer.sec_about': 'माहिती',
    'footer.samvat': '© विक्रम संवत् २०८३',
    'footer.setin': 'कॉर्मोरेंट, लोरा आणि तिरो देवनागरी संस्कृत फॉन्टमध्ये डिझाइन केलेले',
    'footer.license': 'एक खुले संग्रहण · CC BY-SA 4.0',
    // Details
    'detail.back': '← संग्रहणाकडे परत',
    'detail.continue': 'संग्रहणात वाचन सुरू ठेवा',
    'detail.the_opening': 'प्रारंभ',
    'detail.at_a_glance': 'एका दृष्टीक्षेपात',
    'detail.practice_focused': 'सराव-केंद्रित प्रवाह. संदर्भ पॅनेलमध्ये संपूर्ण वाचन-सूची पहा.',
    'detail.recension': 'शाखा/आवृत्ती',
    'detail.authors': 'लेखक/ऋषी',
    'detail.range': 'व्याप्ती',
    'detail.scope': 'विषयक्षेत्र',
    'detail.officiant': 'पुरोहित/ऋत्विज',
    'detail.period': 'कालखंड',
    'detail.strata': 'प्रत्येक वेदाचे चार स्तर',
    'detail.library': 'संग्रहण',
    // Living Knowledge
    'nav.lk': 'जिवंत ज्ञान',
    'lk.eyebrow': 'जिवंत ज्ञान',
    'lk.title': 'भारतीय ज्ञानप्रणालींची जगाला देणगी',
    'lk.title_short': 'जिवंत ज्ञान',
    'lk.meta': '{count} योगदाने · नऊ क्षेत्रे',
    'lk.note_label': 'प्रामाणिकतेची नोंद:',
    'lk.prompt': 'योगदाने पाहण्यासाठी कोणत्याही क्षेत्र टाइलवर क्लिक करा, नंतर अधिक वाचण्यासाठी योगदानावर क्लिक करा.',
    'lk.count': '{n} योगदाने',
    'lk.debated': 'विवादित दावा',
    'lk.expand': 'योगदाने पहा',
    'lk.collapse': 'लपवा',
    'lk.read_more': 'अधिक वाचा →',
    'lk.what': 'हे काय आहे',
    'lk.when': 'कधी उदयास आले',
    'lk.how': 'आज कसे उपयुक्त आहे',
    'lk.back_label': '← जिवंत ज्ञानाकडे परत',
    'lk.back_to_domains': '↑ सर्व क्षेत्रांकडे परत',
    'lk.phase2': 'सविस्तर माहिती लवकरच येणार आहे — दुसऱ्या टप्प्यात तपासा.',
    // Journeys
    'jrn.eyebrow': 'मार्गदर्शित वाचन',
    'jrn.title': 'तुमचा वाचन-मार्ग निवडा',
    'jrn.lede': 'वृक्ष कसा वाढला हे तुम्ही आत्ताच पाहिलंत. आता त्यातून कसं चालायचं ते निवडा.',
    'jrn.themed_heading': 'किंवा विषयानुरूप प्रवास',
    'jrn.meta': '{count} विषयानुरूप प्रवास',
    'jrn.steps_min': '{steps} टप्पे · अंदाजे {minutes} मिनिटे',
    'jrn.begin': 'सुरू करा →',
    'jrn.continue': 'पुढे सुरू ठेवा · टप्पा {n} →',
    'jrn.complete_badge': 'पूर्ण झाले ✓',
    'jrn.list.eyebrow': 'मार्गदर्शित वाचन',
    'jrn.list.title': 'सर्व प्रवास',
    'jrn.crumb': 'प्रवास',
    'jrn.step_of': '{total} पैकी टप्पा {n}',
    'jrn.min_short': '{n} मिनिटे',
    'jrn.reset': 'प्रगती रीसेट करा',
    'jrn.reset_confirm': '"{title}" वरील तुमची प्रगती रीसेट करायची? हे पूर्ववत करता येणार नाही.',
    'tabnav.prev': 'मागील',
    'tabnav.next': 'पुढील',
    'jrn.visited': 'वाचले',
    'jrn.begin_step': 'हा प्रवास सुरू करा →',
    'jrn.ribbon.next': 'पुढे',
    'jrn.ribbon.trail': 'मार्ग-नकाशा',
    'jrn.ribbon.dismiss': 'बंद करा',
    'jrn.ribbon.done_title': 'तुम्ही {title} हा प्रवास पूर्ण केला.',
    'jrn.ribbon.done_more': 'पुढे सुरू ठेवा:',
    // Reading spine (the complete path)
    'spine.eyebrow': 'क्रमाने वाचा',
    'spine.title': 'संपूर्ण मार्ग',
    'spine.tagline': 'संग्रहातील प्रत्येक प्रवाह, जसजसा तो घडत गेला त्या क्रमाने — वैदिक ते आधुनिक. स्रोतापासून सुरुवात करा आणि प्रत्येक पान पुढच्या पानाकडे नेईल.',
    'spine.begin': 'सुरुवातीपासून वाचा',
    'spine.continue': 'पुढे चालू ठेवा · क्र. {n}',
    'spine.walked': '{total} पैकी {n} वाचले',
    'spine.see_all': 'संपूर्ण मार्ग पहा →',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('bgb-lang') as Language;
    if (saved === 'mr' || saved === 'en') {
      setLangState(saved);
      document.documentElement.setAttribute('lang', saved);
    } else {
      document.documentElement.setAttribute('lang', 'en');
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    try {
      localStorage.setItem('bgb-lang', newLang);
      document.documentElement.setAttribute('lang', newLang);
    } catch {}
  };

  const t = (key: string): string => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
