// Gifts of Indian Knowledge Systems to the world — 72 contributions across 9 domains.
// Still practically relevant today.

export type DomainId =
  | 'math'
  | 'astronomy'
  | 'medicine'
  | 'mind'
  | 'body'
  | 'environment'
  | 'language'
  | 'materials'
  | 'life';

export type Gift = {
  id: string;
  n: number;
  name: string;
  deva: string;
  seal: string;
  blurb: string;
  domain: DomainId;
  debated?: boolean;
  what: string;
  when: string;
  how: string;
};

export type DomainMeta = {
  id: DomainId;
  label: string;
  deva: string;
  seal: string;
  gloss: string;
};

export const LK_DOMAINS: DomainId[] = [
  'math', 'astronomy', 'medicine', 'mind', 'body',
  'environment', 'language', 'materials', 'life',
];

export const LK_DOMAIN_META: DomainMeta[] = [
  {
    id: 'math',
    label: 'Mathematics & Logic',
    deva: 'गणित व तर्कशास्त्र',
    seal: '०',
    gloss: 'Zero, algebra, trigonometry, binary numbers, infinite series — the mathematical bedrock of modern computing and science.',
  },
  {
    id: 'astronomy',
    label: 'Astronomy & Time',
    deva: 'खगोलशास्त्र व कालगणना',
    seal: '☽',
    gloss: 'Earth\'s rotation, accurate eclipse prediction, solar calendars, and cosmic time scales spanning billions of years.',
  },
  {
    id: 'medicine',
    label: 'Medicine & Physical Health',
    deva: 'आयुर्वेद',
    seal: 'औ',
    gloss: 'Preventive medicine, surgery, a vast herbal pharmacopoeia, daily health rhythms, and the concept of food as medicine.',
  },
  {
    id: 'mind',
    label: 'Psychology & the Mind',
    deva: 'मनोविज्ञान',
    seal: 'ध्',
    gloss: 'Meditation, breath regulation, layered models of the psyche, equanimity, and self-inquiry — all clinically studied today.',
  },
  {
    id: 'body',
    label: 'The Body & Physical Practice',
    deva: 'शरीर व साधना',
    seal: 'आ',
    gloss: 'Āsanas, Sūrya Namaskāra, martial traditions, and purification practices now studied by modern medicine.',
  },
  {
    id: 'environment',
    label: 'Environment & Sustainable Living',
    deva: 'पर्यावरण व सुस्थिर जीवन',
    seal: 'वृ',
    gloss: 'Sacred groves, plant science, water harvesting, low-footprint vegetarian living, and the five-elements worldview.',
  },
  {
    id: 'language',
    label: 'Language, Arts & Society',
    deva: 'भाषा, कला व समाज',
    seal: 'पा',
    gloss: 'The world\'s first formal grammar, music theory, statecraft, fables that shaped world literature, and chess.',
  },
  {
    id: 'materials',
    label: 'Materials, Trade & Technology',
    deva: 'धातुकर्म व व्यापार',
    seal: 'ल',
    gloss: 'Rust-resistant iron, crucible steel, zinc distillation, crystallized sugar, cotton, diamonds — cornerstones of global trade.',
  },
  {
    id: 'life',
    label: 'Frameworks for a Happy, Balanced Life',
    deva: 'संतुलित जीवनाची चौकट',
    seal: 'पु',
    gloss: 'The Puruṣārthas, Āśrama life stages, situational ethics, fasting, and the universal-family ethic.',
  },
];

export const LIVING_KNOWLEDGE: Gift[] = [
  // ── Mathematics & Logic ───────────────────────────────────────────────────
  {
    id: 'zero',
    n: 1,
    name: 'Zero (śūnya) as a number',
    deva: 'शून्य',
    seal: '०',
    domain: 'math',
    blurb: 'Not merely a placeholder but a true quantity with its own arithmetic — the single most consequential idea for modern computing, banking, and science.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'decimal-system',
    n: 2,
    name: 'The decimal place-value system',
    deva: 'दशमान पद्धती',
    seal: 'द',
    domain: 'math',
    blurb: 'The way nearly the whole world writes numbers today, transmitted to Europe as "Hindu-Arabic" numerals.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'negative-numbers',
    n: 3,
    name: 'Negative numbers and their rules',
    deva: 'ऋण संख्या',
    seal: 'ऋ',
    domain: 'math',
    blurb: 'Brahmagupta (7th c.) gave formal rules for operating with debts and fortunes — negatives and positives.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'algebra',
    n: 4,
    name: 'Algebra (bījagaṇita)',
    deva: 'बीजगणित',
    seal: 'बी',
    domain: 'math',
    blurb: 'Systematic solving of linear, quadratic, and indeterminate equations.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'trigonometry',
    n: 5,
    name: 'Trigonometry',
    deva: 'ज्या',
    seal: 'ज्',
    domain: 'math',
    blurb: 'The sine function (jyā) originates in India and reached Europe via Arabic translation; the word "sine" is a mistranslation of jyā.',
    debated: true,
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'calculus',
    n: 6,
    name: 'Early calculus ideas',
    deva: 'माधव श्रेणी',
    seal: 'म',
    domain: 'math',
    blurb: 'The Mādhava–Kerala school (14th–16th c.) developed infinite series for sine, cosine, and arctangent centuries before Newton and Leibniz.',
    debated: true,
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'pi',
    n: 7,
    name: 'Accurate values of π',
    deva: 'π मूल्य',
    seal: 'π',
    domain: 'math',
    blurb: "From Āryabhaṭa's 3.1416 to Mādhava's rapidly converging series.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'binary-combinatorics',
    n: 8,
    name: 'Binary numbers and combinatorics',
    deva: 'मेरु प्रस्तार',
    seal: 'पि',
    domain: 'math',
    blurb: "Piṅgala's prosody used a binary system and produced the Meru sequence (Fibonacci numbers) and Pascal's triangle long before their European namesakes.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'sulba-sutras',
    n: 9,
    name: 'The geometry of the Śulba Sūtras',
    deva: 'शुल्बसूत्र',
    seal: 'शु',
    domain: 'math',
    blurb: 'Practical theorems — including the "Pythagorean" relation — for precise altar construction.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'infinity',
    n: 10,
    name: 'Comfort with the infinite and the very large',
    deva: 'अनन्त',
    seal: 'अ',
    domain: 'math',
    blurb: 'A distinctive Indian intellectual habit, with named units running to staggering magnitudes.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'atom',
    n: 11,
    name: 'The atom (aṇu / paramāṇu)',
    deva: 'परमाणु',
    seal: 'अ',
    domain: 'math',
    blurb: "Kaṇāda's Vaiśeṣika school theorized indivisible particles combining to form matter.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'nyaya-logic',
    n: 12,
    name: 'Formal logic (Nyāya)',
    deva: 'न्याय',
    seal: 'न्',
    domain: 'math',
    blurb: 'A rigorous epistemology with the five-membered syllogism and a theory of valid means of knowledge (pramāṇa).',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'many-valued-logic',
    n: 13,
    name: 'Many-valued logic (anekāntavāda / syādvāda)',
    deva: 'अनेकान्तवाद',
    seal: 'अ',
    domain: 'math',
    blurb: 'The Jain doctrine of "many-sidedness" — an early framework for pluralism, tolerance, and reasoning under partial truth.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Astronomy & Time ──────────────────────────────────────────────────────
  {
    id: 'earth-rotation',
    n: 14,
    name: "Earth's daily rotation",
    deva: 'भूभ्रमण',
    seal: 'भ',
    domain: 'astronomy',
    blurb: "Proposed by Āryabhaṭa (5th c.), who compared it to a boat traveller seeing the riverbank move.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'eclipses',
    n: 15,
    name: 'Eclipses by shadow, not myth',
    deva: 'ग्रहण',
    seal: 'ग्',
    domain: 'astronomy',
    blurb: 'A correct geometric cause for solar and lunar eclipses.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'solar-year',
    n: 16,
    name: 'Highly accurate solar/sidereal year',
    deva: 'सौरवर्ष',
    seal: 'स',
    domain: 'astronomy',
    blurb: 'Within minutes of the modern value.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'circumference-planets',
    n: 17,
    name: "Earth's circumference and planetary positions",
    deva: 'भूपरिधि',
    seal: 'पृ',
    domain: 'astronomy',
    blurb: 'Computed with impressive precision.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'panchanga',
    n: 18,
    name: 'The pañchāṅga',
    deva: 'पञ्चांग',
    seal: 'प',
    domain: 'astronomy',
    blurb: 'A luni-solar calendar still governing agriculture and festivals across India.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'nakshatras',
    n: 19,
    name: 'The nakṣatra system',
    deva: 'नक्षत्र',
    seal: 'न',
    domain: 'astronomy',
    blurb: '27 lunar mansions for timekeeping and celestial navigation.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'cosmic-time',
    n: 20,
    name: 'Cosmic time scales (yuga, kalpa)',
    deva: 'युग कल्प',
    seal: 'यु',
    domain: 'astronomy',
    blurb: 'Units spanning from the truṭi (a fraction of a second) to billions of years.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'cyclical-time',
    n: 21,
    name: 'A cyclical model of time',
    deva: 'चक्रीय काल',
    seal: 'च',
    domain: 'astronomy',
    blurb: 'A mental frame that encourages patience, perspective, and long-term thinking.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'jantar-mantar',
    n: 22,
    name: 'Astronomical instruments',
    deva: 'यन्त्र',
    seal: 'य',
    domain: 'astronomy',
    blurb: 'Culminating in the monumental Jantar Mantar observatories.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Medicine & Physical Health ────────────────────────────────────────────
  {
    id: 'preventive-medicine',
    n: 23,
    name: 'Preventive, holistic medicine',
    deva: 'स्वास्थ्यरक्षण',
    seal: 'स्',
    domain: 'medicine',
    blurb: 'Health defined as balance, not merely the absence of disease.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'sushruta-surgery',
    n: 24,
    name: "Suśruta's surgery",
    deva: 'शल्यतंत्र',
    seal: 'श',
    domain: 'medicine',
    blurb: 'Cataract operations, rhinoplasty (skin-graft nose reconstruction), and ~300 procedures with 120 instruments.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'charaka-medicine',
    n: 25,
    name: "Charaka's internal medicine",
    deva: 'चरक',
    seal: 'च',
    domain: 'medicine',
    blurb: "Systematic diagnosis, disease classification, and a physician's code of ethics.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'herbal-pharmacopoeia',
    n: 26,
    name: 'A vast herbal pharmacopoeia',
    deva: 'औषधिकोश',
    seal: 'औ',
    domain: 'medicine',
    blurb: 'Thousands of plant remedies still mined by modern pharmacology — turmeric/curcumin, neem, ashwagandha.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'dinacharya',
    n: 27,
    name: 'Daily and seasonal routines (dinacharyā / ṛitucharyā)',
    deva: 'दिनचर्या',
    seal: 'दि',
    domain: 'medicine',
    blurb: 'Practical rhythms aligning life with the body clock — strikingly close to modern circadian science.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'food-as-medicine',
    n: 28,
    name: 'Food as medicine',
    deva: 'आहार',
    seal: 'अ',
    domain: 'medicine',
    blurb: 'Diet personalized to constitution; the idea that what you eat is treatment.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'agni-digestion',
    n: 29,
    name: 'Metabolism and digestion (agni)',
    deva: 'अग्नि',
    seal: 'अ',
    domain: 'medicine',
    blurb: 'Digestive "fire" as the hinge of health.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'marma-points',
    n: 30,
    name: 'Marma points',
    deva: 'मर्म',
    seal: 'म',
    domain: 'medicine',
    blurb: 'Mapped vital points — the basis of therapeutic bodywork.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'variolation',
    n: 31,
    name: 'Variolation against smallpox',
    deva: 'टीकाकरण',
    seal: 'टी',
    domain: 'medicine',
    debated: true,
    blurb: 'Early inoculation practices (documented, though scale and origins are debated).',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'rasashastra',
    n: 32,
    name: 'Rasaśāstra (alchemical chemistry)',
    deva: 'रसशास्त्र',
    seal: 'र',
    domain: 'medicine',
    blurb: 'Purification and medicinal use of metals and minerals; early chemical processing.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Psychology & the Mind ─────────────────────────────────────────────────
  {
    id: 'yoga-eight-limbs',
    n: 33,
    name: "Yoga's eight limbs (Patañjali)",
    deva: 'अष्टांग योग',
    seal: 'यो',
    domain: 'mind',
    blurb: 'A complete operating manual for training attention and the mind.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'meditation',
    n: 34,
    name: 'Meditation (dhyāna)',
    deva: 'ध्यान',
    seal: 'ध्',
    domain: 'mind',
    blurb: 'Now clinically validated for stress, focus, and emotional health.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'pranayama',
    n: 35,
    name: 'Breath regulation (prāṇāyāma)',
    deva: 'प्राणायाम',
    seal: 'प्र',
    domain: 'mind',
    blurb: 'Direct, learnable control of the nervous system.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'layered-psyche',
    n: 36,
    name: 'A layered model of the psyche',
    deva: 'अन्तःकरण',
    seal: 'म',
    domain: 'mind',
    blurb: 'Manas (sensory mind), buddhi (intellect), ahaṃkāra (ego), chitta (memory-substrate).',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'mindfulness',
    n: 37,
    name: 'Mindfulness / present-moment awareness',
    deva: 'वर्तमान',
    seal: 'सा',
    domain: 'mind',
    blurb: 'Millennia before it became a wellness industry.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'karma-yoga',
    n: 38,
    name: 'Karma yoga',
    deva: 'कर्मयोग',
    seal: 'क',
    domain: 'mind',
    blurb: 'Acting wholeheartedly while releasing attachment to results — a genuine antidote to anxiety and burnout.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'gunas',
    n: 39,
    name: 'The guṇa framework (sattva / rajas / tamas)',
    deva: 'गुण',
    seal: 'गु',
    domain: 'mind',
    blurb: 'A practical lens for understanding moods, energy, and temperament.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'equanimity',
    n: 40,
    name: 'Equanimity (samatva)',
    deva: 'समत्व',
    seal: 'स',
    domain: 'mind',
    blurb: 'Emotional regulation treated as a trainable skill, not a fixed trait.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'self-inquiry',
    n: 41,
    name: 'Self-inquiry and Vedānta',
    deva: 'आत्मविचार',
    seal: 'आ',
    domain: 'mind',
    blurb: 'Tools for existential anxiety, identity, and the question "Who am I?"',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'yoga-nidra',
    n: 42,
    name: 'Yoga nidrā',
    deva: 'योगनिद्रा',
    seal: 'नि',
    domain: 'mind',
    blurb: 'Structured deep relaxation — ancestor of modern guided relaxation therapy.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── The Body & Physical Practice ─────────────────────────────────────────
  {
    id: 'asanas',
    n: 43,
    name: 'Āsanas',
    deva: 'आसन',
    seal: 'आ',
    domain: 'body',
    blurb: 'Postures for flexibility, strength, and longevity — now practised worldwide.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'surya-namaskar',
    n: 44,
    name: 'Sūrya Namaskāra',
    deva: 'सूर्यनमस्कार',
    seal: 'सू',
    domain: 'body',
    blurb: 'A single flowing sequence that exercises the whole body.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'kalaripayattu',
    n: 45,
    name: 'Martial traditions (Kalaripayattu, etc.)',
    deva: 'कलरिपयट्टु',
    seal: 'क',
    domain: 'body',
    blurb: 'Conditioning, discipline, and body awareness.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'shatkarma',
    n: 46,
    name: 'Yogic purification (ṣaṭkarma) and hygiene practices',
    deva: 'षट्कर्म',
    seal: 'ष',
    domain: 'body',
    blurb: 'Tongue scraping, oil pulling, nasal cleansing — several now studied by dentistry and ENT.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Environment & Sustainable Living ──────────────────────────────────────
  {
    id: 'sacred-groves',
    n: 47,
    name: 'Sacred groves and reverence for nature',
    deva: 'देवराई',
    seal: 'दे',
    domain: 'environment',
    blurb: 'Rivers, trees, and mountains protected by sanctity — among the world\'s earliest conservation systems.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'vrikshayurveda',
    n: 48,
    name: 'Vṛkṣāyurveda',
    deva: 'वृक्षायुर्वेद',
    seal: 'वृ',
    domain: 'environment',
    blurb: 'A science of plant care, grafting, and agriculture.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'organic-farming',
    n: 49,
    name: 'Organic and cow-based farming',
    deva: 'गोआधारित कृषी',
    seal: 'गो',
    domain: 'environment',
    blurb: 'Methods now revisited for soil health and regeneration.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'ahimsa-ecology',
    n: 50,
    name: 'Ahiṃsā extended to ecology',
    deva: 'अहिंसा',
    seal: 'अ',
    domain: 'environment',
    blurb: 'Minimal harm to all living systems as an ethical baseline.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'water-harvesting',
    n: 51,
    name: 'Traditional water harvesting',
    deva: 'जलसंचय',
    seal: 'ज',
    domain: 'environment',
    blurb: 'Stepwells (baolis), tanks, and catchment engineering for arid climates.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'five-elements',
    n: 52,
    name: 'The five elements (pañca-mahābhūta)',
    deva: 'पञ्चमहाभूत',
    seal: 'पं',
    domain: 'environment',
    blurb: 'A worldview of living in conscious harmony with earth, water, fire, air, and space.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'vegetarian-living',
    n: 53,
    name: 'Low-footprint vegetarian living',
    deva: 'शाकाहार',
    seal: 'शा',
    domain: 'environment',
    blurb: 'A dietary tradition increasingly relevant to climate and resource limits.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Language, Arts & Society ──────────────────────────────────────────────
  {
    id: 'panini-grammar',
    n: 54,
    name: "Pāṇini's Aṣṭādhyāyī",
    deva: 'अष्टाध्यायी',
    seal: 'पा',
    domain: 'language',
    blurb: "The world's first formal generative grammar (~5th c. BCE), whose rule-based structure anticipates modern linguistics and computer science.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'phonetics',
    n: 55,
    name: 'The science of phonetics (śikṣā)',
    deva: 'शिक्षा',
    seal: 'शि',
    domain: 'language',
    blurb: 'Speech sounds classified by place and manner of articulation — arguably the most rigorous pre-modern phonetic system.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'raga-natyashastra',
    n: 56,
    name: 'The rāga system and Nāṭyaśāstra',
    deva: 'नाट्यशास्त्र',
    seal: 'रा',
    domain: 'language',
    blurb: 'A deep theory of music, performance, and rasa (aesthetic emotion).',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'mimamsa-hermeneutics',
    n: 57,
    name: 'Hermeneutics (Mīmāṃsā)',
    deva: 'मीमांसा',
    seal: 'मी',
    domain: 'language',
    blurb: 'Sophisticated rules of textual interpretation that influenced Indian jurisprudence.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'panchatantra',
    n: 58,
    name: 'The Pañchatantra',
    deva: 'पञ्चतन्त्र',
    seal: 'पं',
    domain: 'language',
    blurb: 'Fables that travelled across Persia, Arabia, and Europe, shaping world storytelling.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'chess',
    n: 59,
    name: 'Chess (chaturaṅga)',
    deva: 'चतुरंग',
    seal: 'च',
    domain: 'language',
    blurb: 'The ancestor of modern chess.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'arthashastra',
    n: 60,
    name: 'Statecraft and economics (Arthaśāstra)',
    deva: 'अर्थशास्त्र',
    seal: 'अ',
    domain: 'language',
    blurb: "Kauṭilya's treatise on administration, taxation, diplomacy, and intelligence.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'vastu',
    n: 61,
    name: 'Vāstu Śāstra',
    deva: 'वास्तुशास्त्र',
    seal: 'वा',
    domain: 'language',
    blurb: 'Principles of spatial design, orientation, and architecture.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Materials, Trade & Technology ─────────────────────────────────────────
  {
    id: 'iron-pillar',
    n: 62,
    name: 'Rust-resistant iron',
    deva: 'लोहस्तम्भ',
    seal: 'ल',
    domain: 'materials',
    blurb: 'The Delhi Iron Pillar has resisted corrosion for over 1,600 years.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'wootz-steel',
    n: 63,
    name: 'Wootz / crucible steel',
    deva: 'उक्क',
    seal: 'इ',
    domain: 'materials',
    blurb: 'The high-carbon steel that became famed "Damascus" blades.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'zinc-distillation',
    n: 64,
    name: 'Zinc distillation',
    deva: 'जस्त',
    seal: 'ज',
    domain: 'materials',
    blurb: 'India pioneered the metallurgy of producing pure zinc.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'sugar',
    n: 65,
    name: 'Crystallized sugar',
    deva: 'शर्करा',
    seal: 'श',
    domain: 'materials',
    blurb: 'Śarkarā gives us the very word "sugar."',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'cotton-indigo',
    n: 66,
    name: 'Cotton cultivation, textiles, and dyeing',
    deva: 'कापूस',
    seal: 'क',
    domain: 'materials',
    blurb: 'Including indigo — a cornerstone of global trade.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'diamonds',
    n: 67,
    name: 'Diamond mining and cutting',
    deva: 'हीरा',
    seal: 'ही',
    domain: 'materials',
    blurb: 'The Golconda mines supplied the world for centuries.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Frameworks for a Happy, Balanced Life ─────────────────────────────────
  {
    id: 'purusharthas',
    n: 68,
    name: 'The Puruṣārthas',
    deva: 'पुरुषार्थ',
    seal: 'पु',
    domain: 'life',
    blurb: 'Four aims of life held in balance: dharma (duty/ethics), artha (prosperity), kāma (pleasure/relationship), mokṣa (freedom). A complete model for a well-rounded life.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'ashrama',
    n: 69,
    name: 'The Āśrama system',
    deva: 'आश्रम',
    seal: 'आ',
    domain: 'life',
    blurb: 'Life organized in stages (learning, householder, withdrawal, renunciation) — an early life-planning framework.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'dharma-ethics',
    n: 70,
    name: 'Dharma as situational ethics',
    deva: 'धर्म',
    seal: 'ध',
    domain: 'life',
    blurb: 'Right action judged by context, role, and consequence rather than rigid rule.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'fasting',
    n: 71,
    name: 'Fasting (upavāsa)',
    deva: 'उपवास',
    seal: 'उ',
    domain: 'life',
    blurb: 'Periodic restraint from food; intermittent fasting is now mainstream nutrition science.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'vasudhaiva-kutumbakam',
    n: 72,
    name: 'Vasudhaiva Kuṭumbakam',
    deva: 'वसुधैव कुटुम्बकम्',
    seal: 'वसु',
    domain: 'life',
    blurb: '"The world is one family" — an ethic of universal kinship for a connected, fragile planet.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
];

export const LK_NOTE =
  'Indian civilization produced an extraordinary body of knowledge, but knowledge rarely belongs to one culture alone. ' +
  'Several discoveries below arose in parallel elsewhere too, and a few popular claims are debated by historians. ' +
  'Where that is the case, it is flagged. The aim here is intellectual respect, not exaggeration — the contributions are remarkable enough without inflation.';
