// Gifts of Indian Knowledge Systems to the world — 72 contributions across 9 domains.
// Still practically relevant today.

export type DomainId =
  | 'math'
  | 'astronomy'
  | 'medicine'
  | 'mind'
  | 'body'
  | 'environment'
  | 'language'
  | 'materials'
  | 'life';

export type Gift = {
  id: string;
  n: number;
  name: string;
  deva: string;
  seal: string;
  blurb: string;
  domain: DomainId;
  debated?: boolean;
  what: string;
  when: string;
  how: string;
};

export type DomainMeta = {
  id: DomainId;
  label: string;
  deva: string;
  seal: string;
  gloss: string;
};

export const LK_DOMAINS: DomainId[] = [
  'math', 'astronomy', 'medicine', 'mind', 'body',
  'environment', 'language', 'materials', 'life',
];

export const LK_DOMAIN_META: DomainMeta[] = [
  {
    id: 'math',
    label: 'Mathematics & Logic',
    deva: 'गणित व तर्कशास्त्र',
    seal: '०',
    gloss: 'Zero, algebra, trigonometry, binary numbers, infinite series — the mathematical bedrock of modern computing and science.',
  },
  {
    id: 'astronomy',
    label: 'Astronomy & Time',
    deva: 'खगोलशास्त्र व कालगणना',
    seal: '☽',
    gloss: 'Earth\'s rotation, accurate eclipse prediction, solar calendars, and cosmic time scales spanning billions of years.',
  },
  {
    id: 'medicine',
    label: 'Medicine & Physical Health',
    deva: 'आयुर्वेद',
    seal: 'औ',
    gloss: 'Preventive medicine, surgery, a vast herbal pharmacopoeia, daily health rhythms, and the concept of food as medicine.',
  },
  {
    id: 'mind',
    label: 'Psychology & the Mind',
    deva: 'मनोविज्ञान',
    seal: 'ध्',
    gloss: 'Meditation, breath regulation, layered models of the psyche, equanimity, and self-inquiry — all clinically studied today.',
  },
  {
    id: 'body',
    label: 'The Body & Physical Practice',
    deva: 'शरीर व साधना',
    seal: 'आ',
    gloss: 'Āsanas, Sūrya Namaskāra, martial traditions, and purification practices now studied by modern medicine.',
  },
  {
    id: 'environment',
    label: 'Environment & Sustainable Living',
    deva: 'पर्यावरण व सुस्थिर जीवन',
    seal: 'वृ',
    gloss: 'Sacred groves, plant science, water harvesting, low-footprint vegetarian living, and the five-elements worldview.',
  },
  {
    id: 'language',
    label: 'Language, Arts & Society',
    deva: 'भाषा, कला व समाज',
    seal: 'पा',
    gloss: 'The world\'s first formal grammar, music theory, statecraft, fables that shaped world literature, and chess.',
  },
  {
    id: 'materials',
    label: 'Materials, Trade & Technology',
    deva: 'धातुकर्म व व्यापार',
    seal: 'ल',
    gloss: 'Rust-resistant iron, crucible steel, zinc distillation, crystallized sugar, cotton, diamonds — cornerstones of global trade.',
  },
  {
    id: 'life',
    label: 'Frameworks for a Happy, Balanced Life',
    deva: 'संतुलित जीवनाची चौकट',
    seal: 'पु',
    gloss: 'The Puruṣārthas, Āśrama life stages, situational ethics, fasting, and the universal-family ethic.',
  },
];

export const LIVING_KNOWLEDGE: Gift[] = [
  // ── Mathematics & Logic ───────────────────────────────────────────────────
  {
    id: 'zero',
    n: 1,
    name: 'Zero (śūnya) as a number',
    deva: 'शून्य',
    seal: '०',
    domain: 'math',
    blurb: 'Not merely a placeholder but a true quantity with its own arithmetic — the single most consequential idea for modern computing, banking, and science.',
    what: `Zero is not merely a positional placeholder but a number in its own right, with its own arithmetic. The idea grew from the Indian philosophical concept of śūnya (void) and was crystallised by Brahmagupta (628 CE), who stated formal rules: a number added to zero equals itself; zero multiplied by any number is zero. Earlier texts use a dot for an empty position; Brahmagupta was the first to treat zero as a quantity to be manipulated arithmetically.`,
    when: `A dot marking an empty position appears in Piṅgala's Chandaḥśāstra (c. 200 BCE) and in the Bakhshali manuscript (3rd–4th c. CE). The Gwalior inscription (876 CE) has the earliest carved zero-as-digit. Brahmagupta's Brāhmasphuṭasiddhānta (628 CE) gives the first explicit arithmetic rules. The concept reached Arab scholars via translations and entered Europe through al-Khwārizmī's 9th-century works, though European acceptance was slow; zero was viewed with suspicion well into the medieval period.`,
    how: `Every digital computer operates in binary — a system in which zero is a value equal in status to one. Without zero there is no positional notation, no algebra, no calculus, and no computing as we know it. Financial accounts, coordinate systems in physics, the null set in mathematics, the origin in every graph — all depend on zero as a true number. Few ideas have reshaped civilisation as quietly and as completely.`,
  },
  {
    id: 'decimal-system',
    n: 2,
    name: 'The decimal place-value system',
    deva: 'दशमान पद्धती',
    seal: 'द',
    domain: 'math',
    blurb: 'The way nearly the whole world writes numbers today, transmitted to Europe as "Hindu-Arabic" numerals.',
    what: `The decimal place-value system assigns a different value to each digit depending on its position — ones, tens, hundreds, thousands. With only ten symbols (0–9), any number, however large or small, can be written compactly and unambiguously. By contrast, the Roman system required a different symbol for each magnitude and could not express fractions or very large numbers efficiently. The Indian system made arithmetic accessible to ordinary people and transformed trade, administration, and science.`,
    when: `The system is evident in Āryabhaṭa's Āryabhaṭīya (499 CE) and is elaborated by Brahmagupta (628 CE). Arab scholars encountered it through Indian texts in the 8th century; al-Khwārizmī's treatise (c. 825 CE) introduced it to the Islamic world as al-arqām al-hindiyya (Indian numerals). Fibonacci's Liber Abaci (1202 CE) popularised it in Europe. European adoption was slow but complete by the 15th century, displacing Roman numerals for practical calculation.`,
    how: `Every spreadsheet, calculator, bank statement, and scientific paper uses decimal place-value notation — the most widely used mathematical notation in human history. Its compactness makes mental arithmetic feasible and underlies the algorithms of long multiplication and division taught in schools worldwide. Without it, the quantitative reasoning that drove the scientific and industrial revolutions would have been far more laborious. Its Indian origin is preserved in the name 'Hindu-Arabic numerals' used by mathematicians and historians worldwide.`,
  },
  {
    id: 'negative-numbers',
    n: 3,
    name: 'Negative numbers and their rules',
    deva: 'ऋण संख्या',
    seal: 'ऋ',
    domain: 'math',
    blurb: 'Brahmagupta (7th c.) gave formal rules for operating with debts and fortunes — negatives and positives.',
    what: `Negative numbers represent quantities below a reference point — deficits, debts, temperatures below zero, forces in the opposing direction. Indian mathematicians called positive numbers dhana (wealth) and negatives ṛṇa (debt), grounding the concept in economic experience. Brahmagupta formalised the rules: a negative times a negative yields a positive; the sum of equal positive and negative is zero; and so on. These rules make algebra coherent and complete.`,
    when: `Brahmagupta's Brāhmasphuṭasiddhānta (628 CE) is the first text to state the rules for negative numbers explicitly and systematically. Chinese mathematicians used negative values (red rods for positive, black for negative) somewhat earlier but without the same formalisation. European mathematicians resisted negatives as 'absurd' or 'fictitious' well into the 16th century; Descartes called negative roots of equations 'false roots' as late as 1637.`,
    how: `Negative numbers are indispensable across every quantitative discipline. In economics they represent debt, deficit, and loss. In physics they encode direction, charge, and sub-zero temperature. In digital systems, two's complement uses negatives to handle signed integers. In mathematics, the integers — positive, zero, negative — form the foundational number system from which rationals, reals, and complex numbers are built. Without Brahmagupta's formalisation, the edifice of modern mathematics would lack a cornerstone.`,
  },
  {
    id: 'algebra',
    n: 4,
    name: 'Algebra (bījagaṇita)',
    deva: 'बीजगणित',
    seal: 'बी',
    domain: 'math',
    blurb: 'Systematic solving of linear, quadratic, and indeterminate equations.',
    what: `Bīja-gaṇita — 'seed-calculation' — is the branch of mathematics that operates with unknown quantities, represented by symbols, to find their values. Indian algebraists solved linear equations (one unknown), quadratic equations (squared unknowns), and most remarkably, indeterminate Diophantine equations requiring general integer-solution families. The chakravāla ('cyclic') method for solving the Pell equation (Nx² + 1 = y²) is a particularly sophisticated achievement — a general algorithm of great elegance.`,
    when: `Āryabhaṭa (499 CE) employed algebraic reasoning throughout his Āryabhaṭīya. Brahmagupta (628 CE) gave rules for linear and quadratic equations and solved specific Pell equations. Bhāskara II's Bījaganita (1150 CE) is a systematic algebraic textbook; his chakravāla solved Pell's equation in full generality — a result European mathematicians (Euler, Lagrange) did not match until the 18th century. The word 'algebra' derives from al-jabr in al-Khwārizmī's 9th-century Arabic work, which built directly on Indian methods.`,
    how: `Algebra is the language of modern science and engineering. Every equation in physics, every formula in chemistry, every algorithm in computer science is algebraic. Cryptographic systems, financial models, machine learning, database queries — all depend on solving for unknowns. The Pell equation solved by Bhāskara's chakravāla arises in modern number theory and public-key cryptography. The symbolic reasoning formalised in bīja-gaṇita became, through the European Renaissance, the abstract algebra — groups, rings, fields — that underlies all of modern mathematics.`,
  },
  {
    id: 'trigonometry',
    n: 5,
    name: 'Trigonometry',
    deva: 'ज्या',
    seal: 'ज्',
    domain: 'math',
    blurb: 'The sine function (jyā) originates in India and reached Europe via Arabic translation; the word "sine" is a mistranslation of jyā.',
    debated: true,
    what: `Indian astronomers developed the sine function — which they called jyā (half-chord) — as a tool for calculating angles and distances in astronomical problems. They computed detailed tables of jyā values at precise intervals, and also defined the cosine (kojyā) and versine (utkrama-jyā). This differs from Greek chord-based trigonometry: where Greek astronomers worked with full chords, Indians worked with half-chords — the form modern trigonometry uses. The half-chord approach is more elegant and computationally convenient.`,
    when: `The earliest Indian sine tables appear in Āryabhaṭa's Āryabhaṭīya (499 CE), giving 24 values at intervals of 3°45'. Brahmagupta (628 CE) improved interpolation methods. The term travelled west: the Arab scholar al-Battānī (c. 920 CE) adopted the Indian half-chord method; Arab translators rendered jyā as jaib (fold), which Latin scholars mistranslated as sinus (cavity), giving us the English word 'sine.' Most historians of mathematics accept the Indian origin of the sine function; the extent of its influence on later European mathematics is debated.`,
    how: `Trigonometry is fundamental to navigation (position from angles), architecture (roof pitches, bridge stresses), physics (wave mechanics, oscillations, alternating current), computer graphics (3D rendering, rotation matrices), signal processing (Fourier transforms), and GPS. Every wave in physics — sound, light, radio — is described by sine and cosine functions. The documented chain from India through Arabic translation to European mathematics is one of the clearest cases of mathematical knowledge transmission across cultures.`,
  },
  {
    id: 'calculus',
    n: 6,
    name: 'Early calculus ideas',
    deva: 'माधव श्रेणी',
    seal: 'म',
    domain: 'math',
    blurb: 'The Mādhava–Kerala school (14th–16th c.) developed infinite series for sine, cosine, and arctangent centuries before Newton and Leibniz.',
    debated: true,
    what: `The Kerala school of mathematics made discoveries in infinite series formally equivalent to results attributed centuries later to Newton and Leibniz. Mādhava of Saṅgamagrāma (c. 1340–1425 CE) derived power series for the sine, cosine, and arctangent functions, and a series for π now called the Mādhava-Leibniz-Gregory series. He also developed correction terms (end-corrections) that dramatically accelerated convergence — a technique at the frontier of modern numerical analysis. His student Nīlakaṇṭha Somayāji developed concepts approaching the notion of a derivative.`,
    when: `Mādhava's results date to the late 14th century. They were recorded and proved in the Yuktibhāṣā (c. 1530 CE) by Jyeṣṭhadeva — one of the earliest systematic treatises proving mathematical results step by step. Newton published his calculus in the 1660s–1680s, Leibniz in the 1670s — 200–300 years after Mādhava. Whether Kerala results were transmitted to Europe via Jesuit missionaries active in Kerala from the 1540s is a contested but seriously debated historical hypothesis; the mathematical priority for the series themselves is clear.`,
    how: `Calculus — limits, derivatives, integrals, and infinite series — is the mathematical engine of modern science and engineering. It describes motion, growth, decay, waves, heat, and electricity. Whether or not the Kerala school's results influenced Europe, they demonstrate that the conceptual breakthrough of infinite series was achieved in India independently and earlier. The Mādhava-Leibniz series for π is taught in calculus courses worldwide today — and it was Mādhava who first derived it.`,
  },
  {
    id: 'pi',
    n: 7,
    name: 'Accurate values of π',
    deva: 'π मूल्य',
    seal: 'π',
    domain: 'math',
    blurb: "From Āryabhaṭa's 3.1416 to Mādhava's rapidly converging series.",
    what: `π is the ratio of a circle's circumference to its diameter — approximately 3.14159265. Indian mathematicians computed increasingly accurate values and, in the Kerala school, derived an infinite series that converges to π. Āryabhaṭa described a procedure yielding 62,832/20,000 = 3.1416 and explicitly noted this value is āsanna (approximate) — a remarkable meta-mathematical awareness. Mādhava's series π/4 = 1 − 1/3 + 1/5 − 1/7 + ⋯, together with correction terms, allowed computation to 11 decimal places.`,
    when: `Āryabhaṭa's value (3.1416) appears in the Āryabhaṭīya (499 CE). Earlier, the Śulba Sūtras (c. 800–500 BCE) used approximations near 3.09 for altar construction. Mādhava (c. 1400 CE) derived the infinite series and correction terms. This series was rediscovered in Europe by James Gregory (1671) and Leibniz (1673) — hence it is often called the 'Leibniz formula for π', even though Mādhava preceded both by roughly 250 years. Brahmagupta (628 CE) also used √10 ≈ 3.162 as a convenient approximation.`,
    how: `π appears in the formula for every circle, sphere, cylinder, and cone; in Fourier series describing wave patterns; in the Gaussian curve of statistics; in Heisenberg's uncertainty principle; and in Euler's identity e^(iπ) + 1 = 0. Engineers use π in designing gears, wheels, tunnels, and pipelines. Computer scientists use its computation to benchmark high-precision arithmetic. The Kerala school's rapidly converging series and correction terms for π represent genuine mathematical innovation that remains part of the living heritage of numerical analysis.`,
  },
  {
    id: 'binary-combinatorics',
    n: 8,
    name: 'Binary numbers and combinatorics',
    deva: 'मेरु प्रस्तार',
    seal: 'पि',
    domain: 'math',
    blurb: "Piṅgala's prosody used a binary system and produced the Meru sequence (Fibonacci numbers) and Pascal's triangle long before their European namesakes.",
    what: `Piṅgala's Chandaḥśāstra (a manual of Sanskrit prosody) developed binary notation to classify poetic metres: each syllable is either long (guru, encoded as 1) or short (laghu, encoded as 0). To count possible metres of a given length, Piṅgala derived what we now call Pascal's triangle (the Meru prastāra — 'mountain arrangement'), and he observed the sequence now called Fibonacci numbers in the context of counting mixed metres. This is mathematics arising from literary analysis — an origin as unlikely as it is consequential.`,
    when: `Piṅgala's Chandaḥśāstra is dated to approximately the 3rd–2nd century BCE. The Meru prastāra is described by Halāyudha (c. 975 CE) as an elaboration of Piṅgala. Pascal published his triangle in 1654 CE — roughly 1,600–2,000 years after the Indian version. The Fibonacci sequence, named for Leonardo Fibonacci (1202 CE), appears explicitly in the work of Virahāṅka (c. 600–800 CE) and Gopāla (before 1135 CE). Leibniz developed binary arithmetic in 1679 CE, over 1,800 years after Piṅgala's binary representation of metres.`,
    how: `Binary notation is the foundation of all digital computing — every bit stored or transmitted in computers, smartphones, and networks uses it. Pascal's triangle appears in the binomial theorem, probability, and combinatorics. The Fibonacci sequence appears in plant growth patterns (phyllotaxis), shell spirals, financial market analysis, and computer algorithm design (Fibonacci heaps and search algorithms). Piṅgala's prosodic mathematics — born to analyse poetry — has had consequences that reach into every electronic device in the modern world.`,
  },
  {
    id: 'sulba-sutras',
    n: 9,
    name: 'The geometry of the Śulba Sūtras',
    deva: 'शुल्बसूत्र',
    seal: 'शु',
    domain: 'math',
    blurb: 'Practical theorems — including the "Pythagorean" relation — for precise altar construction.',
    what: `The Śulba Sūtras ('Rules of the cord') are ancient Sanskrit texts giving geometric instructions for constructing precisely shaped Vedic fire altars (agnikuṇḍa). They contain an independent discovery of the relationship now called the Pythagorean theorem: the square on the diagonal of a rectangle equals the sum of the squares on its two sides. They also give a method for constructing a square equal in area to a given circle, approximate √2 to five decimal places (1.41421...), and show how to add and subtract areas by constructing equivalent squares.`,
    when: `The four principal texts — Baudhāyana, Āpastamba, Kātyāyana, and Mānava Śulba Sūtras — are dated to approximately 800–500 BCE. Baudhāyana's is the oldest and states the diagonal theorem explicitly: 'the diagonal of a rectangle produces both areas which the length and the breadth produce separately.' This predates Pythagoras of Samos (c. 570–495 BCE), though whether there was any contact between the traditions cannot be determined. The purpose was entirely practical — ritual precision required genuine mathematical innovation.`,
    how: `The Pythagorean theorem is among the most used mathematical results in human history, underlying trigonometry, Euclidean geometry, the distance formula in coordinate geometry, the inner product of vectors in linear algebra, and the metric tensor in general relativity. Every architect, surveyor, engineer, and navigator applies it constantly. The Śulba Sūtras' approximation of √2 to five decimal places reflects a level of numerical precision remarkable for the 1st millennium BCE. Their blend of practical necessity and geometric sophistication is a model of applied mathematical thinking.`,
  },
  {
    id: 'infinity',
    n: 10,
    name: 'Comfort with the infinite and the very large',
    deva: 'अनन्त',
    seal: 'अ',
    domain: 'math',
    blurb: 'A distinctive Indian intellectual habit, with named units running to staggering magnitudes.',
    what: `Indian mathematical and philosophical traditions developed an extraordinary ease with very large numbers and with multiple levels of infinity. Where Greek mathematics was often uncomfortable with actual infinity (Aristotle rejected it), Indian traditions — especially Jain mathematics — treated the infinite as a legitimate object of rigorous inquiry. Jain texts developed a formal taxonomy of infinities: numerable (saṃkhyāta), innumerable (asaṃkhyāta, in three grades), and truly infinite (ananta, in four grades). This is formal classification, not merely philosophical speculation.`,
    when: `Jain canonical texts (c. 300 BCE–200 CE) contain the earliest systematic treatment. The Lalitavistara Sūtra (c. 1st c. CE) describes a counting contest with numbers reaching 10^421. Hindu cosmological texts use the mahāyuga (4.32 million years) and kalpa (4.32 billion years) as standard units. Āryabhaṭa (499 CE) operated freely with very large astronomical numbers. The Jain mathematician Mahāvīrācārya (850 CE) elaborated the taxonomy of large numbers and infinities in his Gaṇitasārasaṅgraha.`,
    how: `Modern mathematics requires careful reasoning about infinity: limits in calculus, convergence of series, measure theory, and Cantor's transfinite cardinals (ℵ₀, ℵ₁, ...) all demand technical precision about the infinite. The Indian tradition's familiarity with infinity as a legitimate concept — and its classification of types of infinity — is a remarkable intellectual precursor to Cantor's 19th-century mathematics. In cosmology, the age of the universe (approximately 13.8 billion years) fits comfortably within the Hindu cosmological time scale — a coincidence reflecting how seriously Indian thinkers engaged with temporal scale.`,
  },
  {
    id: 'atom',
    n: 11,
    name: 'The atom (aṇu / paramāṇu)',
    deva: 'परमाणु',
    seal: 'अ',
    domain: 'math',
    blurb: "Kaṇāda's Vaiśeṣika school theorized indivisible particles combining to form matter.",
    what: `The Vaiśeṣika school, founded by Kaṇāda (c. 2nd c. BCE–1st c. CE), proposed that all physical matter is composed of eternal, indivisible, imperceptibly small particles called paramāṇu (para = beyond, aṇu = minute). Atoms of different elements — earth, water, fire, air — possess different qualities. Two atoms combine to form a dyad (dvyaṇuka); three dyads form a triad (tryaṇuka), the smallest perceptible unit; larger aggregates form all visible matter. Space, time, mind, and soul are also regarded as fundamental but non-atomic categories.`,
    when: `Kaṇāda's Vaiśeṣika Sūtra is dated to the 2nd century BCE–1st century CE, broadly contemporary with Greek atomism (Leucippus, Democritus, c. 5th c. BCE) but apparently independent — there is no evidence of direct contact at this early period. The system was elaborated by Praśastapāda (c. 4th–5th c. CE) and integrated with the Nyāya school of logic. Buddhist atomism (paramāṇuvāda) developed a parallel tradition in which atoms are momentary rather than eternal.`,
    how: `The Vaiśeṣika theory was philosophical and qualitative, not empirical in the modern sense, and differs in its details from modern atomic physics. Its significance is the central intellectual move: that the complexity of the visible world arises from the combination of simple, indivisible units — the reductionist hypothesis that drives all of modern physical science. The word paramāṇu is now the standard Hindi and Sanskrit term for 'atom', making this an unbroken linguistic and conceptual thread. The parallel development of atomic thinking in India and Greece points to a universal human intellectual tendency toward this kind of explanation.`,
  },
  {
    id: 'nyaya-logic',
    n: 12,
    name: 'Formal logic (Nyāya)',
    deva: 'न्याय',
    seal: 'न्',
    domain: 'math',
    blurb: 'A rigorous epistemology with the five-membered syllogism and a theory of valid means of knowledge (pramāṇa).',
    what: `The Nyāya school is distinguished among Indian philosophical systems by its rigorous analysis of logic, epistemology, and argumentation. Its five-membered syllogism (pañcāvayava-vākya) gives a structured form for valid inference: thesis (pratijñā), reason (hetu), example with universal rule (udāharaṇa), application (upanaya), and conclusion (nigamana). The school also articulates four valid means of knowledge (pramāṇas): perception (pratyakṣa), inference (anumāna), analogy (upamāna), and testimony (śabda) — a comprehensive epistemology that remains philosophically active today.`,
    when: `Akṣapāda Gautama's Nyāya Sūtras are dated to approximately the 2nd century BCE–2nd century CE. They were elaborated by Vātsyāyana (c. 450 CE), Udyotakara (c. 6th c.), and Vācaspatimiśra (c. 9th c.). The New Logic (Navya-Nyāya) school, beginning with Gaṅgeśa's Tattvacintāmaṇi (c. 1325 CE), developed a highly formalised technical language for representing logical relations. 20th-century scholars — B.K. Matilal, D.H.H. Ingalls, J.F. Staal — demonstrated that Navya-Nyāya's formal language is comparable in power to modern predicate logic.`,
    how: `The Nyāya analysis of valid inference — distinguishing sound arguments from fallacies, articulating the structure of reasoning — is a contribution to the theory of rationality with parallels across human cultures. Navya-Nyāya's formal language for expressing complex relational propositions has been compared to first-order predicate calculus; its treatment of 'absence' (abhāva) as a category anticipates negation-as-failure in logic programming. Indian logical traditions also deeply influenced Buddhist and Jain logic that spread across Asia. In AI and cognitive science, the analysis of knowledge sources (pramāṇas) connects to current work on knowledge representation and epistemic logic.`,
  },
  {
    id: 'many-valued-logic',
    n: 13,
    name: 'Many-valued logic (anekāntavāda / syādvāda)',
    deva: 'अनेकान्तवाद',
    seal: 'अ',
    domain: 'math',
    blurb: 'The Jain doctrine of "many-sidedness" — an early framework for pluralism, tolerance, and reasoning under partial truth.',
    what: `Jain philosophy developed anekāntavāda ('the doctrine of many-sidedness') as a theory of knowledge: reality is complex and many-faceted; any single description captures at most a partial truth. Its formal expression is syādvāda ('conditioned predication'), which uses the prefix syāt ('in some respect') to qualify each claim. The saptabhaṅgī (seven-fold predication) lists all possible qualified claims about any object: 'in some respect it is,' 'in some respect it is not,' 'in some respect it both is and is not,' 'in some respect it is indescribable,' and four combinations — a formal seven-valued logic.`,
    when: `Anekāntavāda is attributed to Mahāvīra (c. 599–527 BCE). The saptabhaṅgī was developed by Jain logicians including Samantabhadra (c. 2nd–4th c. CE), Akalaṅka (c. 720–780 CE), Hemacandra (1088–1172 CE), and Mallisheṇa (1292 CE). The tradition remained active through the medieval period and attracted renewed scholarly attention in the 20th century when logicians recognised structural similarities to non-classical logics developed in the West.`,
    how: `Anekāntavāda is a formal framework for reasoning about incomplete and context-dependent information — a problem central to modern AI, database systems, and legal reasoning. Many-valued logics (Łukasiewicz, 1920), fuzzy logic (Zadeh, 1965), and paraconsistent logics (da Costa, 1963) share the core insight that classical two-valued logic is insufficient for real-world reasoning. Fuzzy logic is widely used in consumer electronics, control systems, and medical diagnostics. Philosophically, anekāntavāda provides a rigorous foundation for intellectual tolerance — the recognition that no single perspective has a monopoly on truth.`,
  },

  // ── Astronomy & Time ──────────────────────────────────────────────────────
  {
    id: 'earth-rotation',
    n: 14,
    name: "Earth's daily rotation",
    deva: 'भूभ्रमण',
    seal: 'भ',
    domain: 'astronomy',
    blurb: "Proposed by Āryabhaṭa (5th c.), who compared it to a boat traveller seeing the riverbank move.",
    what: `Āryabhaṭa proposed that the apparent daily motion of the stars across the sky is caused not by the heavens revolving around a stationary Earth, but by the Earth itself rotating on its axis. He captured the relativity of the observation with a striking image: just as a person travelling in a boat sees the trees on the riverbank appear to move backwards, so a person on the rotating Earth sees the fixed stars appear to move westward. This was a radical departure from the geocentric intuition that dominated almost all ancient astronomy.`,
    when: `Āryabhaṭa stated this in the Āryabhaṭīya (499 CE), composed when he was just 23. The idea was controversial even in India: later astronomers such as Brahmagupta and Varāhamihira rejected it, preferring the stationary Earth of received tradition. In Europe, the rotation of the Earth was not seriously revived until Copernicus (1543 CE) and was only firmly established by Galileo and Newton — over a thousand years after Āryabhaṭa.`,
    how: `Earth's rotation is now elementary science: it causes day and night, governs weather systems through the Coriolis effect, and defines our 24-hour timekeeping. Āryabhaṭa's boat analogy is an early articulation of the principle of relativity of motion — the recognition that motion can only be described relative to a reference frame. India's first satellite, launched in 1975, was named Āryabhaṭa in his honour.`,
  },
  {
    id: 'eclipses',
    n: 15,
    name: 'Eclipses by shadow, not myth',
    deva: 'ग्रहण',
    seal: 'ग्',
    domain: 'astronomy',
    blurb: 'A correct geometric cause for solar and lunar eclipses.',
    what: `Indian astronomers gave a correct geometric explanation of eclipses: a lunar eclipse occurs when the Earth's shadow falls on the Moon, and a solar eclipse occurs when the Moon passes between the Earth and the Sun. This displaced mythological explanations — such as the demon Rāhu swallowing the Sun or Moon — with a model based on the relative positions and shadows of celestial bodies. From this geometry they could predict the timing, duration, and extent of eclipses in advance.`,
    when: `Āryabhaṭa (499 CE) clearly stated the shadow theory of eclipses in the Āryabhaṭīya, and Brahmagupta (628 CE) and later astronomers refined the calculations. Remarkably, the astronomers retained the names Rāhu and Ketu for the lunar nodes — the two points where the Moon's orbit crosses the Sun's apparent path — where eclipses can occur, thus reconciling the older vocabulary with the new geometric understanding. These methods were so reliable that the pañchāṅga calendars listed eclipses years in advance.`,
    how: `The geometric understanding of eclipses is exactly what modern astronomy uses, refined with precise orbital mechanics. NASA can now predict eclipses thousands of years into the future and past using the same fundamental geometry. The ability to predict eclipses was, historically, one of the clearest demonstrations that the cosmos follows discoverable mathematical laws rather than the whims of deities — a turning point in the human relationship with nature.`,
  },
  {
    id: 'solar-year',
    n: 16,
    name: 'Highly accurate solar/sidereal year',
    deva: 'सौरवर्ष',
    seal: 'स',
    domain: 'astronomy',
    blurb: 'Within minutes of the modern value.',
    what: `Indian astronomers measured the length of the year — the time the Sun takes to return to the same position — with extraordinary accuracy, arriving at values within minutes of the modern measurement. The sidereal year (relative to the fixed stars) and the tropical year (relative to the seasons) were both computed. This precision required careful long-term observation and sophisticated mathematical methods for handling fractional remainders.`,
    when: `Āryabhaṭa (499 CE) gave a year length of 365 days, 6 hours, 12 minutes, 30 seconds — within a few minutes of the true sidereal year of about 365 days, 6 hours, 9 minutes. Brahmagupta and the later Sūrya Siddhānta tradition refined these figures. For comparison, the Julian calendar adopted in Rome (45 BCE) used 365.25 days, an error that accumulated to ten full days by the 16th century, forcing the Gregorian reform of 1582.`,
    how: `An accurate year length is the foundation of any calendar that stays aligned with the seasons over centuries. The Indian figures rival those used in the much later Gregorian reform. The traditional Indian calendars built on these measurements still successfully predict solstices, equinoxes, and seasonal festivals today. Precise determination of the year remains essential for agriculture, navigation, and the leap-year rules that keep modern calendars accurate.`,
  },
  {
    id: 'circumference-planets',
    n: 17,
    name: "Earth's circumference and planetary positions",
    deva: 'भूपरिधि',
    seal: 'पृ',
    domain: 'astronomy',
    blurb: 'Computed with impressive precision.',
    what: `Indian astronomers computed the circumference of the Earth and the positions and periods of the planets with impressive precision, treating the Earth as a sphere. They calculated planetary orbital periods, the inclinations of orbits, and methods to predict where each planet would appear in the sky on any given date. These computations underpinned the predictive almanacs that Indian astronomy is known for.`,
    when: `Āryabhaṭa (499 CE) gave the Earth's circumference as 4,967 yojanas; using the most widely accepted yojana of about 8 km, this works out to roughly 39,700 km — astonishingly close to the true value of about 40,075 km, an error of under one percent. Brahmagupta (628 CE) and Bhāskara II (1150 CE) extended and refined the planetary models. These results were achieved purely through geometry and observation, without telescopes.`,
    how: `Earth's circumference is fundamental to cartography, navigation, satellite orbits, and global positioning. Āryabhaṭa's value, accurate to within one percent, demonstrates the power of careful mathematical astronomy long before modern instruments. The planetary computation methods are direct ancestors of the ephemeris tables still used (now computer-generated) by astronomers, navigators, and space agencies to locate celestial bodies.`,
  },
  {
    id: 'panchanga',
    n: 18,
    name: 'The pañchāṅga',
    deva: 'पञ्चांग',
    seal: 'प',
    domain: 'astronomy',
    blurb: 'A luni-solar calendar still governing agriculture and festivals across India.',
    what: `The pañchāṅga ('five limbs') is the traditional Indian luni-solar calendar, combining the cycles of both the Sun and the Moon. Its five components are the tithi (lunar day), vāra (weekday), nakṣatra (lunar mansion), yoga (a Sun–Moon angular combination), and karaṇa (half a tithi). Together these give a precise framework for reckoning time, fixing festivals, and choosing auspicious moments. The calendar reconciles the lunar month (about 29.5 days) with the solar year through the periodic insertion of an extra month (adhika māsa).`,
    when: `The roots of the pañchāṅga lie in the Vedāṅga Jyotiṣa (c. 1400–1200 BCE), the earliest Indian astronomical text, and the system was placed on a rigorous mathematical footing by the Siddhānta astronomers — Āryabhaṭa, Brahmagupta, and the Sūrya Siddhānta tradition — in the first millennium CE. Regional variants (such as the Amānta and Pūrṇimānta reckonings) developed across India. The pañchāṅga has been continuously computed and published for well over two thousand years.`,
    how: `The pañchāṅga still governs the dates of virtually every Hindu festival — Diwali, Holi, Navarātri, and countless others — and is consulted across India for agriculture, marriage dates, and ritual timing. Modern pañchāṅgas are computed with the same astronomical principles, now using software, and are available as smartphone apps used by millions. It is one of the world's oldest calendrical systems in continuous practical use.`,
  },
  {
    id: 'nakshatras',
    n: 19,
    name: 'The nakṣatra system',
    deva: 'नक्षत्र',
    seal: 'न',
    domain: 'astronomy',
    blurb: '27 lunar mansions for timekeeping and celestial navigation.',
    what: `The nakṣatras are 27 (sometimes 28) divisions of the ecliptic — the band of sky through which the Sun, Moon, and planets appear to move — each marked by a recognisable star or asterism. The Moon passes through roughly one nakṣatra per day, so the system functions as a celestial clock and calendar, tracking the Moon's nightly position. Each nakṣatra spans 13°20′ of the sky and carries its own name, presiding deity, and associations.`,
    when: `The nakṣatras are named in the Ṛgveda and listed systematically in the Yajurveda and the Vedāṅga Jyotiṣa (c. 1400–1200 BCE), making them among the oldest astronomical reference systems in continuous use anywhere. Similar lunar-mansion systems exist in Chinese (xiu) and Arabic (manāzil) astronomy, raising long-debated questions of independent origin versus transmission. In India the system has been used without interruption for over three thousand years.`,
    how: `The nakṣatras remain central to the pañchāṅga, to the timing of festivals, and to traditional naming customs — a child's syllable is often chosen by the nakṣatra of their birth. As a practical system for tracking the Moon's position against the fixed stars, it represents sophisticated naked-eye astronomy. The 27-fold division of the ecliptic is a genuine astronomical coordinate system, and the nakṣatra names still label regions of the real sky studied by astronomers today.`,
  },
  {
    id: 'cosmic-time',
    n: 20,
    name: 'Cosmic time scales (yuga, kalpa)',
    deva: 'युग कल्प',
    seal: 'यु',
    domain: 'astronomy',
    blurb: 'Units spanning from the truṭi (a fraction of a second) to billions of years.',
    what: `Indian cosmology developed a hierarchy of time units of breathtaking range, from the truṭi — a tiny fraction of a second — up to the kalpa, a 'day of Brahmā' spanning 4.32 billion years, and beyond to the lifespan of the universe over many such days. The yuga cycle (a mahāyuga of 4.32 million years, divided into four ages) and the kalpa give a structured, quantified model of cosmic time. This is time measured not in thousands of years but in billions — a scale unmatched in any other ancient culture.`,
    when: `These time scales appear in the Purāṇas and in the astronomical Siddhāntas of the first millennium CE, with the framework already present in earlier Vedic and epic literature. Āryabhaṭa and the Sūrya Siddhānta gave the figures precise mathematical form. By contrast, most contemporaneous cultures conceived of the world as only thousands of years old — a view that persisted in parts of Europe into the modern era.`,
    how: `The Indian kalpa of 4.32 billion years is remarkably close in order of magnitude to the actual age of the Earth (about 4.54 billion years), and the cosmic cycles approach the timescales of modern cosmology (the universe is about 13.8 billion years old). While the match is not exact and the framework is cosmological rather than empirical, the willingness to think in billions of years prepared the Indian imagination for the deep-time perspective that modern geology and astrophysics require. Carl Sagan famously noted that Hindu cosmology is the only ancient tradition whose time scales correspond to those of modern scientific cosmology.`,
  },
  {
    id: 'cyclical-time',
    n: 21,
    name: 'A cyclical model of time',
    deva: 'चक्रीय काल',
    seal: 'च',
    domain: 'astronomy',
    blurb: 'A mental frame that encourages patience, perspective, and long-term thinking.',
    what: `Indian thought conceives of time as fundamentally cyclical rather than strictly linear: ages (yugas) succeed one another and then recur, universes arise, endure, dissolve, and arise again. This contrasts with the linear, once-only model of time common in Western traditions. The cyclical view frames every event within vast recurring rhythms, encouraging a long perspective in which present difficulties are temporary phases of a larger pattern.`,
    when: `The cyclical model is woven throughout Vedic, Purāṇic, and epic literature, and is formalised in the yuga and kalpa cycles of the astronomical Siddhāntas. It is shared, with variations, across the Hindu, Buddhist, and Jain traditions. The idea is among the oldest and most distinctive features of Indian thought, present from the earliest layers of the tradition.`,
    how: `A cyclical conception of time fosters patience, equanimity, and long-term thinking — psychological resources increasingly valued today, from sustainability planning to personal resilience. It resonates with cyclical patterns recognised in modern science: oscillating-universe cosmological models, the carbon and water cycles, ecological succession, and the recurrence of climate cycles. As a cultural mental frame, it offers a counterweight to short-term thinking, situating human action within rhythms far larger than a single lifetime.`,
  },
  {
    id: 'jantar-mantar',
    n: 22,
    name: 'Astronomical instruments',
    deva: 'यन्त्र',
    seal: 'य',
    domain: 'astronomy',
    blurb: 'Culminating in the monumental Jantar Mantar observatories.',
    what: `Indian astronomers built and used a rich array of observational instruments — the gnomon (śaṅku) for measuring shadows, the armillary sphere (golayantra) modelling the celestial sphere, water clocks, sighting tubes, and graduated arcs — to measure time, angles, and celestial positions. This instrumental tradition culminated in the monumental Jantar Mantar observatories, masonry instruments built on an architectural scale to achieve unprecedented precision with the naked eye.`,
    when: `Instrument-making is described in texts from the Siddhānta period onward, with Bhāskara II (1150 CE) devoting a chapter to astronomical instruments in his Siddhānta Śiromaṇi. The five Jantar Mantar observatories were built by Mahārāja Sawai Jai Singh II between 1724 and 1735 CE at Jaipur, Delhi, Ujjain, Mathura, and Varanasi. The Jaipur observatory houses the Samrāṭ Yantra, a giant sundial about 27 metres tall that tells local time to an accuracy of about two seconds.`,
    how: `The Jantar Mantar observatories still stand and function; the Jaipur site is a UNESCO World Heritage Site visited by scientists and travellers from around the world. They demonstrate how far precision astronomy could advance through scale and geometry alone, before the telescope was widely adopted in India. The instruments remain working teaching tools for understanding solar time, declination, and the coordinates of celestial bodies — a bridge between ancient observational methods and modern astronomy.`,
  },

  // ── Medicine & Physical Health ────────────────────────────────────────────
  {
    id: 'preventive-medicine',
    n: 23,
    name: 'Preventive, holistic medicine',
    deva: 'स्वास्थ्यरक्षण',
    seal: 'स्',
    domain: 'medicine',
    blurb: 'Health defined as balance, not merely the absence of disease.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'sushruta-surgery',
    n: 24,
    name: "Suśruta's surgery",
    deva: 'शल्यतंत्र',
    seal: 'श',
    domain: 'medicine',
    blurb: 'Cataract operations, rhinoplasty (skin-graft nose reconstruction), and ~300 procedures with 120 instruments.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'charaka-medicine',
    n: 25,
    name: "Charaka's internal medicine",
    deva: 'चरक',
    seal: 'च',
    domain: 'medicine',
    blurb: "Systematic diagnosis, disease classification, and a physician's code of ethics.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'herbal-pharmacopoeia',
    n: 26,
    name: 'A vast herbal pharmacopoeia',
    deva: 'औषधिकोश',
    seal: 'औ',
    domain: 'medicine',
    blurb: 'Thousands of plant remedies still mined by modern pharmacology — turmeric/curcumin, neem, ashwagandha.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'dinacharya',
    n: 27,
    name: 'Daily and seasonal routines (dinacharyā / ṛitucharyā)',
    deva: 'दिनचर्या',
    seal: 'दि',
    domain: 'medicine',
    blurb: 'Practical rhythms aligning life with the body clock — strikingly close to modern circadian science.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'food-as-medicine',
    n: 28,
    name: 'Food as medicine',
    deva: 'आहार',
    seal: 'अ',
    domain: 'medicine',
    blurb: 'Diet personalized to constitution; the idea that what you eat is treatment.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'agni-digestion',
    n: 29,
    name: 'Metabolism and digestion (agni)',
    deva: 'अग्नि',
    seal: 'अ',
    domain: 'medicine',
    blurb: 'Digestive "fire" as the hinge of health.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'marma-points',
    n: 30,
    name: 'Marma points',
    deva: 'मर्म',
    seal: 'म',
    domain: 'medicine',
    blurb: 'Mapped vital points — the basis of therapeutic bodywork.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'variolation',
    n: 31,
    name: 'Variolation against smallpox',
    deva: 'टीकाकरण',
    seal: 'टी',
    domain: 'medicine',
    debated: true,
    blurb: 'Early inoculation practices (documented, though scale and origins are debated).',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'rasashastra',
    n: 32,
    name: 'Rasaśāstra (alchemical chemistry)',
    deva: 'रसशास्त्र',
    seal: 'र',
    domain: 'medicine',
    blurb: 'Purification and medicinal use of metals and minerals; early chemical processing.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Psychology & the Mind ─────────────────────────────────────────────────
  {
    id: 'yoga-eight-limbs',
    n: 33,
    name: "Yoga's eight limbs (Patañjali)",
    deva: 'अष्टांग योग',
    seal: 'यो',
    domain: 'mind',
    blurb: 'A complete operating manual for training attention and the mind.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'meditation',
    n: 34,
    name: 'Meditation (dhyāna)',
    deva: 'ध्यान',
    seal: 'ध्',
    domain: 'mind',
    blurb: 'Now clinically validated for stress, focus, and emotional health.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'pranayama',
    n: 35,
    name: 'Breath regulation (prāṇāyāma)',
    deva: 'प्राणायाम',
    seal: 'प्र',
    domain: 'mind',
    blurb: 'Direct, learnable control of the nervous system.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'layered-psyche',
    n: 36,
    name: 'A layered model of the psyche',
    deva: 'अन्तःकरण',
    seal: 'म',
    domain: 'mind',
    blurb: 'Manas (sensory mind), buddhi (intellect), ahaṃkāra (ego), chitta (memory-substrate).',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'mindfulness',
    n: 37,
    name: 'Mindfulness / present-moment awareness',
    deva: 'वर्तमान',
    seal: 'सा',
    domain: 'mind',
    blurb: 'Millennia before it became a wellness industry.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'karma-yoga',
    n: 38,
    name: 'Karma yoga',
    deva: 'कर्मयोग',
    seal: 'क',
    domain: 'mind',
    blurb: 'Acting wholeheartedly while releasing attachment to results — a genuine antidote to anxiety and burnout.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'gunas',
    n: 39,
    name: 'The guṇa framework (sattva / rajas / tamas)',
    deva: 'गुण',
    seal: 'गु',
    domain: 'mind',
    blurb: 'A practical lens for understanding moods, energy, and temperament.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'equanimity',
    n: 40,
    name: 'Equanimity (samatva)',
    deva: 'समत्व',
    seal: 'स',
    domain: 'mind',
    blurb: 'Emotional regulation treated as a trainable skill, not a fixed trait.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'self-inquiry',
    n: 41,
    name: 'Self-inquiry and Vedānta',
    deva: 'आत्मविचार',
    seal: 'आ',
    domain: 'mind',
    blurb: 'Tools for existential anxiety, identity, and the question "Who am I?"',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'yoga-nidra',
    n: 42,
    name: 'Yoga nidrā',
    deva: 'योगनिद्रा',
    seal: 'नि',
    domain: 'mind',
    blurb: 'Structured deep relaxation — ancestor of modern guided relaxation therapy.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── The Body & Physical Practice ─────────────────────────────────────────
  {
    id: 'asanas',
    n: 43,
    name: 'Āsanas',
    deva: 'आसन',
    seal: 'आ',
    domain: 'body',
    blurb: 'Postures for flexibility, strength, and longevity — now practised worldwide.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'surya-namaskar',
    n: 44,
    name: 'Sūrya Namaskāra',
    deva: 'सूर्यनमस्कार',
    seal: 'सू',
    domain: 'body',
    blurb: 'A single flowing sequence that exercises the whole body.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'kalaripayattu',
    n: 45,
    name: 'Martial traditions (Kalaripayattu, etc.)',
    deva: 'कलरिपयट्टु',
    seal: 'क',
    domain: 'body',
    blurb: 'Conditioning, discipline, and body awareness.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'shatkarma',
    n: 46,
    name: 'Yogic purification (ṣaṭkarma) and hygiene practices',
    deva: 'षट्कर्म',
    seal: 'ष',
    domain: 'body',
    blurb: 'Tongue scraping, oil pulling, nasal cleansing — several now studied by dentistry and ENT.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Environment & Sustainable Living ──────────────────────────────────────
  {
    id: 'sacred-groves',
    n: 47,
    name: 'Sacred groves and reverence for nature',
    deva: 'देवराई',
    seal: 'दे',
    domain: 'environment',
    blurb: 'Rivers, trees, and mountains protected by sanctity — among the world\'s earliest conservation systems.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'vrikshayurveda',
    n: 48,
    name: 'Vṛkṣāyurveda',
    deva: 'वृक्षायुर्वेद',
    seal: 'वृ',
    domain: 'environment',
    blurb: 'A science of plant care, grafting, and agriculture.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'organic-farming',
    n: 49,
    name: 'Organic and cow-based farming',
    deva: 'गोआधारित कृषी',
    seal: 'गो',
    domain: 'environment',
    blurb: 'Methods now revisited for soil health and regeneration.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'ahimsa-ecology',
    n: 50,
    name: 'Ahiṃsā extended to ecology',
    deva: 'अहिंसा',
    seal: 'अ',
    domain: 'environment',
    blurb: 'Minimal harm to all living systems as an ethical baseline.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'water-harvesting',
    n: 51,
    name: 'Traditional water harvesting',
    deva: 'जलसंचय',
    seal: 'ज',
    domain: 'environment',
    blurb: 'Stepwells (baolis), tanks, and catchment engineering for arid climates.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'five-elements',
    n: 52,
    name: 'The five elements (pañca-mahābhūta)',
    deva: 'पञ्चमहाभूत',
    seal: 'पं',
    domain: 'environment',
    blurb: 'A worldview of living in conscious harmony with earth, water, fire, air, and space.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'vegetarian-living',
    n: 53,
    name: 'Low-footprint vegetarian living',
    deva: 'शाकाहार',
    seal: 'शा',
    domain: 'environment',
    blurb: 'A dietary tradition increasingly relevant to climate and resource limits.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Language, Arts & Society ──────────────────────────────────────────────
  {
    id: 'panini-grammar',
    n: 54,
    name: "Pāṇini's Aṣṭādhyāyī",
    deva: 'अष्टाध्यायी',
    seal: 'पा',
    domain: 'language',
    blurb: "The world's first formal generative grammar (~5th c. BCE), whose rule-based structure anticipates modern linguistics and computer science.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'phonetics',
    n: 55,
    name: 'The science of phonetics (śikṣā)',
    deva: 'शिक्षा',
    seal: 'शि',
    domain: 'language',
    blurb: 'Speech sounds classified by place and manner of articulation — arguably the most rigorous pre-modern phonetic system.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'raga-natyashastra',
    n: 56,
    name: 'The rāga system and Nāṭyaśāstra',
    deva: 'नाट्यशास्त्र',
    seal: 'रा',
    domain: 'language',
    blurb: 'A deep theory of music, performance, and rasa (aesthetic emotion).',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'mimamsa-hermeneutics',
    n: 57,
    name: 'Hermeneutics (Mīmāṃsā)',
    deva: 'मीमांसा',
    seal: 'मी',
    domain: 'language',
    blurb: 'Sophisticated rules of textual interpretation that influenced Indian jurisprudence.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'panchatantra',
    n: 58,
    name: 'The Pañchatantra',
    deva: 'पञ्चतन्त्र',
    seal: 'पं',
    domain: 'language',
    blurb: 'Fables that travelled across Persia, Arabia, and Europe, shaping world storytelling.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'chess',
    n: 59,
    name: 'Chess (chaturaṅga)',
    deva: 'चतुरंग',
    seal: 'च',
    domain: 'language',
    blurb: 'The ancestor of modern chess.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'arthashastra',
    n: 60,
    name: 'Statecraft and economics (Arthaśāstra)',
    deva: 'अर्थशास्त्र',
    seal: 'अ',
    domain: 'language',
    blurb: "Kauṭilya's treatise on administration, taxation, diplomacy, and intelligence.",
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'vastu',
    n: 61,
    name: 'Vāstu Śāstra',
    deva: 'वास्तुशास्त्र',
    seal: 'वा',
    domain: 'language',
    blurb: 'Principles of spatial design, orientation, and architecture.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Materials, Trade & Technology ─────────────────────────────────────────
  {
    id: 'iron-pillar',
    n: 62,
    name: 'Rust-resistant iron',
    deva: 'लोहस्तम्भ',
    seal: 'ल',
    domain: 'materials',
    blurb: 'The Delhi Iron Pillar has resisted corrosion for over 1,600 years.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'wootz-steel',
    n: 63,
    name: 'Wootz / crucible steel',
    deva: 'उक्क',
    seal: 'इ',
    domain: 'materials',
    blurb: 'The high-carbon steel that became famed "Damascus" blades.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'zinc-distillation',
    n: 64,
    name: 'Zinc distillation',
    deva: 'जस्त',
    seal: 'ज',
    domain: 'materials',
    blurb: 'India pioneered the metallurgy of producing pure zinc.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'sugar',
    n: 65,
    name: 'Crystallized sugar',
    deva: 'शर्करा',
    seal: 'श',
    domain: 'materials',
    blurb: 'Śarkarā gives us the very word "sugar."',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'cotton-indigo',
    n: 66,
    name: 'Cotton cultivation, textiles, and dyeing',
    deva: 'कापूस',
    seal: 'क',
    domain: 'materials',
    blurb: 'Including indigo — a cornerstone of global trade.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'diamonds',
    n: 67,
    name: 'Diamond mining and cutting',
    deva: 'हीरा',
    seal: 'ही',
    domain: 'materials',
    blurb: 'The Golconda mines supplied the world for centuries.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },

  // ── Frameworks for a Happy, Balanced Life ─────────────────────────────────
  {
    id: 'purusharthas',
    n: 68,
    name: 'The Puruṣārthas',
    deva: 'पुरुषार्थ',
    seal: 'पु',
    domain: 'life',
    blurb: 'Four aims of life held in balance: dharma (duty/ethics), artha (prosperity), kāma (pleasure/relationship), mokṣa (freedom). A complete model for a well-rounded life.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'ashrama',
    n: 69,
    name: 'The Āśrama system',
    deva: 'आश्रम',
    seal: 'आ',
    domain: 'life',
    blurb: 'Life organized in stages (learning, householder, withdrawal, renunciation) — an early life-planning framework.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'dharma-ethics',
    n: 70,
    name: 'Dharma as situational ethics',
    deva: 'धर्म',
    seal: 'ध',
    domain: 'life',
    blurb: 'Right action judged by context, role, and consequence rather than rigid rule.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'fasting',
    n: 71,
    name: 'Fasting (upavāsa)',
    deva: 'उपवास',
    seal: 'उ',
    domain: 'life',
    blurb: 'Periodic restraint from food; intermittent fasting is now mainstream nutrition science.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
  {
    id: 'vasudhaiva-kutumbakam',
    n: 72,
    name: 'Vasudhaiva Kuṭumbakam',
    deva: 'वसुधैव कुटुम्बकम्',
    seal: 'वसु',
    domain: 'life',
    blurb: '"The world is one family" — an ethic of universal kinship for a connected, fragile planet.',
    what: 'Detailed account coming in Phase II.',
    when: 'Detailed account coming in Phase II.',
    how: 'Detailed account coming in Phase II.',
  },
];

export const LK_NOTE =
  'Indian civilization produced an extraordinary body of knowledge, but knowledge rarely belongs to one culture alone. ' +
  'Several discoveries below arose in parallel elsewhere too, and a few popular claims are debated by historians. ' +
  'Where that is the case, it is flagged. The aim here is intellectual respect, not exaggeration — the contributions are remarkable enough without inflation.';
