// Detail content for each section page.
// All copy is original synthesis for an educational platform.

export type Shloka = { deva: string; trans: string; cite: string };

export type SectionItem = {
  id: string;
  title: string;
  deva: string;
  epithet: string;
  meta: string[];
  summary: string;
  opening?: Shloka;
  facets?: string[];
};

export type SectionDetail = {
  title: string;
  deva: string;
  crumb: string[];
  lede: string;
  layout: 'tabs' | 'grid' | 'primer';
  items?: SectionItem[];
};

export const SECTION_DETAILS: Record<string, SectionDetail> = {

  // ──────────────────────────────────────────────────────── Upavedas
  upavedas: {
    title: 'The Upavedas',
    deva: 'उपवेदाः',
    crumb: ['Library', 'Smṛti', 'The Upavedas'],
    lede: 'Four applied sciences — one paired with each principal Veda. Where the Vedas record the rite, the Upavedas record what to do with the rest of life: a body to keep healthy, a polity to defend, a music to make, a building to raise.',
    layout: 'tabs',
    items: [
      {
        id: 'ayurveda',
        title: 'Āyurveda',
        deva: 'आयुर्वेद',
        epithet: 'The science of life',
        meta: ['Paired with Atharvaveda', 'Caraka · Suśruta · Vāgbhaṭa', 'Aṣṭāṅga — eight limbs'],
        summary: 'A complete medical system organised around three doṣas (vāta · pitta · kapha), seven dhātus and the daily and seasonal rhythm of the body. Its surviving compendia — the Caraka-saṃhitā, the Suśruta-saṃhitā, the Aṣṭāṅga-hṛdaya — are still in clinical use.',
        opening: { deva: 'आयुष्कामीयम् — आयुर्वेदयतीत्यायुर्वेदः ।', trans: '“On the desire for life — that which makes life known is Āyurveda.”', cite: 'Caraka-saṃhitā · Sūtrasthāna 1' },
        facets: ['Internal medicine', 'Surgery (śalya)', 'Toxicology', 'Paediatrics', 'Rasāyana · rejuvenation'],
      },
      {
        id: 'dhanurveda',
        title: 'Dhanurveda',
        deva: 'धनुर्वेद',
        epithet: 'The science of arms',
        meta: ['Paired with Yajurveda', 'Bow, sword, mace, war-elephant', 'Defensive yoga'],
        summary: 'The science of weaponry and warfare — archery, swordsmanship, the conduct of a kṣatriya in the field, and the ethics of when and how a war may be fought. Treated in the epics and codified in works like the Dhanurveda-saṃhitā.',
        opening: { deva: 'धनुर्वेदोऽधनुर्वेदः — चतुष्पादोऽयं वेदः ।', trans: '“Dhanurveda — the four-footed Veda — for the bow, the sword, the polearm and the hand.”', cite: 'Vasiṣṭha · Dhanurveda-saṃhitā' },
        facets: ['Archery (dhanurvidyā)', 'Bāhu-yuddha · unarmed combat', 'Yuddha-dharma'],
      },
      {
        id: 'gandharvaveda',
        title: 'Gāndharvaveda',
        deva: 'गान्धर्ववेद',
        epithet: 'The science of music',
        meta: ['Paired with Sāmaveda', 'Saṅgīta-ratnākara', 'Nāṭya-śāstra'],
        summary: 'The science of music, dance and dramatic performance — the disciplines descended from the chant of the Sāmaveda. Its surviving treatises are the Nāṭya-śāstra of Bharata and the Saṅgīta-ratnākara of Śāraṅgadeva, ancestors of every later Indian classical tradition.',
        opening: { deva: 'सप्त स्वराः षड्जादयो विज्ञेयाः ।', trans: '“The seven svaras — sa, ri, ga, ma, pa, dha, ni — are to be known.”', cite: 'Nāṭya-śāstra · 28' },
        facets: ['Saṅgīta · music', 'Nṛtya · dance', 'Nāṭya · drama'],
      },
      {
        id: 'sthapatyaveda',
        title: 'Sthāpatyaveda',
        deva: 'स्थापत्यवेद',
        epithet: 'The science of building',
        meta: ['Paired with Ṛgveda', 'Mānasāra · Mayamatam', 'Vāstu-puruṣa-maṇḍala'],
        summary: 'The science of architecture, temple-design, town-planning and sacred geometry. Its texts — the Mānasāra, the Mayamatam, the Samarāṅgaṇa-sūtradhāra — encode the ratios that govern everything from a doorway to a city.',
        opening: { deva: 'वास्तुपुरुषमण्डलं भूमिं विभजति ।', trans: '“The maṇḍala of the vāstu-puruṣa divides the site.”', cite: 'Mānasāra · 7' },
        facets: ['Vāstu-śāstra', 'Śilpa-śāstra', 'Town planning'],
      },
    ],
  },

  // ──────────────────────────────────────────────────────── Vedangas
  vedangas: {
    title: 'The Six Vedāṅgas',
    deva: 'षड्वेदाङ्गानि',
    crumb: ['Library', 'Auxiliary', 'The Six Vedāṅgas'],
    lede: 'The six limbs without which the Veda cannot be read — phonetics, ritual, grammar, etymology, prosody, astronomy. Every limb has its own sūtra literature; together they make the Veda intelligible.',
    layout: 'grid',
    items: [
      { id: 'shiksha', title: 'Śikṣā', deva: 'शिक्षा', epithet: 'The mouth — phonetics', meta: ['Pāṇinīya · Yājñavalkya', '6 vowels · 25 consonants'], summary: 'The science of pronunciation, accent, articulation and recitation. Treats each speech sound — its place of articulation, effort, duration — with a precision unmatched by any other ancient grammar.', facets: ['Mouth of the Veda', 'Vyākaraṇa-companion'] },
      { id: 'kalpa', title: 'Kalpa', deva: 'कल्प', epithet: 'The hand — ritual', meta: ['Śrauta · Gṛhya · Dharma', 'Sūtra literature'], summary: 'The science of ritual procedure — public yajña, household rite and the rules of dharma. The Kalpa-sūtras are among the oldest prose works in any Indo-European language.', facets: ['Śrauta-sūtra', 'Gṛhya-sūtra', 'Dharma-sūtra'] },
      { id: 'vyakarana', title: 'Vyākaraṇa', deva: 'व्याकरण', epithet: 'The face — grammar', meta: ['Pāṇini · Aṣṭādhyāyī', '3,959 sūtras'], summary: 'A complete formal grammar of Sanskrit. Pāṇini’s Aṣṭādhyāyī derives every Sanskrit word from rules — twenty-five centuries before modern formal grammar, and at finer resolution than any of its successors.', facets: ['Generative grammar', 'Pāṇinian model'] },
      { id: 'nirukta', title: 'Nirukta', deva: 'निरुक्त', epithet: 'The ear — etymology', meta: ['Yāska', '5 chapters · 14 sections'], summary: 'The science of word-meaning and derivation. Yāska’s Nirukta organises obscure Vedic terms into a working philological method — the closest classical antiquity ever came to a comparative dictionary.', facets: ['Nighaṇṭu glossary', 'Semantic theory'] },
      { id: 'chandas', title: 'Chandas', deva: 'छन्दस्', epithet: 'The foot — prosody', meta: ['Piṅgala · Chanda-sūtra', '7 vedic metres'], summary: 'The science of metre. Piṅgala’s Chanda-sūtra is the first known systematic treatment of metrical patterns — and contains the earliest description of what is now called Pascal’s triangle and the Fibonacci sequence.', facets: ['Gāyatrī · Anuṣṭubh', 'Combinatorics'] },
      { id: 'jyotisha', title: 'Jyotiṣa', deva: 'ज्योतिष', epithet: 'The eye — astronomy', meta: ['Vedāṅga-jyotiṣa', 'Lagadha · ~1400 BCE'], summary: 'The science of celestial timing — when a rite should be performed. Begins with a luni-solar calendar and the twenty-seven nakṣatras, and grows into a complete astronomy by the classical period.', facets: ['Calendar', 'Nakṣatras · ecliptic', 'Astrology — later'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Upanishads
  upanishads: {
    title: 'The Upaniṣads',
    deva: 'उपनिषदः',
    crumb: ['Library', 'Śruti', 'The Upaniṣads'],
    lede: 'The “sitting-down-near” — late-Vedic dialogues that turn from the outer rite toward the question of the self. Tradition counts 108; ten are conventionally called principal (mukhya). Together they form the source of every later Vedānta school.',
    layout: 'grid',
    items: [
      { id: 'isha', title: 'Īśa', deva: 'ईश', epithet: 'The seer everywhere', meta: ['18 verses', 'Śukla-Yajurveda'], summary: 'The shortest of the principal — eighteen verses on the world “covered by the Lord”, on action without grasping, and on the play of immanence and transcendence.', facets: ['Śānti-mantra', 'Karman & jñāna'] },
      { id: 'kena', title: 'Kena', deva: 'केन', epithet: 'By whom is the mind sent?', meta: ['4 chapters', 'Sāmaveda'], summary: 'A short dialogue on the ground of all faculties — the question “by whom?” pressed until the gods themselves do not know whose strength has just won the battle.', facets: ['Prose + verse', 'Indra & Umā'] },
      { id: 'katha', title: 'Kaṭha', deva: 'कठ', epithet: 'Naciketas and Death', meta: ['2 sections · 6 vallīs', 'Kṛṣṇa-Yajurveda'], summary: 'The boy Naciketas is sent to Yama and asks the secret of what survives. Yama answers in verse — the chariot of the body, the reins of the mind, the path “sharp as the razor’s edge.”', facets: ['Most quoted', 'Source of the Gītā imagery'] },
      { id: 'prashna', title: 'Praśna', deva: 'प्रश्न', epithet: 'Six questions', meta: ['6 questions', 'Atharvaveda'], summary: 'Six seekers approach the sage Pippalāda. Each asks a question; he answers in prose. The breath, the dream, the syllable Aum, and where the self abides while the body sleeps.', facets: ['Pippalāda', 'Q&A form'] },
      { id: 'mundaka', title: 'Muṇḍaka', deva: 'मुण्डक', epithet: 'Higher and lower knowledge', meta: ['3 muṇḍakas', 'Atharvaveda'], summary: 'The famous two-bird simile of the self and the witness, and the line that the modern Indian state took for its motto — satyam eva jayate, “truth alone triumphs.”', facets: ['Two-bird verse', 'State motto'] },
      { id: 'mandukya', title: 'Māṇḍūkya', deva: 'माण्डूक्य', epithet: 'The four states', meta: ['12 verses', 'Atharvaveda'], summary: 'The shortest principal Upaniṣad — twelve verses on the four states of consciousness (waking, dream, sleep, turīya) and the syllable Aum that contains them.', facets: ['Aum · A-U-M', 'Turīya'] },
      { id: 'taittiriya', title: 'Taittirīya', deva: 'तैत्तिरीय', epithet: 'The five sheaths', meta: ['3 vallīs', 'Kṛṣṇa-Yajurveda'], summary: 'Origin of the pañca-kośa model — the five sheaths of the self, from the gross body of food to the bliss-body — and the famous instruction to the departing student: speak truth, do dharma.', facets: ['Annamaya → ānandamaya'] },
      { id: 'aitareya', title: 'Aitareya', deva: 'ऐतरेय', epithet: 'Origin of beings', meta: ['3 chapters', 'Ṛgveda'], summary: 'Cosmogony in three short chapters — the self alone, the act of looking, and the emergence of speech, breath, eye, ear and mind from a single original being.', facets: ['Cosmogony'] },
      { id: 'chandogya', title: 'Chāndogya', deva: 'छान्दोग्य', epithet: 'Sat, the One', meta: ['8 chapters', 'Sāmaveda'], summary: 'Long, narrative, foundational. The dialogues of Uddālaka and Śvetaketu (“tat tvam asi — that thou art”), and the meditation on the syllable Aum that opens every later commentary.', facets: ['Tat tvam asi', 'Source mahāvākya'] },
      { id: 'brihad', title: 'Bṛhad-āraṇyaka', deva: 'बृहदारण्यक', epithet: 'The great forest', meta: ['6 chapters', 'Śukla-Yajurveda'], summary: 'The longest and arguably the deepest — Yājñavalkya and Maitreyī on what survives death, Yājñavalkya in the court of Janaka, the line “neti, neti — not this, not this.”', facets: ['Yājñavalkya', 'Neti neti'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Darshanas (Āstika)
  darshanas: {
    title: 'The Āstika Darśanas',
    deva: 'षड्दर्शनानि',
    crumb: ['Library', 'Smṛti', 'Āstika Darśanas'],
    lede: 'Six orthodox schools of Indic philosophy — orthodox in the technical sense that they accept the authority of the Veda. Paired in three couples, each pair sharing its method and each member countering the other. The classical opposing schools, the Nāstika Darśanas, sit beside them in the library.',
    layout: 'tabs',
    items: [
      { id: 'nyaya', title: 'Nyāya', deva: 'न्याय', epithet: 'The school of logic',
        meta: ['Gautama · Nyāya-sūtras', '16 categories', 'Paired with Vaiśeṣika'],
        summary: 'The school of correct reasoning. Develops a complete theory of inference — five-membered syllogism, fallacies, debate — that became the standard tool of every later Indic argument, ours included.',
        opening: { deva: 'प्रमाण-प्रमेय-संशय-प्रयोजन-दृष्टान्त-सिद्धान्ता…', trans: 'The categories begin with pramāṇa (means of knowledge) and prameya (the knowable) — sixteen in all.', cite: 'Nyāya-sūtra · 1.1.1' },
        facets: ['Inference (anumāna)', 'Five-step syllogism', 'Fallacy theory'] },
      { id: 'vaisheshika', title: 'Vaiśeṣika', deva: 'वैशेषिक', epithet: 'The school of particulars',
        meta: ['Kaṇāda · Vaiśeṣika-sūtras', '7 categories', 'Atomism'],
        summary: 'The first Indian atomism. Reality is six (later seven) categories — substance, quality, action, generality, particularity, inherence — and matter is built from indivisible aṇus, an idea that pre-dates Democritus.',
        opening: { deva: 'अथातो धर्मं व्याख्यास्यामः ।', trans: 'Now therefore, we shall expound dharma.', cite: 'Vaiśeṣika-sūtra · 1.1.1' },
        facets: ['Aṇu — atom', 'Padārtha — categories', 'Naturalist'] },
      { id: 'sankhya', title: 'Sāṅkhya', deva: 'साङ्ख्य', epithet: 'The school of enumeration',
        meta: ['Kapila', '25 tattvas', 'Paired with Yoga'],
        summary: 'The oldest of the six. A strict dualism of puruṣa (consciousness) and prakṛti (nature), with twenty-three intermediate tattvas — the architecture every later Indian school argued with, including the Yoga-sūtras and the Bhagavad-gītā.',
        opening: { deva: 'मूलप्रकृतिरविकृतिः महदाद्याः प्रकृतिविकृतयः सप्त ।', trans: 'Root nature is unchanging; the seven beginning with mahat are both nature and modification.', cite: 'Sāṅkhya-kārikā · 3' },
        facets: ['Puruṣa & prakṛti', 'Three guṇas', 'Twenty-five tattvas'] },
      { id: 'yoga', title: 'Yoga', deva: 'योग', epithet: 'The school of practice',
        meta: ['Patañjali · Yoga-sūtras', '4 pādas · 196 sūtras', 'Aṣṭāṅga — eight limbs'],
        summary: 'The applied counterpart to Sāṅkhya. Patañjali’s 196 sūtras lay out an eight-limbed path from ethics (yama) to absorption (samādhi). “Yogaḥ citta-vṛtti-nirodhaḥ — yoga is the stilling of the modifications of the mind.”',
        opening: { deva: 'योगश्चित्तवृत्तिनिरोधः ॥', trans: 'Yoga is the stilling of the modifications of the mind.', cite: 'Yoga-sūtra · 1.2' },
        facets: ['Aṣṭāṅga', 'Samādhi', 'Iśvara-praṇidhāna'] },
      { id: 'mimamsa', title: 'Pūrva-Mīmāṃsā', deva: 'पूर्व-मीमांसा', epithet: 'The school of exegesis',
        meta: ['Jaimini · Mīmāṃsā-sūtras', 'Ritual-canonical', 'Paired with Vedānta'],
        summary: 'A rigorous theory of how a sentence in the Veda is to be read. Develops a doctrine of dharma derived not from a god but from the eternal authority of the Veda itself — and along the way invents most of Sanskrit semantic theory.',
        opening: { deva: 'अथातो धर्मजिज्ञासा ।', trans: 'Now therefore, the desire to know dharma.', cite: 'Mīmāṃsā-sūtra · 1.1.1' },
        facets: ['Apauruṣeya — unauthored', 'Sentence-meaning', 'Eternal Veda'] },
      { id: 'vedanta', title: 'Vedānta', deva: 'वेदान्त', epithet: 'The end of the Veda',
        meta: ['Bādarāyaṇa · Brahma-sūtras', 'Three streams', 'Advaita · Viśiṣṭādvaita · Dvaita'],
        summary: 'The “end of the Veda” — and, in a different sense, what comes at its end. Three classical streams: Advaita (Śaṅkara, non-dualism), Viśiṣṭādvaita (Rāmānuja, qualified non-dualism) and Dvaita (Madhva, dualism), all reading the same Upaniṣads.',
        opening: { deva: 'अथातो ब्रह्मजिज्ञासा ।', trans: 'Now therefore, the desire to know Brahman.', cite: 'Brahma-sūtra · 1.1.1' },
        facets: ['Brahman & ātman', 'Upaniṣad → Brahma-sūtra → Gītā', 'Three classical commentators'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Agamas
  agamas: {
    title: 'Āgamas & Tantra',
    deva: 'आगमाः · तन्त्रम्',
    crumb: ['Library', 'Tantra', 'Āgamas & Tantra'],
    lede: 'Three vast streams of ritual and esoteric literature — Śaiva, Vaiṣṇava and Śākta — that handed Indic religious life its working manuals. Where Vedic śruti speaks of yajña around the fire, the Āgamas speak of pratimā in the temple, mantra in the mouth, and yantra on the wall.',
    layout: 'tabs',
    items: [
      { id: 'shaiva', title: 'Śaiva-āgama', deva: 'शैव आगम', epithet: 'The Śaiva stream',
        meta: ['28 Śaiva-siddhānta āgamas', 'Kashmir Śaivism', '64 Bhairava-tantras'],
        summary: 'The oldest and best-organised of the three. Two principal sub-streams: the dualist Śaiva-siddhānta of the Tamil south, and the non-dual Trika of Kashmir — whose Spanda and Pratyabhijñā schools form some of the most sophisticated philosophy in the Indic record.',
        opening: { deva: 'चैतन्यमात्मा ॥', trans: '“Consciousness is the self.”', cite: 'Śiva-sūtra · 1.1' },
        facets: ['Trika of Kashmir', 'Pratyabhijñā', 'Temple liturgy'] },
      { id: 'vaishnava', title: 'Vaiṣṇava-āgama', deva: 'वैष्णव आगम', epithet: 'The Vaiṣṇava stream',
        meta: ['Pāñcarātra', 'Vaikhānasa', '108 saṃhitās'],
        summary: 'The Pāñcarātra and Vaikhānasa traditions govern the worship of Viṣṇu — temple iconography, daily ritual, the structure of vimāna and gopura. Most surviving Viṣṇu and Kṛṣṇa temples are run on Pāñcarātra lines.',
        opening: { deva: 'ॐ नमो नारायणाय ॥', trans: '“Aum — salutation to Nārāyaṇa.”', cite: 'Aṣṭākṣara-mantra' },
        facets: ['Pratimā · iconography', 'Mantra & mudrā', 'Aṣṭākṣara'] },
      { id: 'shakta', title: 'Śākta-tantra', deva: 'शाक्त तन्त्र', epithet: 'The Śākta stream',
        meta: ['Śrī-vidyā · Kālī-kula', 'Saundarya-laharī', 'Yantra-centric'],
        summary: 'The worship of the Goddess as ultimate reality — Śakti, the dynamic ground of consciousness. Its central yantra is the Śrī-cakra; its central text-cluster includes the Saundarya-laharī and the Devī-māhātmya.',
        opening: { deva: 'शिवः शक्त्या युक्तो यदि भवति शक्तः प्रभवितुम् ।', trans: 'Śiva, only when joined with Śakti, has the power to act.', cite: 'Saundarya-laharī · 1' },
        facets: ['Śrī-cakra', 'Mantra · yantra · mudrā', 'Daśa-mahāvidyā'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Itihasa
  itihasa: {
    title: 'Itihāsa',
    deva: 'इतिहासः',
    crumb: ['Library', 'Smṛti', 'Itihāsa'],
    lede: 'Itihāsa — literally “thus indeed it was.” Two great narrative encyclopaedias, transmitted as the people’s Veda: the Rāmāyaṇa of Vālmīki and the Mahābhārata of Vyāsa. Between them they contain the Indic theory of dharma in story form.',
    layout: 'tabs',
    items: [
      { id: 'ramayana', title: 'Rāmāyaṇa', deva: 'रामायण', epithet: 'The way of Rāma',
        meta: ['Vālmīki', '24,000 verses', '7 kāṇḍas'],
        summary: 'The earlier of the two — Vālmīki’s ādi-kāvya, the first poem. The story of Rāma’s exile, the abduction of Sītā, the war at Laṅkā, and the return. The Hindu world has retold it ever since: Tulsidās in Avadhī, Kamban in Tamil, the shadow-puppets of Bali, the Ramakien in Thai.',
        opening: { deva: 'तपः स्वाध्यायनिरतं तपस्वी वाग्विदां वरम् ।', trans: 'Devoted to austerity and recitation, the foremost of speakers — to him Vālmīki put the question…', cite: 'Rāmāyaṇa · Bāla-kāṇḍa 1.1' },
        facets: ['Seven kāṇḍas', 'Ādi-kāvya', 'Vālmīki'] },
      { id: 'mahabharata', title: 'Mahābhārata', deva: 'महाभारत', epithet: 'The great Bhārata',
        meta: ['Vyāsa', '1,00,000+ verses', '18 parvas'],
        summary: 'Eight times the size of the Iliad and Odyssey combined. Within it: the war of the Kuru cousins, the entire Bhagavad-gītā, the Anuśāsana-parvan’s catalogue of dharma, the Yakṣa-praśna, and the saying — what is not here is nowhere.',
        opening: { deva: 'यतो धर्मस्ततो जयः ॥', trans: '“Where dharma is, there is victory.”', cite: 'Mahābhārata · Udyoga-parva' },
        facets: ['Bhagavad-gītā', '18 parvans', 'Pañcama-veda'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Lifestyle
  lifestyle: {
    title: 'Dinacaryā & Living',
    deva: 'दिनचर्या',
    crumb: ['Library', 'Practice', 'Dinacaryā & Living'],
    lede: 'How the day is structured — and the week, the season, the lifetime — when the science of life is taken seriously at the scale of a single morning. Four interlocking calendars: the day (dinacaryā), the season (ṛtucaryā), the four ages of a person (āśrama), and the four ends of life (puruṣārtha).',
    layout: 'grid',
    items: [
      { id: 'dinacharya', title: 'Dinacaryā', deva: 'दिनचर्या', epithet: 'The daily rhythm',
        meta: ['Six segments', 'Brāhma muhūrta', 'Doṣa-clock'],
        summary: 'The day divided into six tri-doṣic windows. Wake before sunrise, oil the body, sit, the principal meal at noon, light supper before dusk, sleep before the Pitta hours of the night begin again.',
        facets: ['Wake · 04:30', 'Mid-meal · noon', 'Sleep · 22:00'] },
      { id: 'ritucharya', title: 'Ṛtucaryā', deva: 'ऋतुचर्या', epithet: 'The seasonal rhythm',
        meta: ['Six seasons', 'Ādāna · visarga', 'Doṣa-shift'],
        summary: 'Six Indian seasons, paired into solstice-halves. What to eat, what to wear, when to fast, when to be still — calibrated against the way the body’s doṣas shift over the year.',
        facets: ['Vasanta → Hemanta', 'Six-fold calendar', 'Seasonal diet'] },
      { id: 'ashrama', title: 'Āśrama', deva: 'आश्रम', epithet: 'The four stages of life',
        meta: ['Brahmacarya · Gārhasthya', 'Vānaprastha · Sannyāsa'],
        summary: 'A life sketched in four parts — the student, the householder, the forest-dweller and the renunciate. Each has its own dharma, its own practice, its own measure of success.',
        facets: ['Four stages', 'Sva-dharma', 'Phase-aware'] },
      { id: 'purushartha', title: 'Puruṣārtha', deva: 'पुरुषार्थ', epithet: 'The four ends of life',
        meta: ['Dharma · Artha', 'Kāma · Mokṣa'],
        summary: 'Four legitimate human goals, in order — duty (dharma), prosperity (artha), pleasure (kāma) and liberation (mokṣa). Tradition does not ask anyone to choose only one; it asks they be ordered.',
        facets: ['Four ends', 'Ordering principle'] },
      { id: 'yoga', title: 'Yoga', deva: 'योग', epithet: 'Internal practice',
        meta: ['Aṣṭāṅga', 'Pātañjala', '8 limbs'],
        summary: 'Yoga as the inner counterpart of dinacaryā — yama and niyama before āsana, āsana before prāṇāyāma, prāṇāyāma before pratyāhāra. A path, not a workout.',
        facets: ['Yama · niyama', 'Āsana · prāṇāyāma', 'Dhyāna · samādhi'] },
      { id: 'ayurveda', title: 'Āyurveda', deva: 'आयुर्वेद', epithet: 'Applied medicine',
        meta: ['Tridoṣa · saptadhātu', 'Diet · cleansing', 'Pañcakarma'],
        summary: 'The clinical side of the lifestyle — diagnosis by doṣa-balance, food as the principal medicine, seasonal cleansing (pañcakarma), and the rejuvenative protocols (rasāyana) that close the loop.',
        facets: ['Diet', 'Pañcakarma', 'Rasāyana'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Nāstika Darśanas
  'nastika-darshanas': {
    title: 'The Nāstika Darśanas',
    deva: 'नास्तिक दर्शनानि',
    crumb: ['Library', 'Philosophy', 'Nāstika Darśanas'],
    lede: 'Three schools — Cārvāka, Bauddha and Jaina — that decline the authority of the Veda and were therefore classed nāstika by their orthodox opponents. The word does not mean “atheist”; it means “those who say na — those who do not accept.” Indic philosophy as argued by its sharpest counter-positions.',
    layout: 'tabs',
    items: [
      { id: 'carvaka', title: 'Cārvāka', deva: 'चार्वाक', epithet: 'The school of materialism',
        meta: ['Bṛhaspati (legendary)', 'Lokāyata · “of the world”', 'Pratyakṣa-only'],
        summary: 'A consistent materialism: only the directly perceived is real, the body is the self, consciousness arises from the four elements as wine arises from grain, and the categories of soul, rebirth, karma and merit are inferences made on insufficient evidence. The school’s own texts are lost; we know it almost entirely through the careful refutations of its opponents — and through the late Tattvopaplava-siṃha.',
        opening: { deva: 'यावज्जीवेत् सुखं जीवेत् ऋणं कृत्वा घृतं पिबेत् ।', trans: '“While one lives, let one live happily — even if one must take a loan to drink ghee. For once the body is reduced to ashes, how can it return?”', cite: 'Attributed to Cārvāka · Sarva-darśana-saṅgraha 1' },
        facets: ['Materialism', 'Perception only', 'Refused inference', 'Refused śabda'] },
      { id: 'bauddha', title: 'Bauddha', deva: 'बौद्ध', epithet: 'The Buddhist school',
        meta: ['Gautama Buddha · 5th c. BCE', 'Four Noble Truths · Eightfold Path', 'Theravāda · Mahāyāna · Vajrayāna'],
        summary: 'Born of the Buddha’s teaching at Sarnath. Reality is impermanent (anitya), unsatisfactory (duḥkha), and without a fixed self (anātman). All things arise in dependence (pratītya-samutpāda). Across two and a half millennia the school splits into the Theravāda, the Mahāyāna and the Vajrayāna, and inside the Mahāyāna into the Mādhyamaka of Nāgārjuna and the Yogācāra of Asaṅga and Vasubandhu — schools that argue with each other as sharply as with anyone outside Buddhism.',
        opening: { deva: 'इदं दुःखं आर्यसत्यम् ।', trans: '“This is the noble truth of suffering. This is its arising. This is its cessation. This is the path leading to cessation.”', cite: 'Dhamma-cakka-pavattana-sutta · paraphrase' },
        facets: ['Anātman · no-self', 'Pratītya-samutpāda', 'Madhyamaka', 'Yogācāra'] },
      { id: 'jaina', title: 'Jaina', deva: 'जैन', epithet: 'The Jain school',
        meta: ['Mahāvīra · 24th tīrthaṅkara', 'Digambara · Śvetāmbara', 'Tattvārtha-sūtra · Umāsvāti'],
        summary: 'A radical pluralism. Reality has infinitely many aspects (anekānta), every statement is true only from a standpoint (syādvāda), and any single description is partial. From these flow the central Jain commitments: rigorous ahiṃsā in thought, speech and act; a clear ontology of jīva (soul) and ajīva (matter); and a programme of liberation through right view, right knowledge and right conduct.',
        opening: { deva: 'अहिंसा परमो धर्मः ।', trans: '“Non-injury is the supreme dharma.”', cite: 'Mahābhārata · Anuśāsana-parva 116, echoed in every Jain school' },
        facets: ['Ahiṃsā', 'Anekānta · syādvāda', 'Jīva & ajīva', 'Two schools'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Puranas
  puranas: {
    title: 'The Purāṇas',
    deva: 'पुराणानि',
    crumb: ['Library', 'Smṛti', 'The Purāṇas'],
    lede: 'Eighteen great Purāṇas — and another eighteen sub-Purāṇas — taken together as a kind of people’s Veda. By the classical period they were sorted into three groups according to the predominant guṇa: Vaiṣṇava (sattva), Brāhma (rajas) and Śaiva (tamas). Every Purāṇa is in principle expected to treat five subjects: creation, dissolution, dynasties, the manvantaras, and royal genealogies.',
    layout: 'tabs',
    items: [
      { id: 'vaishnava', title: 'Vaiṣṇava (sattva)', deva: 'वैष्णव', epithet: 'Six Purāṇas of Viṣṇu',
        meta: ['Viṣṇu · Bhāgavata · Nāradīya', 'Garuḍa · Padma · Varāha', 'Sattva-pradhāna'],
        summary: 'The six Purāṇas in which Viṣṇu is the supreme deity. The Bhāgavata, with its account of Kṛṣṇa, is the single most influential of all eighteen — the source of every later bhakti tradition from the Tamil ālvārs to Caitanya.',
        opening: { deva: 'धर्मः प्रोज्झितकैतवोऽत्र परमो निर्मत्सराणां सताम् ।', trans: '“The supreme dharma — freed of every motive but truth — is set forth here for the good who bear no envy.”', cite: 'Bhāgavata-purāṇa · 1.1.2' },
        facets: ['Bhāgavata-purāṇa', 'Avatāra theology', 'Source of bhakti'] },
      { id: 'brahma', title: 'Brāhma (rajas)', deva: 'ब्राह्म', epithet: 'Six Purāṇas of Brahmā',
        meta: ['Brahma · Brahmāṇḍa · Brahmavaivarta', 'Mārkaṇḍeya · Bhaviṣya · Vāmana', 'Rajas-pradhāna'],
        summary: 'The middle group, centred on Brahmā. The Mārkaṇḍeya-purāṇa contains the Devī-māhātmya — the seven-hundred-verse hymn to the Goddess that is recited at every Navarātri. The Bhaviṣya-purāṇa preserves a striking layer of late material on what the tradition called “future” history.',
        opening: { deva: 'या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता ।', trans: '“She who abides in all beings as power — to her, salutation; to her, salutation.”', cite: 'Devī-māhātmya · 5.14 (Mārkaṇḍeya-purāṇa)' },
        facets: ['Devī-māhātmya', 'Cosmogony', 'Royal genealogies'] },
      { id: 'shaiva', title: 'Śaiva (tamas)', deva: 'शैव', epithet: 'Six Purāṇas of Śiva',
        meta: ['Śiva · Liṅga · Skanda', 'Agni · Matsya · Kūrma', 'Tamas-pradhāna'],
        summary: 'The six Purāṇas in which Śiva is supreme. The Skanda is the longest of all eighteen; the Liṅga organises the metaphysics of Śaiva-Siddhānta; the Agni and the Matsya read like encyclopaedias — covering everything from temple-building to grammar.',
        opening: { deva: 'ॐ नमः शिवाय ।', trans: '“Aum — salutation to Śiva.”', cite: 'Pañcākṣara-mantra · pan-Śaiva' },
        facets: ['Skanda · longest', 'Encyclopaedic', 'Pīṭhas & tīrthas'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Dharma-śāstra
  dharmashastra: {
    title: 'Dharma-śāstra',
    deva: 'धर्मशास्त्र',
    crumb: ['Library', 'Smṛti', 'Dharma-śāstra'],
    lede: 'The codes — smṛti texts that translate dharma into a working civil law for the householder, the king and the court. The largest of them, the Manusmṛti, ran for centuries as the operating manual of brahmanical society; the others tightened, contested and updated it.',
    layout: 'tabs',
    items: [
      { id: 'manu', title: 'Manusmṛti', deva: 'मनुस्मृति', epithet: 'The first of the codes',
        meta: ['12 chapters · 2,694 verses', '~2nd c. BCE – 2nd c. CE', 'Most-cited dharma-text'],
        summary: 'The foundational dharma-text. Twelve chapters cover the origin of the world, the four varṇas, the duties of each, the law of marriage and inheritance, the duties of the king, criminal and civil procedure, and the soul’s journey after death. Read continuously and continuously argued with for two thousand years.',
        opening: { deva: 'विद्वद्भिः सेवितः सद्भिर्नित्यमद्वेषरागिभिः ।\nहृदयेनाभ्यनुज्ञातो यो धर्मस्तं निबोधत ॥', trans: '“Hear that dharma which is followed by the wise and the good, ever free of envy and attachment, and which the heart itself approves.”', cite: 'Manusmṛti · 2.1' },
        facets: ['12 adhyāyas', 'Varṇa-dharma', 'Rāja-dharma', 'Most-commented'] },
      { id: 'yajnavalkya', title: 'Yājñavalkya-smṛti', deva: 'याज्ञवल्क्यस्मृति', epithet: 'The lawyer’s code',
        meta: ['3 kāṇḍas · ~1,000 verses', '~3rd – 5th c. CE', 'Mitākṣarā commentary'],
        summary: 'A tighter, more lawyerly successor to Manu. Three sections — ācāra (custom), vyavahāra (procedure), prāyaścitta (expiation). The mediaeval Mitākṣarā commentary on this text became the operative law of inheritance across most of India until 1956.',
        opening: { deva: 'यज्ञवल्क्यं मुनिश्रेष्ठं याज्ञिकाः पर्युपासते ।', trans: '“The yajña-priests sit at the feet of Yājñavalkya, foremost of sages, and ask him: pray, recite the laws of the four varṇas.”', cite: 'Yājñavalkya-smṛti · 1.1' },
        facets: ['Three kāṇḍas', 'Mitākṣarā', 'Inheritance law'] },
      { id: 'narada', title: 'Nārada-smṛti', deva: 'नारदस्मृति', epithet: 'A code for litigation',
        meta: ['~5th c. CE', '18 titles of law', 'Procedural focus'],
        summary: 'The most purely juridical of the smṛtis — almost entirely procedural. Eighteen titles of law (vyavahāra-padas) for the courtroom: debt, deposit, partnership, sale, theft, defamation, inheritance. The first Indian text to treat written contracts and witnesses as a system.',
        facets: ['Vyavahāra-pada', 'Written contract', 'Witness law'] },
      { id: 'brihaspati', title: 'Bṛhaspati-smṛti', deva: 'बृहस्पतिस्मृति', epithet: 'On evidence and procedure',
        meta: ['~6th – 7th c. CE', 'Survives only in citation', 'Successor of Nārada'],
        summary: 'A later, finer-grained refinement of legal procedure — only fragments survive directly, but it is quoted by every later commentator and reconstructed from the digests. The first dharma-text to make a clear hierarchy between written, witnessed and inferred evidence.',
        facets: ['Reconstructed text', 'Evidence-hierarchy', 'Procedural code'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Artha-śāstra
  arthashastra: {
    title: 'Artha-śāstra',
    deva: 'अर्थशास्त्र',
    crumb: ['Library', 'Applied', 'Artha-śāstra'],
    lede: 'The science of artha — material welfare, polity, statecraft, war, espionage and the running of an economy. Kauṭilya’s Arthaśāstra is the central text; the later nīti-tradition trimmed and updated it for the medieval court.',
    layout: 'tabs',
    items: [
      { id: 'kautilya', title: 'Kauṭilīya Arthaśāstra', deva: 'कौटिलीयार्थशास्त्र', epithet: 'Kauṭilya’s manual of state',
        meta: ['15 adhikaraṇas · 150 chapters', '~4th c. BCE (Mauryan)', 'Rediscovered 1905'],
        summary: 'A manual for the running of a state by a chief minister — almost certainly Kauṭilya (also Cāṇakya), the strategist of the Mauryan empire. Fifteen books cover the training of the prince, the appointment of officers, civil and criminal law, taxation, foreign relations, war, and the management of intelligence networks. Rediscovered in a Mysore library in 1905 after centuries of being known only through citation.',
        opening: { deva: 'पृथिव्या लाभे पालने च यावन्त्यर्थशास्त्राणि पूर्वाचार्यैः प्रस्थापितानि प्रायशस्तानि संहृत्यैकमिदमर्थशास्त्रं कृतम् ।', trans: '“This single Arthaśāstra has been composed by drawing together the science as the earlier teachers set it down — for the acquisition and the keeping of the earth.”', cite: 'Arthaśāstra · 1.1' },
        facets: ['15 adhikaraṇas', 'Maṇḍala theory', 'Intelligence-state'] },
      { id: 'kamandaka', title: 'Kāmandakīya Nītisāra', deva: 'कामन्दकीय नीतिसारः', epithet: 'A medieval abridgement',
        meta: ['~7th – 8th c. CE', '20 sargas · ~1,500 verses', 'Versified Kauṭilya'],
        summary: 'Kāmandaka condenses the Arthaśāstra into elegant verse for a courtly audience — the seven limbs of the state (svāmin, amātya, janapada, durga, kośa, daṇḍa, mitra), the six modes of policy (saṃdhi, vigraha, yāna, āsana, dvaidhī-bhāva, saṃśraya), and the maṇḍala of friend and enemy.',
        facets: ['Saptāṅga', 'Ṣāḍguṇya', 'Maṇḍala'] },
      { id: 'shukra', title: 'Śukra-nīti', deva: 'शुक्रनीति', epithet: 'The mythical kingbook',
        meta: ['Attributed to Śukrācārya', '4 chapters', 'Practical breadth'],
        summary: 'A late compendium that opens the catalogue beyond Kauṭilya — covers everything from town-planning to the assay of metals, from the duties of physicians to the management of elephants and horses. Its precise date is contested; its practical breadth is not.',
        facets: ['Late compendium', 'Civic admin', 'Town & guild'] },
      { id: 'manu-raja', title: 'Manusmṛti — Rāja-dharma', deva: 'राज-धर्म', epithet: 'Polity within the dharma-code',
        meta: ['Manu · chs 7 & 8', '~600 verses', 'Polity as dharma'],
        summary: 'Manu’s seventh and eighth chapters are themselves a complete miniature arthaśāstra. The king as protector, the fourfold expedient (sāma · dāna · bheda · daṇḍa), the law of taxation, the duty of fining the strong before the weak — read as the bridge between dharma-śāstra and polity proper.',
        facets: ['Sāma–dāna–bheda–daṇḍa', 'Daṇḍa-nīti', 'Mahā-pātakas'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Kāvya & Nāṭya
  kavya: {
    title: 'Kāvya & Nāṭya',
    deva: 'काव्य · नाट्य',
    crumb: ['Library', 'Literature', 'Kāvya & Nāṭya'],
    lede: 'Classical Sanskrit literature — the kāvya of the courtly poets and the nāṭya of the dramatic stage, the long mahākāvyas, the wandering messenger-poems, and the prose tale of the fox and the lion. Where Indic literary art reaches its self-aware peak.',
    layout: 'tabs',
    items: [
      { id: 'mahakavya', title: 'Mahākāvya', deva: 'महाकाव्य', epithet: 'The great court-poems',
        meta: ['Kālidāsa · Bhāravi · Māgha', 'Śrīharṣa · Aśvaghoṣa', 'Five canonical mahākāvyas'],
        summary: 'The long courtly epic in elaborately ornamented verse. The five canonical mahākāvyas — Kālidāsa’s Raghuvaṃśa and Kumārasambhava, Bhāravi’s Kirātārjunīya, Māgha’s Śiśupālavadha, Śrīharṣa’s Naiṣadhīyacarita — set the bar that every later Sanskrit poet aimed for.',
        opening: { deva: 'वागर्थाविव सम्पृक्तौ वागर्थप्रतिपत्तये ।\nजगतः पितरौ वन्दे पार्वतीपरमेश्वरौ ॥', trans: '“Joined as speech and meaning are joined — for the gaining of speech and meaning — I bow to the parents of the world, Pārvatī and Parameśvara.”', cite: 'Kālidāsa · Raghuvaṃśa 1.1' },
        facets: ['Kālidāsa', 'Five canonical', 'Ornamented verse'] },
      { id: 'natya', title: 'Nāṭya', deva: 'नाट्य', epithet: 'Sanskrit drama',
        meta: ['Bhāsa · Śūdraka · Kālidāsa', 'Daśarūpaka — 10 forms', 'Bharata · Nāṭya-śāstra'],
        summary: 'The classical theatre — Bhāsa’s Svapnavāsavadattam, Śūdraka’s Mṛcchakaṭika, Kālidāsa’s Śakuntalā, Bhavabhūti’s Uttara-rāma-carita, Viśākhadatta’s Mudrārākṣasa. Governed by Bharata’s Nāṭya-śāstra — the world’s oldest surviving treatise on dramaturgy.',
        opening: { deva: 'या सृष्टिः स्रष्टुराद्या वहति विधिहुतं या हविर्या च होत्री ।', trans: 'The opening invocation of Kālidāsa’s Abhijñāna-Śākuntalam — calling the eight forms of Śiva as benediction before the play begins.', cite: 'Kālidāsa · Abhijñāna-Śākuntalam · Nāndī 1' },
        facets: ['Nāṭya-śāstra', 'Daśa-rūpaka', 'Rasa-theory'] },
      { id: 'khanda', title: 'Khaṇḍa-kāvya', deva: 'खण्डकाव्य', epithet: 'The shorter lyric',
        meta: ['Meghadūta', 'Ṛtusaṃhāra', 'Caurapañcāśikā'],
        summary: 'The shorter lyric — a single mood, a single voyage. Kālidāsa’s Meghadūta sends a yakṣa’s message on a cloud across India; his Ṛtusaṃhāra is a six-season cycle; Bilhaṇa’s Caurapañcāśikā is the fifty stanzas a condemned poet writes about his lover the night before his execution.',
        opening: { deva: 'कश्चित्कान्ताविरहगुरुणा स्वाधिकारात्प्रमत्तः शापेनास्तंगमितमहिमा वर्षभोग्येण भर्तुः ।', trans: '“A certain yakṣa, neglectful of his charge — heavy with his beloved’s absence, his glory dimmed by his master’s curse for the term of a year…”', cite: 'Kālidāsa · Meghadūta · Pūrva-megha 1' },
        facets: ['Messenger-poem', 'Season-cycle', 'Single mood'] },
      { id: 'katha', title: 'Kathā & Ākhyāyikā', deva: 'कथा · आख्यायिका', epithet: 'The prose tale',
        meta: ['Pañcatantra', 'Hitopadeśa', 'Daśakumāracarita · Kādambarī'],
        summary: 'The prose tale — Viṣṇuśarman’s Pañcatantra (the most-translated Indic book in the world), Nārāyaṇa’s Hitopadeśa, Daṇḍin’s Daśakumāracarita and Bāṇa’s Kādambarī. Stories told to teach polity, or for sheer narrative pleasure.',
        opening: { deva: 'अथेदं प्रथमं तन्त्रं मित्रभेदो नाम ।', trans: '“And now this first book, called Mitra-bheda — the splitting of friends.”', cite: 'Pañcatantra · Book I' },
        facets: ['Pañcatantra', 'Nesting-frame', 'Animal fable'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Indic Sciences & Mathematics
  sciences: {
    title: 'Indic Sciences & Mathematics',
    deva: 'गणितम् · ज्योतिषम्',
    crumb: ['Library', 'Applied', 'Sciences & Mathematics'],
    lede: 'A long arc — from the geometric altars of the Śulba-sūtras, through the decimal system with zero, the trigonometry of Āryabhaṭa, the algebra of Brahmagupta and Bhāskara, to the infinite-series calculus of the Kerala school. Older, longer, and more continuous than the credit it usually receives.',
    layout: 'grid',
    items: [
      { id: 'shulba', title: 'Śulba-sūtras', deva: 'शुल्बसूत्राणि', epithet: 'Geometry of the altar',
        meta: ['~800 – 200 BCE', 'Baudhāyana · Āpastamba', 'Kalpa-sūtra appendix'],
        summary: 'The earliest surviving Indic mathematics — manuals for the precise geometric construction of fire-altars. Baudhāyana states the “Pythagorean” theorem two centuries before Pythagoras, and includes the first known explicit value of √2 to five decimal places.',
        facets: ['Earliest Indic math', 'Altar-geometry', '√2 to 5 places'] },
      { id: 'aryabhata', title: 'Āryabhaṭa', deva: 'आर्यभट', epithet: 'The first dated astronomer',
        meta: ['476 – c. 550 CE', 'Āryabhaṭīya · 121 verses', 'Kusumapura'],
        summary: 'A single short text — 121 verses — sets out a complete astronomy and a complete mathematics. The earth is a sphere that rotates; the sine table is given (Āryabhaṭa coins jyā); π is approximated to 3.1416; the algorithm for solving the “pulveriser” (kuṭṭaka) equation is laid down.',
        facets: ['Rotating earth', 'Sine table', 'π ≈ 3.1416'] },
      { id: 'brahmagupta', title: 'Brahmagupta', deva: 'ब्रह्मगुप्त', epithet: 'The author of zero',
        meta: ['c. 598 – 668 CE', 'Brāhma-sphuṭa-siddhānta', 'Bhinnamāla, Rajasthan'],
        summary: 'The first mathematician anywhere to give the rules of arithmetic with zero and negative numbers — treating positives as “fortunes” and negatives as “debts.” His Brāhma-sphuṭa-siddhānta also gives the general solution to ax² + bx + c = 0 and the cyclic quadrilateral formula that bears his name.',
        facets: ['Zero & negatives', 'Pell equation', 'Cyclic quadrilateral'] },
      { id: 'bhaskara', title: 'Bhāskara II', deva: 'भास्कराचार्य', epithet: 'Līlāvatī · Bījagaṇita',
        meta: ['1114 – c. 1185 CE', 'Siddhānta-śiromaṇi', 'Vijjadavīḍa, Karnataka'],
        summary: 'The Siddhānta-śiromaṇi gathers the whole arc in four parts — Līlāvatī on arithmetic (still taught from in Sanskrit schools), Bījagaṇita on algebra, and two siddhāntas on planetary astronomy. Contains a clear conceptual precursor of the differential calculus, six centuries before Newton.',
        facets: ['Līlāvatī', 'Algebra (bīja)', 'Pre-calculus'] },
      { id: 'kerala', title: 'Kerala school', deva: 'केरल-गणित-सम्प्रदायः', epithet: 'Mādhava and his lineage',
        meta: ['14th – 16th c. CE', 'Mādhava · Nīlakaṇṭha · Jyeṣṭhadeva', 'Yuktibhāṣā'],
        summary: 'A lineage of mathematicians in fourteenth-to-sixteenth-century Kerala — Mādhava of Saṅgamagrāma and his students — who derived the infinite-series expansions for sine, cosine and arctangent two centuries before Newton and Leibniz. The Yuktibhāṣā is the first known prose mathematics in any Indic language.',
        facets: ['Infinite series', 'sin · cos · arctan', 'Yuktibhāṣā'] },
      { id: 'pingala', title: 'Piṅgala’s combinatorics', deva: 'पिङ्गल-छन्दःसूत्राणि', epithet: 'Binary, before binary',
        meta: ['~3rd – 2nd c. BCE', 'Chanda-sūtra · 8 chapters', 'Counted metres'],
        summary: 'The Chanda-sūtra’s combinatorial machinery — how many distinct metres of a given length are possible — gives the earliest known description of what is now called Pascal’s triangle (the mātrā-meru), an explicit rule for binary representation of numbers, and the recurrence we now call Fibonacci.',
        facets: ['Mātrā-meru ≈ Pascal’s Δ', 'Binary numerals', 'Fibonacci'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Subhāṣita & Nīti
  subhashita: {
    title: 'Subhāṣita & Nīti',
    deva: 'सुभाषित · नीति',
    crumb: ['Library', 'Literature', 'Subhāṣita & Nīti'],
    lede: 'The aphoristic tradition — the wit-literature that distils the rest of the canon into single verses you can quote across a dinner table. Where the dharma-śāstras prescribe and the kāvyas describe, the subhāṣitas observe.',
    layout: 'tabs',
    items: [
      { id: 'bhartrihari', title: 'Bhartṛhari · Trishataka', deva: 'भर्तृहरि-त्रिशतकम्', epithet: 'Three hundreds on three lives',
        meta: ['~5th c. CE', '3 śatakas · 300+ verses', 'Nīti · Śṛṅgāra · Vairāgya'],
        summary: 'Three sets of a hundred verses — one on worldly conduct (nīti), one on love (śṛṅgāra), one on renunciation (vairāgya). The same Bhartṛhari is also credited with the Vākyapadīya, one of the most important works of Indic philosophy of language.',
        opening: { deva: 'दिक्कालाद्यनवच्छिन्नानन्तचिन्मात्रमूर्तये ।\nस्वानुभूत्येकमानाय नमः शान्ताय तेजसे ॥', trans: '“To the boundless self-cognising radiance, by space and time uncircumscribed, knowable only in its own experience — to that quiet brilliance, salutation.”', cite: 'Bhartṛhari · Nīti-śataka · maṅgala' },
        facets: ['Three śatakas', 'Three rasas', 'Most-quoted'] },
      { id: 'chanakya', title: 'Cāṇakya-nīti', deva: 'चाणक्य-नीति', epithet: 'The minister’s aphorisms',
        meta: ['Attributed to Kauṭilya', '17 chapters', 'Householder-counsel'],
        summary: 'A loosely-organised collection of practical aphorisms attributed to Kauṭilya — on choosing friends, raising children, recognising fools, judging companions. Probably not by Kauṭilya himself, but a worthy successor to his Arthaśāstra in tone.',
        facets: ['Household-nīti', 'Practical aphorisms'] },
      { id: 'vidura', title: 'Vidura-nīti', deva: 'विदुर-नीति', epithet: 'Counsel in the Mahābhārata',
        meta: ['Mahābhārata · Udyoga-parva 33–40', '~8 chapters', 'Royal counsel'],
        summary: 'Embedded inside the Mahābhārata — Vidura, half-brother of the blind king Dhṛtarāṣṭra, is asked through the night for the rule of polity and dharma. His answer is a small free-standing classic on the conduct of kings, the management of fools, and what makes a man trustworthy.',
        facets: ['Inside Mahābhārata', 'Royal counsel', 'Night-dialogue'] },
      { id: 'panchatantra', title: 'Pañcatantra', deva: 'पञ्चतन्त्र', epithet: 'Nīti by animal fable',
        meta: ['Viṣṇuśarman · ~3rd c. CE', '5 books · 84 stories', 'Most-translated Indic text'],
        summary: 'Five interlocking books of animal-fable, framed as a tutor’s programme to teach three foolish princes the running of a kingdom in six months. Travelled from Sanskrit through Middle Persian into Arabic (Kalīla wa Dimna), Greek, Latin, every major European vernacular — the most widely translated work of Indic literature ever written.',
        facets: ['Five books', 'Frame-tale', 'World-circulating'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Modern Indic Thought
  modern: {
    title: 'Modern Indic Thought',
    deva: 'आधुनिक भारतीय चिन्तनम्',
    crumb: ['Library', 'Philosophy', 'Modern Indic Thought'],
    lede: 'The long nineteenth and twentieth centuries — how the Indic corpus was reread, contested and remade under colonial rule and after independence. Reformers, mystics, poets, jurists; men and women who took the canon apart and tried to put it back together for a country that had become a republic.',
    layout: 'grid',
    items: [
      { id: 'rammohan', title: 'Rammohan Roy', deva: 'राममोहन राय', epithet: 'The first reformer',
        meta: ['1772 – 1833', 'Brāhmo Samāj · 1828', 'Sati abolition · 1829'],
        summary: 'The opening figure. Translated the principal Upaniṣads into Bengali and English, founded the Brāhmo Samāj as a reformed monotheistic congregation, and led the campaign that ended sati. A Sanskritist, an Arabicist, and the first Indian to argue for liberal reform on Indic philosophical grounds.',
        facets: ['Brāhmo Samāj', 'Upaniṣad translations', 'Sati abolition'] },
      { id: 'vivekananda', title: 'Swami Vivekananda', deva: 'स्वामी विवेकानन्द', epithet: 'Practical Vedānta',
        meta: ['1863 – 1902', 'Disciple of Ramakrishna', 'Chicago address · 1893'],
        summary: 'Took the Advaita-Vedānta of Śaṅkara out of the monastery and made it a public philosophy of work, service and self-reliance. The Chicago address of 1893 is the conventional date for the modern Indic tradition stepping onto the world stage; the Rāmakṛṣṇa Mission carried it forward.',
        facets: ['Practical Vedānta', 'Rāmakṛṣṇa Mission', 'World’s Parliament'] },
      { id: 'aurobindo', title: 'Sri Aurobindo', deva: 'श्रीअरविन्दः', epithet: 'Integral Yoga',
        meta: ['1872 – 1950', 'Pondicherry · 1910', 'The Life Divine'],
        summary: 'Cambridge-educated revolutionary turned mystic philosopher. The Life Divine is a five-thousand-page rereading of the Upaniṣads and the Gītā as a single evolutionary process — matter, life, mind, and the “supermind” still to come. His Pondicherry ashram became the seedbed of Integral Yoga.',
        facets: ['Integral Yoga', 'The Life Divine', 'Supermind'] },
      { id: 'tagore', title: 'Rabindranath Tagore', deva: 'रवीन्द्रनाथ ठाकुर', epithet: 'Poet of the universal',
        meta: ['1861 – 1941', 'Nobel Prize · 1913', 'Śāntiniketan · 1901'],
        summary: 'Bengali poet, novelist, painter, educator. First non-European Nobel laureate in literature. Reread the Upaniṣads as a poetics of the universal self, founded Śāntiniketan as an experiment in a kind of education that was neither colonial nor narrowly indigenous, and renounced his knighthood after Jallianwala Bagh.',
        facets: ['Gītāñjali', 'Śāntiniketan', 'Universalist'] },
      { id: 'gandhi', title: 'Mohandas Gandhi', deva: 'मोहनदास गान्धी', epithet: 'Satya & ahiṃsā',
        meta: ['1869 – 1948', 'Satyāgraha · 1906', 'Independence · 1947'],
        summary: 'Rebuilt ahiṃsā as a mass political method. Combined the Jain inheritance of non-injury, the Bhagavad-gītā’s teaching on detached action, and Tolstoy’s Christian anarchism into satyāgraha — “holding firmly to the truth.” The Salt March of 1930 made it a method any colonised people could attempt.',
        facets: ['Satyāgraha', 'Ahiṃsā', 'Sarvodaya'] },
      { id: 'ambedkar', title: 'B. R. Ambedkar', deva: 'भीमराव अम्बेडकर', epithet: 'Architect of the Constitution',
        meta: ['1891 – 1956', 'Chair, Drafting Committee', 'Conversion to Buddhism · 1956'],
        summary: 'Economist, jurist, and the principal author of the Indian Constitution. A Dalit who took two doctorates at Columbia and the LSE, then turned them on the Indic canon — reading Manu against Manu, the Buddha against Brahminism. Converted publicly to Buddhism in 1956 with half a million followers.',
        facets: ['Constitution of India', 'Annihilation of Caste', 'Navayāna Buddhism'] },
      { id: 'krishnamurti', title: 'J. Krishnamurti', deva: 'जिड्डु कृष्णमूर्ति', epithet: 'Without a tradition',
        meta: ['1895 – 1986', 'Dissolution of the Order · 1929', 'Saanen · Brockwood Park'],
        summary: 'Selected as a child to lead the Theosophists’ World-Teacher project; dissolved that project at age 34 and spent the next fifty-seven years arguing, in unrhetorical English, that no method, guru or tradition can deliver the kind of seeing he meant. The most influential anti-traditional voice the tradition produced.',
        facets: ['Anti-method', 'Choiceless awareness', '“Pathless land”'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Bhagavad Gītā
  gita: {
    title: 'Bhagavad Gītā',
    deva: 'भगवद्गीता',
    crumb: ['Library', 'Smṛti', 'Bhagavad Gītā'],
    lede: 'Seven hundred verses spoken between Kṛṣṇa and Arjuna on the battlefield of Kurukṣetra — eighteen chapters embedded in the Mahābhārata that became, by the classical period, a self-contained scripture in its own right. The most-commented Indic text outside the Upaniṣads.',
    layout: 'tabs',
    items: [
      { id: 'karma', title: 'Karma-yoga', deva: 'कर्मयोग', epithet: 'The path of action',
        meta: ['Chapters 2 – 6', 'Niṣkāma-karma', 'Action without grasping'],
        summary: 'The first of the three classical paths the Gītā lays out. Act without attachment to the fruit of action — the work is yours; its result is not. The teaching that resolves Arjuna’s opening refusal to fight, and the heart of Gandhi’s reading of the text.',
        opening: { deva: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन ।\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ॥', trans: '“Yours is the right to action alone, never to its fruits. Be not the cause of the fruit of action — and let not your attachment be to inaction.”', cite: 'Bhagavad Gītā · 2.47' },
        facets: ['Niṣkāma-karma', 'Sva-dharma', 'Action without grasping'] },
      { id: 'bhakti', title: 'Bhakti-yoga', deva: 'भक्तियोग', epithet: 'The path of devotion',
        meta: ['Chapters 7 – 12', 'Prapatti · surrender', 'Twelfth chapter pre-eminent'],
        summary: 'The second path. Devotion to the personal lord (Iśvara) as the most accessible discipline for the embodied human — the teaching that fuelled every later bhakti tradition, from the Ālvārs of Tamil country to the Sants of the north.',
        opening: { deva: 'मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु ।\nमामेवैष्यसि सत्यं ते प्रतिजाने प्रियोऽसि मे ॥', trans: '“Fix your mind on me, devote yourself to me, sacrifice to me, bow to me. To me alone you shall come — this I truly promise you, for you are beloved to me.”', cite: 'Bhagavad Gītā · 18.65' },
        facets: ['Iśvara-praṇidhāna', 'Most accessible path', 'Bhakti as surrender'] },
      { id: 'jnana', title: 'Jñāna-yoga', deva: 'ज्ञानयोग', epithet: 'The path of knowledge',
        meta: ['Chapters 13 – 18', 'Sāṅkhya-yoga', 'Discrimination of kṣetra/kṣetrajña'],
        summary: 'The third path. The discrimination of the field (kṣetra, prakṛti) from its knower (kṣetrajña, puruṣa) — a Sāṅkhya-rooted analysis of body, mind, the three guṇas, and the witness that is none of them. Śaṅkara’s Advaita reading reads the whole Gītā through this final third.',
        opening: { deva: 'इदं शरीरं कौन्तेय क्षेत्रमित्यभिधीयते ।\nएतद्यो वेत्ति तं प्राहुः क्षेत्रज्ञ इति तद्विदः ॥', trans: '“This body, son of Kuntī, is called the field. The one who knows it — him the knowers call the knower-of-the-field.”', cite: 'Bhagavad Gītā · 13.1' },
        facets: ['Kṣetra–kṣetrajña', 'Three guṇas', 'Witness-consciousness'] },
      { id: 'vishvarupa', title: 'Viśva-rūpa', deva: 'विश्वरूप-दर्शन', epithet: 'The eleventh chapter',
        meta: ['Chapter 11', 'Theophany', 'Cosmic-form vision'],
        summary: 'The mid-point and the climax. Arjuna asks to see Kṛṣṇa’s true form; Kṛṣṇa grants divine sight and reveals himself as the universal form — every being, every direction, beginning, middle and end. The verse Oppenheimer recited at Trinity comes from this chapter.',
        opening: { deva: 'पश्य मे पार्थ रूपाणि शतशोऽथ सहस्रशः ।\nनानाविधानि दिव्यानि नानावर्णाकृतीनि च ॥', trans: '“Behold, Pārtha, my forms — in their hundreds, in their thousands — diverse and divine, of varied colours and shapes.”', cite: 'Bhagavad Gītā · 11.5' },
        facets: ['Theophany', 'Mid-text climax', 'Time the destroyer'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Bhakti Traditions
  bhakti: {
    title: 'Bhakti Traditions',
    deva: 'भक्ति-परम्परा',
    crumb: ['Library', 'Practice', 'Bhakti Traditions'],
    lede: 'The devotional turn — a long, plural movement that begins in the Tamil country around the seventh century and rolls northward over the next thousand years. Vernacular poetry, personal address to the Lord, the dignity of every singer regardless of caste, the temple as a community more than a precinct.',
    layout: 'tabs',
    items: [
      { id: 'alvars', title: 'Ālvārs', deva: 'आऴ्वार्', epithet: 'Tamil Vaiṣṇava poet-saints',
        meta: ['6th – 9th c. CE', '12 ālvārs · 4,000 hymns', 'Divya-prabandham'],
        summary: 'Twelve Tamil poet-saints — including the woman Āṇṭāḷ — whose 4,000-verse Divya-prabandham forms the Tamil counterpart of the Veda for Śrīvaiṣṇavas. Sang Viṣṇu in personal, intimate Tamil; opened the temple to the devotional aesthetics that Rāmānuja would later systematise.',
        opening: { deva: 'மணிவண்ணா எங்ஙே மறைந்திருந்தாய்', trans: '“Jewel-hued Lord — where do you hide?” (Āṇṭāḷ, Nācciyār Tirumoḻi)', cite: 'Āṇṭāḷ · Tamil source · 9th c.' },
        facets: ['Tamil śruti', 'Āṇṭāḷ', 'Source of Śrīvaiṣṇavism'] },
      { id: 'nayanars', title: 'Nāyaṉārs', deva: 'नायन्मार्', epithet: 'Tamil Śaiva poet-saints',
        meta: ['6th – 9th c. CE', '63 nāyaṉārs', 'Tēvāram'],
        summary: 'Sixty-three Śaiva counterparts to the Ālvārs. The Tēvāram of Appar, Sambandar and Sundarar, and Māṇikkavācakar’s Tiruvācakam, are the foundational corpus of Tamil Śaiva-Siddhānta. Walked from temple to temple singing Śiva in the local language; the same century the Ālvārs were walking the same paths.',
        opening: { deva: 'பித்தா பிறை சூடி', trans: '“Mad one — wearer of the crescent moon, lord of bull and bow…” (Sundarar)', cite: 'Sundarar · Tēvāram · 9th c.' },
        facets: ['63 nāyaṉārs', 'Tēvāram', 'Tamil Śaiva foundation'] },
      { id: 'sants', title: 'Northern Sants', deva: 'सन्त-परम्परा', epithet: 'Vernacular nirguṇa-bhakti',
        meta: ['14th – 17th c. CE', 'Kabīr · Ravidās · Nāmdev', 'Pan-North, pan-religious'],
        summary: 'A confederation more than a school — Kabīr the weaver, Ravidās the leather-worker, Nāmdev the tailor, Mīrā the Rajput princess, Tulsīdās the brahmin. Sang in Hindi-Avadhī-Braj-Marathi-Punjabi, often refused all temples and all images, addressed an attribute-less divine they each named differently.',
        opening: { deva: 'मन लागो मेरो यार फकीरी में', trans: '“My heart is set, friend, on the dervish life — what use to me are silk and palace?” (Kabīr · paraphrase)', cite: 'Kabīr · Hindi · 15th c.' },
        facets: ['Nirguṇa', 'Vernacular', 'Cross-caste'] },
      { id: 'gaudiya', title: 'Gauḍīya & Vārkarī', deva: 'गौडीय · वारकरी', epithet: 'Caitanya · Tukārām',
        meta: ['16th c. CE', 'Caitanya · Tukārām · Jñāneśvar', 'Saguṇa devotion'],
        summary: 'Two of the great regional crystallisations. The Gauḍīya tradition of Caitanya in Bengal — Kṛṣṇa as the supreme rasa, the saṃkīrtana of the divine names. The Vārkarī tradition of Maharashtra — Viṭṭhal at Paṇḍharpur, Jñāneśvar’s Marathi commentary on the Gītā, the abhaṅgas of Tukārām.',
        facets: ['Bengali · Marathi', 'Caitanya', 'Vārkarī pilgrimage'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Parallel Canons
  parallel: {
    title: 'Parallel Canons',
    deva: 'इतर परम्पराः',
    crumb: ['Library', 'Parallel', 'Other canons'],
    lede: 'Three vast bodies of text that share Indic ground while standing outside the Vedic line. Each runs on its own languages, its own scripts, its own apparatus of commentary; each shaped, and was shaped by, the corpus described in the rest of the library.',
    layout: 'tabs',
    items: [
      { id: 'jain', title: 'Jain Āgamas', deva: 'जैन-आगमाः', epithet: 'In Ardhamāgadhī Prakrit',
        meta: ['Mahāvīra · 6th c. BCE', '12 (or 45) aṅgas', 'Digambara · Śvetāmbara'],
        summary: 'The teachings of the Tīrthaṅkaras, transmitted orally for centuries and finally committed to writing at the council of Valabhī in the fifth century CE. The Tattvārtha-sūtra of Umāsvāti is the rare text accepted by both Digambara and Śvetāmbara schools — a Jain analogue of the Brahma-sūtras.',
        opening: { deva: 'अहिंसा-संयम-तपो धर्मः', trans: '“Dharma is non-injury, restraint, and austerity.”', cite: 'Daśavaikālika-sūtra · 1.1' },
        facets: ['Ardhamāgadhī', 'Tattvārtha-sūtra', 'Two schools'] },
      { id: 'buddhist', title: 'Buddhist Tipiṭaka', deva: 'त्रिपिटक', epithet: 'In Pali',
        meta: ['Buddha · 5th c. BCE', 'Tipiṭaka — three baskets', 'Theravāda canon'],
        summary: 'The Pali canon — three baskets (piṭakas): Vinaya (the monastic code), Sutta (the Buddha’s discourses), Abhidhamma (the systematic analysis of mind and phenomena). Later Mahāyāna sūtras — the Lotus, the Perfection of Wisdom, the Laṅkāvatāra — were composed in Sanskrit and survive principally in Tibetan and Chinese translation.',
        opening: { deva: 'सब्बे संखारा अनिच्चा', trans: '“All conditioned things are impermanent. All conditioned things are unsatisfactory. All things — conditioned and unconditioned — are not-self.”', cite: 'Dhammapada · 20.5 – 7' },
        facets: ['Vinaya · Sutta · Abhidhamma', 'Theravāda · Mahāyāna', 'Pali · Sanskrit'] },
      { id: 'sikh', title: 'Gurū Granth Sāhib', deva: 'गुरु ग्रन्थ साहिब', epithet: 'The Ādi Granth',
        meta: ['Compiled 1604 · Final 1708', 'Gurmukhī script', '1,430 aṅgas'],
        summary: 'The scripture of the Sikhs, compiled by the fifth Sikh guru, Arjun, and given final form by the tenth, Gobind Singh, who installed it as the eternal guru. Includes the compositions of the first ten gurus along with hymns by Kabīr, Ravidās, Nāmdev, Farīd and other bhagats from across the religious spectrum.',
        opening: { deva: 'ੴ ਸਤਿ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ।', trans: '“One — the eternal — whose name is Truth, the doer, the formless.”', cite: 'Mūl Mantra · Gurū Granth Sāhib · 1' },
        facets: ['Mūl Mantra', '1,430 aṅgas', 'Pan-religious hymns'] },
    ],
  },

  // ──────────────────────────────────────────────────────── Śruti & Smṛti (primer)
  'shruti-smriti': {
    title: 'Śruti & Smṛti',
    deva: 'श्रुति · स्मृति',
    crumb: ['Library', 'Field guide', 'Śruti & Smṛti'],
    lede: 'A two-tier distinction that holds the entire Indic corpus together — and has no exact European parallel. The field guide.',
    layout: 'primer',
  },
};
